use std::{
    fs::{read_to_string, write},
    io::Result,
    path::{Path, PathBuf},
};

use glob::glob;

fn main() -> Result<()> {
    let proto_root = PathBuf::from("src/proto/opentelemetry-proto");
    let include_path = proto_root.clone();

    let proto_paths: Vec<_> = glob(&format!("{}/**/*.proto", proto_root.display()))
        .expect("Failed to read glob pattern")
        .filter_map(|result| result.ok())
        .collect();

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let descriptor_path = out_dir.join("opentelemetry-proto.desc");

    tonic_build::configure()
        .build_client(true)
        .build_server(true)
        .file_descriptor_set_path(&descriptor_path)
        .compile(&proto_paths, &[include_path])?;

    // The vendored OTLP `.proto` files must remain byte-for-byte identical to upstream due to being
    // copied directly out of the upstream git repository. One upstream comment contains an indented
    // JSON example that prost copies into the generated Rust source with enough indentation for
    // rustdoc to interpret it as a Rust doctest. The example is valid documentation but invalid
    // Rust, so `cargo test --doc --workspace` fails.
    //
    // The other seemingly applicable approaches do not work here:
    // - `#[doc(hidden)]` hides rendered documentation but does not suppress doctests extracted from
    //   child items in an included generated file.
    // - `[lib] doctest = false` is bypassed because CI explicitly requests doctests with `--doc`.
    // - tonic-build 0.11's `disable_comments` only controls generated service/RPC comments, not the
    //   protobuf field comments generated by prost.
    //
    // Normalize only the generated Rust copy, leaving the upstream source and its documentation
    // untouched. This turns the example into ordinary indented prose instead of a doctest.
    sanitize_generated_trace_docs(&out_dir)?;
    write_static_descriptor_reference(&descriptor_path, &out_dir)?;

    Ok(())
}

fn sanitize_generated_trace_docs(out_dir: &Path) -> Result<()> {
    let generated_file = out_dir.join("opentelemetry.proto.trace.v1.rs");
    let existing = read_to_string(&generated_file)?;
    let sanitized = existing.replace("    ///     ", "    ///   ");

    if existing != sanitized {
        write(generated_file, sanitized)?;
    }

    Ok(())
}

fn write_static_descriptor_reference(descriptor_path: &Path, out_dir: &Path) -> Result<()> {
    let include_line = format!(
        "pub static DESCRIPTOR_BYTES: &[u8] = include_bytes!(r\"{}\");\n",
        descriptor_path.display()
    );

    let include_file = out_dir.join("opentelemetry-proto.rs");
    let existing = read_to_string(&include_file).ok();
    if existing.as_deref() != Some(&include_line) {
        write(&include_file, include_line)?;
    }

    Ok(())
}
