RUN=./scripts/docker-compose-run.sh

# default target

all: verify

# checks

check: check-code check-fmt check-style check-generate check-blog check-version check-examples

check-code: init-target-dir
	$(RUN) check-code

check-fmt: init-target-dir
	$(RUN) check-fmt

check-style:
	$(RUN) check-style

check-generate:
	$(RUN) check-generate

check-blog:
	$(RUN) check-blog

check-version:
	$(RUN) check-version

check-examples: build-archive
	$(RUN) check-examples

# build artifacts

build-archive: init-target-dir
	$(RUN) build-archive

package-deb: build-archive
	$(RUN) package-deb

package-rpm: build-archive
	$(RUN) package-rpm

# verify RPM packages

verify-rpm-amazonlinux-1: package-rpm
	$(RUN) verify-rpm-amazonlinux-1

verify-rpm-amazonlinux-2: package-rpm
	$(RUN) verify-rpm-amazonlinux-2

verify-rpm-centos-7: package-rpm
	$(RUN) verify-rpm-centos-7

verify-rpm: verify-rpm-amazonlinux-1 verify-rpm-amazonlinux-2 verify-rpm-centos-7

# verify DEB packages

verify-deb-artifact-on-deb-10: package-deb
	$(RUN) verify-deb-artifact-on-deb-10

verify-deb: verify-deb-artifact-on-deb-10

# verify all artifacts

verify: verify-rpm verify-deb

# display dependencies between all targets in this Makefile
target-graph:
	@docker-compose -f docker-compose.test.yml run --rm target-graph $(TARGET)

# misc

# clean everything
clean:
	$(RUN) clean

# create target directory with correct permissions
init-target-dir:
	$(RUN) init-target-dir
