RUN=./scripts/docker-compose-run.sh

# default target

all: verify

# build artifacts

build-archive:
	# these dirs are created explictly to ensure that they have the current user as the owner
	mkdir -p target/cargo/git target/cargo/registry
	$(RUN) build-archive

package-deb: build-archive
	$(RUN) package-deb

package-rpm: build-archive
	$(RUN) package-rpm

# verify RPM packages

verify-rpm-amazonlinux-1: package-rpm
	$(RUN) verify-rpm-amazonlinux-1

verify-rpm-amazonlinux-2: package-rpm
	$(RUN) verify-rpm-amazonlinux-2

verify-rpm-centos-7: package-rpm
	$(RUN) verify-rpm-centos-7

verify-rpm: verify-rpm-amazonlinux-1 verify-rpm-amazonlinux-2 verify-rpm-centos-7

# verify DEB packages

verify-deb-artifact-on-deb-10: package-deb
	$(RUN) verify-deb-artifact-on-deb-10

verify-deb: verify-deb-artifact-on-deb-10

# verify all artifacts

verify: verify-rpm verify-deb

# display dependencies between all targets in this Makefile
target-graph:
	@docker-compose -f docker-compose.test.yml run --rm target-graph $(TARGET)

# clean everything
clean:
	$(RUN) clean
