#!/bin/sh
set -e

# Add Vector to adm group to read /var/logs
usermod --append --groups adm vector || true

# Add Vector to systemd-journal to read journald logs
usermod --append --groups systemd-journal vector || true

# Reload the daemon to reflect new group membership
if command -v systemctl >/dev/null 2>&1
then
  systemctl daemon-reload
fi
