use std::{collections::HashMap, net::SocketAddr};

use vector_lib::{codecs::JsonSerializerConfig, configurable::configurable_component};

use super::{buffering::MessageBufferingConfig, sink::WebSocketListenerSink};
use crate::{
    codecs::{EncodingConfig, Transformer},
    common::http::server_auth::HttpServerAuthConfig,
    config::{AcknowledgementsConfig, Input, SinkConfig, SinkContext, ValidatedSink},
    sinks::{Healthcheck, VectorSink},
    tls::{MaybeTlsSettings, TlsEnableableConfig},
};

/// Configuration for the `websocket_server` sink.
#[configurable_component(sink(
    "websocket_server",
    "Deliver observability event data to websocket clients."
))]
#[derive(Clone, Debug)]
pub struct WebSocketListenerSinkConfig {
    /// The socket address to listen for connections on.
    ///
    /// This value _must_ include a port.
    #[configurable(metadata(docs::examples = "0.0.0.0:80"))]
    #[configurable(metadata(docs::examples = "localhost:80"))]
    pub address: SocketAddr,

    pub tls: Option<TlsEnableableConfig>,

    pub encoding: EncodingConfig,

    #[serde(default)]
    pub subprotocol: SubProtocolConfig,

    #[serde(
        default,
        deserialize_with = "crate::serde::bool_or_struct",
        skip_serializing_if = "crate::serde::is_default"
    )]
    pub acknowledgements: AcknowledgementsConfig,

    pub message_buffering: Option<MessageBufferingConfig>,

    pub auth: Option<HttpServerAuthConfig>,

    /// Configuration of internal metrics
    #[serde(default)]
    pub internal_metrics: InternalMetricsConfig,
}

/// Configuration of internal metrics for websocket server.
#[configurable_component]
#[derive(Clone, Debug, PartialEq, Eq, Default)]
#[serde(deny_unknown_fields)]
pub struct InternalMetricsConfig {
    /// Extra tags to add to all metrics generated by this component
    #[serde(default, skip_serializing_if = "crate::serde::is_default")]
    #[configurable(metadata(
        docs::additional_props_description = "Maps extra tag keys to values."
    ))]
    pub extra_tags: HashMap<String, ExtraMetricTagsConfig>,
}

/// Configuration of extra metrics tags
#[configurable_component]
#[derive(Clone, Debug, PartialEq, Eq)]
#[serde(deny_unknown_fields, rename_all = "snake_case", tag = "type")]
#[configurable(metadata(docs::enum_tag_description = "Enum for extra metric tag values."))]
pub enum ExtraMetricTagsConfig {
    /// Hard-coded extra metric tag for all clients
    Fixed {
        /// Tag value
        value: String,
    },
    /// Extra metric tag that takes on the value of a header
    Header {
        /// Name of the header to use as value
        name: String,
    },
    /// Extra metric tag that takes on the value of a query parameter
    Query {
        /// Name of the query parameter to use as value
        name: String,
    },
    /// Extra metric tag that takes full request URL as value
    Url,
    /// Extra metric tag that uses client ip address as value
    IpAddress {
        /// Set to true if port should be included with the ip address.
        ///
        /// By default port is not included
        #[serde(default = "crate::serde::default_false")]
        with_port: bool,
    },
}

/// Configuration of websocket subprotocol handling.
#[configurable_component]
#[derive(Clone, Debug, PartialEq, Eq)]
#[serde(deny_unknown_fields, rename_all = "snake_case", tag = "type")]
#[configurable(metadata(docs::enum_tag_description = "Enum for websocket subprotocol handling."))]
pub enum SubProtocolConfig {
    /// Supports any subprotocol that the client sends. First of the requested subprotocols will be accepted.
    Any,
    /// Supports only listed subprotocols. If client doesn't send any of these, server will skip
    /// `Sec-WebSocket-Protocol` header and the client can choose to close the connection then.
    Specific {
        /// List of supported `Sec-WebSocket-Protocol` values. First match out of requested
        /// subprotocols will be accepted.
        supported_subprotocols: Vec<String>,
    },
}

impl Default for SubProtocolConfig {
    fn default() -> Self {
        Self::Specific {
            supported_subprotocols: Vec::default(),
        }
    }
}

impl Default for WebSocketListenerSinkConfig {
    fn default() -> Self {
        Self {
            address: "0.0.0.0:8080".parse().unwrap(),
            encoding: JsonSerializerConfig::default().into(),
            tls: None,
            acknowledgements: Default::default(),
            message_buffering: None,
            subprotocol: Default::default(),
            auth: None,
            internal_metrics: InternalMetricsConfig::default(),
        }
    }
}

#[async_trait::async_trait]
#[typetag::serde(name = "websocket_server")]
impl SinkConfig for WebSocketListenerSinkConfig {
    fn input(&self) -> Input {
        Input::new(self.encoding.config().input_type())
    }

    fn acknowledgements(&self) -> &AcknowledgementsConfig {
        &self.acknowledgements
    }
}

#[derive(Clone, Debug)]
pub struct ValidatedWebSocketListenerSink {
    pub(super) transformer: Transformer,
}

#[async_trait::async_trait]
impl ValidatedSink for WebSocketListenerSinkConfig {
    type Validated = ValidatedWebSocketListenerSink;

    fn validate(&self) -> crate::Result<ValidatedWebSocketListenerSink> {
        let transformer = self.encoding.transformer();
        // Custom-auth VRL compilation is deferred to `validate_with_context`, which
        // has the enrichment tables needed to resolve `get_enrichment_table_record!`.
        Ok(ValidatedWebSocketListenerSink { transformer })
    }

    fn validate_with_context(&self, cx: &SinkContext) -> crate::Result<()> {
        if let Some(auth) = &self.auth {
            auth.validate(&cx.enrichment_tables)?;
        }
        Ok(())
    }

    async fn build(
        &self,
        validated: &ValidatedWebSocketListenerSink,
        cx: SinkContext,
    ) -> crate::Result<(VectorSink, Healthcheck)> {
        // TLS settings may read certificate files from disk, so they are
        // resolved at build time rather than during pure validation.
        let tls = MaybeTlsSettings::from_config(self.tls.as_ref(), true)?;
        let ws_sink = WebSocketListenerSink::from_validated(self.clone(), validated, tls, cx)?;

        Ok((
            VectorSink::from_event_streamsink(ws_sink),
            Box::pin(async move { Ok(()) }),
        ))
    }
}

impl_generate_config_from_default!(WebSocketListenerSinkConfig);

#[cfg(test)]
mod test {
    use super::*;
    use indoc::indoc;
    use vector_lib::codecs::encoding::SerializerConfig;

    use crate::config::ValidatedSink;

    fn sink_context_with_allowed_users() -> SinkContext {
        let cx = SinkContext::default();
        let mut stubs: HashMap<String, Box<dyn vector_lib::enrichment::Table + Send + Sync>> =
            HashMap::new();
        stubs.insert(
            "allowed_users".to_string(),
            Box::new(crate::validate::StubEnrichmentTable)
                as Box<dyn vector_lib::enrichment::Table + Send + Sync>,
        );
        cx.enrichment_tables.load(stubs);
        cx
    }

    #[test]
    fn generate_config() {
        crate::test_util::test_generate_config::<WebSocketListenerSinkConfig>();
    }

    #[test]
    fn validate_produces_usable_state() {
        let config = WebSocketListenerSinkConfig {
            address: "0.0.0.0:8080".parse().unwrap(),
            ..Default::default()
        };
        let _validated = config.validate().expect("validation should succeed");
        // Serializer construction is deferred to `build`; validation retains the
        // transformer so `build` can construct the serializer.
        assert!(matches!(
            config.encoding.config(),
            SerializerConfig::Json(_)
        ));
    }

    #[test]
    fn validate_fails_on_invalid_custom_auth_source() {
        let config = WebSocketListenerSinkConfig {
            address: "0.0.0.0:8080".parse().unwrap(),
            auth: Some(HttpServerAuthConfig::Custom {
                source: "\"unterminated".to_string(),
            }),
            ..Default::default()
        };
        assert!(
            config
                .validate_with_context(&SinkContext::default())
                .is_err(),
            "an invalid custom auth VRL source must fail validation"
        );
    }

    #[test]
    fn validate_succeeds_on_valid_custom_auth_source() {
        let config = WebSocketListenerSinkConfig {
            address: "0.0.0.0:8080".parse().unwrap(),
            auth: Some(HttpServerAuthConfig::Custom {
                source: indoc! {r#"
                    .headers.authorization == "Basic test"
                    "#}
                .to_string(),
            }),
            ..Default::default()
        };
        assert!(
            config
                .validate_with_context(&SinkContext::default())
                .is_ok(),
            "a valid custom auth VRL source must pass validation"
        );
    }

    #[test]
    fn validate_succeeds_on_custom_auth_with_enrichment() {
        // Custom-auth VRL is compiled against the configured enrichment tables
        // (stubbed during validation); a program referencing a configured table
        // must pass without loading actual data.
        let config = WebSocketListenerSinkConfig {
            address: "0.0.0.0:8080".parse().unwrap(),
            auth: Some(HttpServerAuthConfig::Custom {
                source: indoc! {r#"
                    get_enrichment_table_record!("allowed_users", { "user": .headers.authorization }) != null
                    "#}
                .to_string(),
            }),
            ..Default::default()
        };
        assert!(
            config
                .validate_with_context(&sink_context_with_allowed_users())
                .is_ok(),
            "custom auth using enrichment tables must pass validation"
        );
    }
}
