use strum::{AsRefStr, Display, EnumIter};

/// Canonical list of all per-component internal metric names emitted by Vector.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Display, AsRefStr, EnumIter)]
#[strum(serialize_all = "snake_case")]
pub enum MetricName {
    ComponentReceivedEventsTotal,
    ComponentReceivedEventBytesTotal,
    ComponentReceivedEventsCount,
    ComponentReceivedBytesTotal,
    ComponentSentEventsTotal,
    ComponentSentEventBytesTotal,
    ComponentSentBytesTotal,
    ComponentDiscardedEventsTotal,
    ComponentErrorsTotal,
    ComponentTimedOutEventsTotal,
    ComponentTimedOutRequestsTotal,
    BufferMaxSizeEvents,
    BufferMaxEventSize,
    BufferMaxSizeBytes,
    BufferMaxByteSize,
    BufferReceivedEventsTotal,
    BufferReceivedBytesTotal,
    BufferSentEventsTotal,
    BufferSentBytesTotal,
    BufferDiscardedEventsTotal,
    BufferDiscardedBytesTotal,
    BufferErrorsTotal,
    BufferSendDurationSeconds,
    BufferEvents,
    BufferSizeEvents,
    BufferSizeBytes,
    BufferByteSize,
    ComponentLatencySeconds,
    ComponentLatencyMeanSeconds,
    SourceLagTimeSeconds,
    SourceSendLatencySeconds,
    SourceSendBatchLatencySeconds,
    // Internal events from src/internal_events/
    ActiveClients,
    ActiveEndpoints,
    AdaptiveConcurrencyAveragedRtt,
    AdaptiveConcurrencyBackPressure,
    AdaptiveConcurrencyInFlight,
    AdaptiveConcurrencyLimit,
    AdaptiveConcurrencyObservedRtt,
    AdaptiveConcurrencyPastRttMean,
    AdaptiveConcurrencyReachedLimit,
    AggregateEventsRecordedTotal,
    AggregateFailedUpdates,
    AggregateFlushesTotal,
    ApiStartedTotal,
    BuildInfo,
    CheckpointsTotal,
    ChecksumErrorsTotal,
    CollectCompletedTotal,
    CollectDurationSeconds,
    CommandExecutedTotal,
    CommandExecutionDurationSeconds,
    ComponentReceivedBytes,
    ConnectionEstablishedTotal,
    ConnectionSendErrorsTotal,
    ConnectionShutdownTotal,
    ContainerProcessedEventsTotal,
    ContainersUnwatchedTotal,
    ContainersWatchedTotal,
    DecoderBomRemovalsTotal,
    DecoderMalformedReplacementWarningsTotal,
    DorisBytesLoadedTotal,
    DorisRowsFilteredTotal,
    DorisRowsLoadedTotal,
    EncoderUnmappableReplacementWarningsTotal,
    EventsDiscardedTotal,
    FilesAddedTotal,
    FilesDeletedTotal,
    FilesResumedTotal,
    FilesUnwatchedTotal,
    GrpcServerHandlerDurationSeconds,
    GrpcServerMessagesReceivedTotal,
    GrpcServerMessagesSentTotal,
    HttpClientErrorRttSeconds,
    HttpClientErrorsTotal,
    HttpClientRequestsSentTotal,
    HttpClientResponseRttSeconds,
    HttpClientResponsesTotal,
    HttpClientRttSeconds,
    HttpServerHandlerDurationSeconds,
    HttpServerRequestsReceivedTotal,
    HttpServerResponsesSentTotal,
    KafkaConsumedMessagesBytesTotal,
    KafkaConsumedMessagesTotal,
    KafkaConsumerLag,
    KafkaProducedMessagesBytesTotal,
    KafkaProducedMessagesTotal,
    KafkaQueueMessages,
    KafkaQueueMessagesBytes,
    KafkaRequestsBytesTotal,
    KafkaRequestsTotal,
    KafkaResponsesBytesTotal,
    KafkaResponsesTotal,
    LuaMemoryUsedBytes,
    MetadataRefreshFailedTotal,
    MetadataRefreshSuccessfulTotal,
    OpenConnections,
    OpenFiles,
    ParseErrorsTotal,
    QuitTotal,
    ReloadedTotal,
    RewrittenTimestampEventsTotal,
    SplunkPendingAcks,
    SqsMessageDeferSucceededTotal,
    SqsMessageDeleteSucceededTotal,
    SqsMessageProcessingSucceededTotal,
    SqsMessageReceiveSucceededTotal,
    SqsMessageReceivedMessagesTotal,
    StaleEventsFlushedTotal,
    StartedTotal,
    StoppedTotal,
    TagValueLimitExceededTotal,
    UptimeSeconds,
    ValueLimitReachedTotal,
    WebsocketBytesSentTotal,
    WebsocketMessagesSentTotal,
    WindowsServiceInstallTotal,
    WindowsServiceRestartTotal,
    WindowsServiceStartTotal,
    WindowsServiceStopTotal,
    WindowsServiceUninstallTotal,
    K8sEventNamespaceAnnotationFailuresTotal,
    K8sEventNodeAnnotationFailuresTotal,
    K8sFormatPickerEdgeCasesTotal,
    K8sDockerFormatParseFailuresTotal,
    S3ObjectProcessingSucceededDurationSeconds,
    S3ObjectProcessingFailedDurationSeconds,
    SqsS3EventRecordIgnoredTotal,
}

impl MetricName {
    #[allow(clippy::too_many_lines)]
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::ComponentReceivedEventsTotal => "component_received_events_total",
            Self::ComponentReceivedEventBytesTotal => "component_received_event_bytes_total",
            Self::ComponentReceivedEventsCount => "component_received_events_count",
            Self::ComponentReceivedBytesTotal => "component_received_bytes_total",
            Self::ComponentSentEventsTotal => "component_sent_events_total",
            Self::ComponentSentEventBytesTotal => "component_sent_event_bytes_total",
            Self::ComponentSentBytesTotal => "component_sent_bytes_total",
            Self::ComponentDiscardedEventsTotal => "component_discarded_events_total",
            Self::ComponentErrorsTotal => "component_errors_total",
            Self::ComponentTimedOutEventsTotal => "component_timed_out_events_total",
            Self::ComponentTimedOutRequestsTotal => "component_timed_out_requests_total",
            Self::BufferMaxSizeEvents => "buffer_max_size_events",
            Self::BufferMaxEventSize => "buffer_max_event_size",
            Self::BufferMaxSizeBytes => "buffer_max_size_bytes",
            Self::BufferMaxByteSize => "buffer_max_byte_size",
            Self::BufferReceivedEventsTotal => "buffer_received_events_total",
            Self::BufferReceivedBytesTotal => "buffer_received_bytes_total",
            Self::BufferSentEventsTotal => "buffer_sent_events_total",
            Self::BufferSentBytesTotal => "buffer_sent_bytes_total",
            Self::BufferDiscardedEventsTotal => "buffer_discarded_events_total",
            Self::BufferDiscardedBytesTotal => "buffer_discarded_bytes_total",
            Self::BufferErrorsTotal => "buffer_errors_total",
            Self::BufferSendDurationSeconds => "buffer_send_duration_seconds",
            Self::BufferEvents => "buffer_events",
            Self::BufferSizeEvents => "buffer_size_events",
            Self::BufferSizeBytes => "buffer_size_bytes",
            Self::BufferByteSize => "buffer_byte_size",
            Self::ComponentLatencySeconds => "component_latency_seconds",
            Self::ComponentLatencyMeanSeconds => "component_latency_mean_seconds",
            Self::SourceLagTimeSeconds => "source_lag_time_seconds",
            Self::SourceSendLatencySeconds => "source_send_latency_seconds",
            Self::SourceSendBatchLatencySeconds => "source_send_batch_latency_seconds",
            Self::ActiveClients => "active_clients",
            Self::ActiveEndpoints => "active_endpoints",
            Self::AdaptiveConcurrencyAveragedRtt => "adaptive_concurrency_averaged_rtt",
            Self::AdaptiveConcurrencyBackPressure => "adaptive_concurrency_back_pressure",
            Self::AdaptiveConcurrencyInFlight => "adaptive_concurrency_in_flight",
            Self::AdaptiveConcurrencyLimit => "adaptive_concurrency_limit",
            Self::AdaptiveConcurrencyObservedRtt => "adaptive_concurrency_observed_rtt",
            Self::AdaptiveConcurrencyPastRttMean => "adaptive_concurrency_past_rtt_mean",
            Self::AdaptiveConcurrencyReachedLimit => "adaptive_concurrency_reached_limit",
            Self::AggregateEventsRecordedTotal => "aggregate_events_recorded_total",
            Self::AggregateFailedUpdates => "aggregate_failed_updates",
            Self::AggregateFlushesTotal => "aggregate_flushes_total",
            Self::ApiStartedTotal => "api_started_total",
            Self::BuildInfo => "build_info",
            Self::CheckpointsTotal => "checkpoints_total",
            Self::ChecksumErrorsTotal => "checksum_errors_total",
            Self::CollectCompletedTotal => "collect_completed_total",
            Self::CollectDurationSeconds => "collect_duration_seconds",
            Self::CommandExecutedTotal => "command_executed_total",
            Self::CommandExecutionDurationSeconds => "command_execution_duration_seconds",
            Self::ComponentReceivedBytes => "component_received_bytes",
            Self::ConnectionEstablishedTotal => "connection_established_total",
            Self::ConnectionSendErrorsTotal => "connection_send_errors_total",
            Self::ConnectionShutdownTotal => "connection_shutdown_total",
            Self::ContainerProcessedEventsTotal => "container_processed_events_total",
            Self::ContainersUnwatchedTotal => "containers_unwatched_total",
            Self::ContainersWatchedTotal => "containers_watched_total",
            Self::DecoderBomRemovalsTotal => "decoder_bom_removals_total",
            Self::DecoderMalformedReplacementWarningsTotal => {
                "decoder_malformed_replacement_warnings_total"
            }
            Self::DorisBytesLoadedTotal => "doris_bytes_loaded_total",
            Self::DorisRowsFilteredTotal => "doris_rows_filtered_total",
            Self::DorisRowsLoadedTotal => "doris_rows_loaded_total",
            Self::EncoderUnmappableReplacementWarningsTotal => {
                "encoder_unmappable_replacement_warnings_total"
            }
            Self::EventsDiscardedTotal => "events_discarded_total",
            Self::FilesAddedTotal => "files_added_total",
            Self::FilesDeletedTotal => "files_deleted_total",
            Self::FilesResumedTotal => "files_resumed_total",
            Self::FilesUnwatchedTotal => "files_unwatched_total",
            Self::GrpcServerHandlerDurationSeconds => "grpc_server_handler_duration_seconds",
            Self::GrpcServerMessagesReceivedTotal => "grpc_server_messages_received_total",
            Self::GrpcServerMessagesSentTotal => "grpc_server_messages_sent_total",
            Self::HttpClientErrorRttSeconds => "http_client_error_rtt_seconds",
            Self::HttpClientErrorsTotal => "http_client_errors_total",
            Self::HttpClientRequestsSentTotal => "http_client_requests_sent_total",
            Self::HttpClientResponseRttSeconds => "http_client_response_rtt_seconds",
            Self::HttpClientResponsesTotal => "http_client_responses_total",
            Self::HttpClientRttSeconds => "http_client_rtt_seconds",
            Self::HttpServerHandlerDurationSeconds => "http_server_handler_duration_seconds",
            Self::HttpServerRequestsReceivedTotal => "http_server_requests_received_total",
            Self::HttpServerResponsesSentTotal => "http_server_responses_sent_total",
            Self::KafkaConsumedMessagesBytesTotal => "kafka_consumed_messages_bytes_total",
            Self::KafkaConsumedMessagesTotal => "kafka_consumed_messages_total",
            Self::KafkaConsumerLag => "kafka_consumer_lag",
            Self::KafkaProducedMessagesBytesTotal => "kafka_produced_messages_bytes_total",
            Self::KafkaProducedMessagesTotal => "kafka_produced_messages_total",
            Self::KafkaQueueMessages => "kafka_queue_messages",
            Self::KafkaQueueMessagesBytes => "kafka_queue_messages_bytes",
            Self::KafkaRequestsBytesTotal => "kafka_requests_bytes_total",
            Self::KafkaRequestsTotal => "kafka_requests_total",
            Self::KafkaResponsesBytesTotal => "kafka_responses_bytes_total",
            Self::KafkaResponsesTotal => "kafka_responses_total",
            Self::LuaMemoryUsedBytes => "lua_memory_used_bytes",
            Self::MetadataRefreshFailedTotal => "metadata_refresh_failed_total",
            Self::MetadataRefreshSuccessfulTotal => "metadata_refresh_successful_total",
            Self::OpenConnections => "open_connections",
            Self::OpenFiles => "open_files",
            Self::ParseErrorsTotal => "parse_errors_total",
            Self::QuitTotal => "quit_total",
            Self::ReloadedTotal => "reloaded_total",
            Self::RewrittenTimestampEventsTotal => "rewritten_timestamp_events_total",
            Self::SplunkPendingAcks => "splunk_pending_acks",
            Self::SqsMessageDeferSucceededTotal => "sqs_message_defer_succeeded_total",
            Self::SqsMessageDeleteSucceededTotal => "sqs_message_delete_succeeded_total",
            Self::SqsMessageProcessingSucceededTotal => "sqs_message_processing_succeeded_total",
            Self::SqsMessageReceiveSucceededTotal => "sqs_message_receive_succeeded_total",
            Self::SqsMessageReceivedMessagesTotal => "sqs_message_received_messages_total",
            Self::StaleEventsFlushedTotal => "stale_events_flushed_total",
            Self::StartedTotal => "started_total",
            Self::StoppedTotal => "stopped_total",
            Self::TagValueLimitExceededTotal => "tag_value_limit_exceeded_total",
            Self::UptimeSeconds => "uptime_seconds",
            Self::ValueLimitReachedTotal => "value_limit_reached_total",
            Self::WebsocketBytesSentTotal => "websocket_bytes_sent_total",
            Self::WebsocketMessagesSentTotal => "websocket_messages_sent_total",
            Self::WindowsServiceInstallTotal => "windows_service_install_total",
            Self::WindowsServiceRestartTotal => "windows_service_restart_total",
            Self::WindowsServiceStartTotal => "windows_service_start_total",
            Self::WindowsServiceStopTotal => "windows_service_stop_total",
            Self::WindowsServiceUninstallTotal => "windows_service_uninstall_total",
            Self::K8sEventNamespaceAnnotationFailuresTotal => "k8s_event_namespace_annotation_failures_total",
            Self::K8sEventNodeAnnotationFailuresTotal => "k8s_event_node_annotation_failures_total",
            Self::K8sFormatPickerEdgeCasesTotal => "k8s_format_picker_edge_cases_total",
            Self::K8sDockerFormatParseFailuresTotal => "k8s_docker_format_parse_failures_total",
            Self::S3ObjectProcessingSucceededDurationSeconds => "s3_object_processing_succeeded_duration_seconds",
            Self::S3ObjectProcessingFailedDurationSeconds => "s3_object_processing_failed_duration_seconds",
            Self::SqsS3EventRecordIgnoredTotal => "sqs_s3_event_record_ignored_total",
        }
    }
}
