use std::num::NonZeroU64;

use http::Uri;
use snafu::ResultExt;
use tower::ServiceBuilder;
use vector_lib::{
    config::proxy::ProxyConfig, configurable::configurable_component, stream::BatcherSettings,
};

use super::{
    request_builder::{DatadogMetricsRequestBuilder, ShadowBuilderConfig},
    service::{DatadogMetricsRetryLogic, DatadogMetricsService},
    sink::DatadogMetricsSink,
};
use crate::{
    common::datadog,
    config::{AcknowledgementsConfig, Input, SinkConfig, SinkContext},
    http::HttpClient,
    sinks::{
        Healthcheck, UriParseSnafu, VectorSink,
        datadog::{DatadogCommonConfig, LocalDatadogCommonConfig},
        util::{ServiceBuilderExt, SinkBatchSettings, TowerRequestConfig, batch::BatchConfig},
    },
    tls::{MaybeTlsSettings, TlsEnableableConfig},
};
#[derive(Clone, Copy, Debug, Default)]
pub struct DatadogMetricsDefaultBatchSettings;

impl SinkBatchSettings for DatadogMetricsDefaultBatchSettings {
    const MAX_EVENTS: Option<usize> = Some(100_000);
    // No default byte cap here; the appropriate limit (v1: 60 MiB, v2: 5 MiB) is applied at
    // sink build time based on the active series API version.
    const MAX_BYTES: Option<usize> = None;
    const TIMEOUT_SECS: f64 = 2.0;
}

pub(super) const SERIES_V1_PATH: &str = "/api/v1/series";
pub(super) const SERIES_V2_PATH: &str = "/api/v2/series";
pub(super) const SERIES_V3_PATH: &str = "/api/intake/metrics/v3/series";
/// Beta intake endpoint used during V3 shadow rollout.
pub(super) const SERIES_V3_BETA_PATH: &str = "/api/intake/metrics/v3beta/series";
pub(super) const SKETCHES_PATH: &str = "/api/beta/sketches";
pub(super) const SKETCHES_V3_PATH: &str = "/api/intake/metrics/v3/sketches";

/// The API version to use when submitting series metrics to Datadog.
///
/// `V3Beta` is deliberately kept in this enum (and fully wired through the encoder and
/// request builder) but marked `#[serde(skip)]` below, so it cannot be configured as the
/// *primary* `series_api_version`. It's a validation-only route used exclusively for the V3
/// shadow dual-write: `batch_id` and the `X-Metrics-Request-*` correlation headers that pair a
/// shadow request with its legacy V1/V2 twin are only generated by the dual-write path, so a
/// primary request sent as `V3Beta` would be unpaired and uncorrelated -- the shadow backend
/// has nothing to validate it against, and it doesn't provide normal metric ingestion either.
/// Use `v3` for stable primary V3 series submission, or enable `dual_write` to get `V3Beta`
/// shadow traffic alongside a legacy primary.
#[configurable_component]
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
#[serde(rename_all = "snake_case")]
pub enum SeriesApiVersion {
    /// Use the v1 series endpoint (`/api/v1/series`).
    ///
    /// This is a legacy endpoint. Prefer `v2` unless you have a specific reason to use v1.
    #[configurable(deprecated)]
    V1,

    /// Use the v2 series endpoint (`/api/v2/series`).
    ///
    /// This is the recommended and default endpoint.
    #[default]
    V2,

    /// Use the v3 series endpoint (`/api/intake/metrics/v3/series`).
    ///
    /// Columnar protobuf format with dictionary-based string deduplication and delta
    /// encoding. More efficient than v2 for workloads with many metrics that share
    /// common tags or names.
    V3,

    /// Use the v3 beta intake endpoint (`/api/intake/metrics/v3beta/series`).
    ///
    /// This is a validation-only route used internally by V3 shadow dual-write (see
    /// `dual_write`) and can't be selected as the primary `series_api_version` -- see this
    /// enum's doc comment for why. The variant, `get_path()`, `is_v3_format()`, and the shadow
    /// encoder path are all still fully implemented; only the primary config surface is
    /// disabled.
    #[serde(skip)]
    V3Beta,
}

impl SeriesApiVersion {
    pub const fn get_path(self) -> &'static str {
        match self {
            Self::V1 => SERIES_V1_PATH,
            Self::V2 => SERIES_V2_PATH,
            Self::V3 => SERIES_V3_PATH,
            Self::V3Beta => SERIES_V3_BETA_PATH,
        }
    }

    /// Returns true if this version uses the V3 columnar encoding format.
    pub const fn is_v3_format(self) -> bool {
        matches!(self, Self::V3 | Self::V3Beta)
    }
}

/// The API version to use when submitting sketch metrics (distributions, histograms) to Datadog.
///
/// Independent of `series_api_version`: Datadog's intake gates V3 series and V3 sketches
/// separately, so enabling one does not enable the other.
///
/// `V3` is deliberately kept in this enum (and fully wired through the encoder and request
/// builder) but marked `#[serde(skip)]` below, so it cannot currently be configured. Datadog's
/// V3 sketches intake routes don't exist yet: both `/api/intake/metrics/v3/sketches` and
/// `/api/intake/metrics/v3beta/sketches` return 404, and a 404 maps to a *retriable*
/// `ClientError`, so sketches sent this way retry forever without ever delivering. Remove the
/// `#[serde(skip)]` once the intake side supports it.
#[configurable_component]
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
#[serde(rename_all = "snake_case")]
pub enum SketchesApiVersion {
    /// Use the legacy sketches endpoint (`/api/beta/sketches`).
    ///
    /// This is the recommended and default endpoint.
    #[default]
    V2,

    /// Use the v3 sketches endpoint (`/api/intake/metrics/v3/sketches`).
    ///
    /// Columnar protobuf format, matching the encoding used for V3 series. Must be enabled
    /// separately from `series_api_version`.
    ///
    /// Not currently configurable — see the `#[serde(skip)]` note on this enum's doc comment.
    /// The variant, `get_path()`, `is_v3_format()`, and the request builder's V3 sketches
    /// encoder path are all still fully implemented; only the config surface is disabled.
    #[serde(skip)]
    V3,
}

impl SketchesApiVersion {
    pub const fn get_path(self) -> &'static str {
        match self {
            Self::V2 => SKETCHES_PATH,
            Self::V3 => SKETCHES_V3_PATH,
        }
    }

    /// Returns true if this version uses the V3 columnar encoding format.
    pub const fn is_v3_format(self) -> bool {
        matches!(self, Self::V3)
    }
}

/// Various metric type-specific API types.
///
/// Each of these corresponds to a specific request path when making a request to the agent API.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum DatadogMetricsEndpoint {
    Series(SeriesApiVersion),
    Sketches,
}

/// Payload limits for metrics are endpoint-dependent.
pub(super) struct DatadogMetricsPayloadLimits {
    pub(super) uncompressed: usize,
    pub(super) compressed: usize,
}

impl DatadogMetricsEndpoint {
    /// Gets the content type associated with the specific encoder for a given metric endpoint.
    pub const fn content_type(self) -> &'static str {
        match self {
            Self::Series(SeriesApiVersion::V1) => "application/json",
            _ => "application/x-protobuf",
        }
    }

    pub(super) const fn payload_limits(self) -> DatadogMetricsPayloadLimits {
        // from https://docs.datadoghq.com/api/latest/metrics/#submit-metrics
        let (uncompressed, compressed) = match self {
            // Sketches use the same payload size limits as v1 series
            DatadogMetricsEndpoint::Series(SeriesApiVersion::V1)
            | DatadogMetricsEndpoint::Sketches => (
                62_914_560, // 60 MiB
                3_200_000,  // 3.2 MB
            ),
            DatadogMetricsEndpoint::Series(SeriesApiVersion::V2) => (
                5_242_880, // 5 MiB
                512_000,   // 512 KB
            ),
            // V3/V3Beta all use the same limits as V2 series.
            DatadogMetricsEndpoint::Series(SeriesApiVersion::V3 | SeriesApiVersion::V3Beta) => (
                5_242_880, // 5 MiB
                512_000,   // 512 KB
            ),
        };

        DatadogMetricsPayloadLimits {
            uncompressed,
            compressed,
        }
    }

    /// Returns the compression scheme used for this endpoint.
    pub(super) const fn compression(self) -> DatadogMetricsCompression {
        match self {
            Self::Series(SeriesApiVersion::V1) => DatadogMetricsCompression::Zlib,
            _ => DatadogMetricsCompression::Zstd,
        }
    }
}

/// Selects the compressor for a given Datadog metrics endpoint.
#[derive(Clone, Copy, Debug)]
pub(super) enum DatadogMetricsCompression {
    /// zlib (deflate) — used by Series v1.
    Zlib,
    /// zstd — used by Series v2 and Sketches.
    Zstd,
}

impl DatadogMetricsCompression {
    pub(super) const fn content_encoding(self) -> &'static str {
        match self {
            Self::Zstd => "zstd",
            Self::Zlib => "deflate",
        }
    }
}

/// Maps Datadog metric endpoints to their actual URI.
pub struct DatadogMetricsEndpointConfiguration {
    series_endpoint: Uri,
    sketches_endpoint: Uri,
}

impl DatadogMetricsEndpointConfiguration {
    /// Creates a new `DatadogMEtricsEndpointConfiguration`.
    pub const fn new(series_endpoint: Uri, sketches_endpoint: Uri) -> Self {
        Self {
            series_endpoint,
            sketches_endpoint,
        }
    }

    /// Gets the URI for the given Datadog metrics endpoint.
    pub fn get_uri_for_endpoint(&self, endpoint: DatadogMetricsEndpoint) -> Uri {
        match endpoint {
            DatadogMetricsEndpoint::Series { .. } => self.series_endpoint.clone(),
            DatadogMetricsEndpoint::Sketches => self.sketches_endpoint.clone(),
        }
    }
}

const fn default_shadow_every() -> NonZeroU64 {
    NonZeroU64::new(1000).unwrap()
}

/// Configuration for the V3 shadow dual-write mode.
///
/// When enabled, every `shadow_every`-th legacy (V1/V2) *series* flush also sends a V3
/// shadow payload to the shadow series endpoint. Both payloads in a pair carry the same
/// `X-Metrics-Request-ID` header so the intake backend can correlate them.
///
/// Sketches are never dual-written. The V3 sketches intake routes do not exist — both
/// `/api/intake/metrics/v3/sketches` and `/api/intake/metrics/v3beta/sketches` return 404,
/// and a 404 maps to a *retriable* `ClientError`, so shadowing sketches produced an
/// endless retry loop that never delivered anything.
#[configurable_component]
#[derive(Clone, Debug)]
pub struct DualWriteConfig {
    /// Whether to enable V3 shadow dual-write.
    ///
    /// When unset, this defaults to `true` when submitting directly to Datadog (no custom
    /// `endpoint` set), and to `false` when a custom `endpoint` is configured (for example, a
    /// Datadog Agent, relay, or test collector). The shadow route
    /// (`/api/intake/metrics/v3beta/series`) is only guaranteed to exist on Datadog's own
    /// intake; hitting it on a custom endpoint that doesn't implement it 404s, which is
    /// treated as a retriable error, so every sampled flush would add a request that retries
    /// forever. Set this explicitly to `true` to opt in to shadow traffic against a custom
    /// endpoint anyway, or to `false` to disable it even when submitting directly to Datadog.
    ///
    /// This only ever affects series. Sketches are never dual-written.
    #[serde(default)]
    pub enabled: Option<bool>,

    /// Send a V3 shadow payload once per this many legacy (V1/V2) series flushes.
    ///
    /// Set to `1` to shadow every series flush (full dual-write). Must be greater than zero.
    /// Defaults to `1000`. Sketches flushes are never counted or shadowed.
    #[serde(default = "default_shadow_every")]
    pub shadow_every: NonZeroU64,
}

impl Default for DualWriteConfig {
    fn default() -> Self {
        Self {
            enabled: None,
            shadow_every: default_shadow_every(),
        }
    }
}

impl DualWriteConfig {
    pub(super) const fn get_series_path(&self) -> &'static str {
        SERIES_V3_BETA_PATH
    }

    /// Resolves whether shadow dual-write should actually run for this sink instance.
    ///
    /// An explicit `enabled` setting always wins. When unset, dual-write defaults to `true`
    /// only when submitting directly to Datadog; a custom endpoint (Agent, relay, test
    /// collector, ...) defaults to `false`, since the beta shadow route isn't guaranteed to
    /// exist there and a 404 would otherwise retry forever. See `enabled`'s docs for details.
    pub(super) fn is_enabled(&self, has_custom_endpoint: bool) -> bool {
        self.enabled.unwrap_or(!has_custom_endpoint)
    }
}

/// Configuration for the `datadog_metrics` sink.
#[configurable_component(sink("datadog_metrics", "Publish metric events to Datadog."))]
#[derive(Clone, Debug, Default)]
#[serde(deny_unknown_fields)]
pub struct DatadogMetricsConfig {
    #[serde(flatten)]
    pub local_dd_common: LocalDatadogCommonConfig,

    /// Sets the default namespace for any metrics sent.
    ///
    /// This namespace is only used if a metric has no existing namespace. When a namespace is
    /// present, it is used as a prefix to the metric name, and separated with a period (`.`).
    #[configurable(metadata(docs::examples = "myservice"))]
    #[serde(default)]
    pub default_namespace: Option<String>,

    /// Controls which Datadog series API endpoint is used to submit metrics.
    ///
    /// Defaults to `v2` (`/api/v2/series`). Set to `v1` (`/api/v1/series`) only if you need to
    /// fall back to the legacy endpoint.
    #[serde(default)]
    pub series_api_version: SeriesApiVersion,

    /// Controls which Datadog sketches API endpoint is used to submit distributions and
    /// histograms.
    ///
    /// Only `v2` (`/api/beta/sketches`) can currently be configured. The V3 sketches intake
    /// routes do not exist yet (`/api/intake/metrics/v3/sketches` and its beta counterpart both
    /// 404), so V3 sketches support is temporarily disabled at the configuration level.
    #[serde(default)]
    pub sketches_api_version: SketchesApiVersion,

    #[configurable(derived)]
    #[serde(default)]
    pub batch: BatchConfig<DatadogMetricsDefaultBatchSettings>,

    #[configurable(derived)]
    #[serde(default)]
    pub request: TowerRequestConfig,

    /// V3 shadow dual-write configuration.
    ///
    /// By default, a sampled fraction of legacy series flushes is mirrored as V3 payloads to
    /// a separate intake endpoint, both stamped with a shared `X-Metrics-Request-ID` — but
    /// only when submitting directly to Datadog. If `endpoint` is set to a custom Agent,
    /// relay, or test collector, dual-write defaults to disabled instead, since the shadow
    /// route isn't guaranteed to exist there. Set `dual_write.enabled` explicitly to override
    /// either default in either direction.
    ///
    /// Sketches are never dual-written, regardless of this setting.
    #[configurable(derived)]
    #[serde(default)]
    pub dual_write: DualWriteConfig,
}

impl_generate_config_from_default!(DatadogMetricsConfig);

#[async_trait::async_trait]
#[typetag::serde(name = "datadog_metrics")]
impl SinkConfig for DatadogMetricsConfig {
    async fn build(&self, cx: SinkContext) -> crate::Result<(VectorSink, Healthcheck)> {
        let client = self.build_client(&cx.proxy)?;
        let global = cx.extra_context.get_or_default::<datadog::Options>();
        let dd_common = self.local_dd_common.with_globals(global)?;
        let healthcheck = dd_common.build_healthcheck(client.clone())?;
        let sink = self.build_sink(&dd_common, client)?;

        Ok((sink, healthcheck))
    }

    fn input(&self) -> Input {
        Input::metric()
    }

    fn acknowledgements(&self) -> &AcknowledgementsConfig {
        &self.local_dd_common.acknowledgements
    }
}

impl DatadogMetricsConfig {
    /// Gets the base URI of the Datadog agent API.
    ///
    /// Per the Datadog agent convention, we should include a unique identifier as part of the
    /// domain to indicate that these metrics are being submitted by Vector, including the version,
    /// likely useful for detecting if a specific version of the agent (Vector, in this case) is
    /// doing something wrong, for understanding issues from the API side.
    ///
    /// The `endpoint` configuration field will be used here if it is present.
    fn get_base_agent_endpoint(&self, dd_common: &DatadogCommonConfig) -> String {
        dd_common.endpoint.clone().unwrap_or_else(|| {
            let version = str::replace(crate::built_info::PKG_VERSION, ".", "-");
            format!(
                "https://{}-vector.agent.{}",
                version,
                dd_common.site.as_str()
            )
        })
    }

    /// Generates the `DatadogMetricsEndpointConfiguration`, used for mapping endpoints to their URI.
    fn generate_metrics_endpoint_configuration(
        &self,
        dd_common: &DatadogCommonConfig,
    ) -> crate::Result<DatadogMetricsEndpointConfiguration> {
        let base_uri = self.get_base_agent_endpoint(dd_common);

        let series_endpoint = build_uri(&base_uri, self.series_api_version.get_path())?;
        let sketches_endpoint = build_uri(&base_uri, self.sketches_api_version.get_path())?;

        Ok(DatadogMetricsEndpointConfiguration::new(
            series_endpoint,
            sketches_endpoint,
        ))
    }

    fn build_client(&self, proxy: &ProxyConfig) -> crate::Result<HttpClient> {
        let default_tls_config;

        let tls_settings = MaybeTlsSettings::from_config(
            Some(match self.local_dd_common.tls.as_ref() {
                Some(config) => config,
                None => {
                    default_tls_config = TlsEnableableConfig::enabled();
                    &default_tls_config
                }
            }),
            false,
        )?;
        let client = HttpClient::new(tls_settings, proxy)?;
        Ok(client)
    }

    fn build_sink(
        &self,
        dd_common: &DatadogCommonConfig,
        client: HttpClient,
    ) -> crate::Result<VectorSink> {
        let (batcher_settings, sketches_batcher_settings) =
            resolve_endpoint_batch_settings(self.batch, self.series_api_version)?;

        // TODO: revisit our concurrency and batching defaults
        let request_limits = self.request.into_settings();

        let endpoint_configuration = self.generate_metrics_endpoint_configuration(dd_common)?;
        let service = ServiceBuilder::new()
            .settings(request_limits, DatadogMetricsRetryLogic)
            .service(DatadogMetricsService::new(
                client,
                dd_common.default_api_key.inner(),
            ));

        let shadow_config = self
            .dual_write
            .is_enabled(dd_common.endpoint.is_some())
            .then_some(&self.dual_write)
            .map(|dw| -> crate::Result<ShadowBuilderConfig> {
                let base_uri = self.get_base_agent_endpoint(dd_common);
                let series_shadow_uri = build_uri(&base_uri, dw.get_series_path())?;
                Ok(ShadowBuilderConfig {
                    series_uri: series_shadow_uri,
                    series_api_version: SeriesApiVersion::V3Beta,
                    default_namespace: self.default_namespace.clone(),
                    shadow_every: dw.shadow_every,
                })
            })
            .transpose()?;

        let request_builder = DatadogMetricsRequestBuilder::new(
            endpoint_configuration,
            self.default_namespace.clone(),
            self.series_api_version,
            self.sketches_api_version,
            shadow_config,
        );

        let protocol = self.get_protocol(dd_common);
        let sink = DatadogMetricsSink::new(
            service,
            request_builder,
            batcher_settings,
            sketches_batcher_settings,
            protocol,
            self.series_api_version,
        );

        Ok(VectorSink::from_event_streamsink(sink))
    }

    fn get_protocol(&self, dd_common: &DatadogCommonConfig) -> String {
        self.get_base_agent_endpoint(dd_common)
            .parse::<Uri>()
            .unwrap()
            .scheme_str()
            .unwrap_or("http")
            .to_string()
    }
}

/// Returns `(series_settings, sketches_settings)`.
///
/// When the user has not set an explicit `max_bytes`, each endpoint is capped to its own
/// uncompressed payload limit (5 MiB for Series v2, 60 MiB for Sketches). When an explicit
/// limit is configured, both endpoints share it.
fn resolve_endpoint_batch_settings(
    batch: BatchConfig<DatadogMetricsDefaultBatchSettings>,
    series_version: SeriesApiVersion,
) -> crate::Result<(BatcherSettings, BatcherSettings)> {
    let mut series = batch.into_batcher_settings()?;
    let mut sketches = series;
    if series.size_limit == usize::MAX {
        series.size_limit = DatadogMetricsEndpoint::Series(series_version)
            .payload_limits()
            .uncompressed;
        sketches.size_limit = DatadogMetricsEndpoint::Sketches
            .payload_limits()
            .uncompressed;
    }
    Ok((series, sketches))
}

fn build_uri(host: &str, endpoint: &str) -> crate::Result<Uri> {
    let result = format!("{host}{endpoint}")
        .parse::<Uri>()
        .context(UriParseSnafu)?;
    Ok(result)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_config() {
        crate::test_util::test_generate_config::<DatadogMetricsConfig>();
    }

    // When max_bytes is unset, each endpoint gets its own API payload limit.
    #[test]
    fn default_batch_config_uses_endpoint_specific_size_limits() {
        let (series, sketches) =
            resolve_endpoint_batch_settings(BatchConfig::default(), SeriesApiVersion::V2).unwrap();

        assert_eq!(series.size_limit, 5_242_880); // 5 MiB — Series v2 limit
        assert_eq!(sketches.size_limit, 62_914_560); // 60 MiB — Sketches limit
    }

    #[test]
    fn v1_batch_config_uses_v1_size_limit() {
        let (series, sketches) =
            resolve_endpoint_batch_settings(BatchConfig::default(), SeriesApiVersion::V1).unwrap();

        assert_eq!(series.size_limit, 62_914_560); // 60 MiB — Series v1 limit
        assert_eq!(sketches.size_limit, 62_914_560); // 60 MiB — Sketches limit
    }

    // When the user sets max_bytes, both endpoints share that limit unchanged.
    #[test]
    fn explicit_max_bytes_applies_to_both_endpoints() {
        let mut config = BatchConfig::<DatadogMetricsDefaultBatchSettings>::default();
        config.max_bytes = Some(1_000_000);

        let (series, sketches) =
            resolve_endpoint_batch_settings(config, SeriesApiVersion::V2).unwrap();

        assert_eq!(series.size_limit, 1_000_000);
        assert_eq!(sketches.size_limit, 1_000_000);
    }

    // The internal V3 beta shadow route isn't guaranteed to exist on a custom endpoint
    // (Agent, relay, test collector, ...), so leaving `dual_write.enabled` unset must not
    // silently turn on shadow traffic there: a 404 is retriable, so every sampled flush would
    // add a permanently retrying request against a target that never implements the route.
    // Submitting directly to Datadog (no custom `endpoint`) is unaffected -- shadow dual-write
    // stays enabled by default there, since Datadog's own intake does implement the route.
    #[test]
    fn dual_write_defaults_to_disabled_only_for_custom_endpoints() {
        let unset = DualWriteConfig::default();
        assert!(
            unset.is_enabled(false),
            "unset `enabled` must default to on when submitting directly to Datadog"
        );
        assert!(
            !unset.is_enabled(true),
            "unset `enabled` must default to off for a custom endpoint"
        );
    }

    // An explicit `enabled` setting always overrides the endpoint-based default, in either
    // direction: opting in to shadow traffic against a custom endpoint, or opting out of it
    // even when submitting directly to Datadog.
    #[test]
    fn dual_write_explicit_enabled_overrides_the_endpoint_based_default() {
        let explicit_on = DualWriteConfig {
            enabled: Some(true),
            ..DualWriteConfig::default()
        };
        assert!(
            explicit_on.is_enabled(true),
            "explicit `enabled = true` must opt in even for a custom endpoint"
        );

        let explicit_off = DualWriteConfig {
            enabled: Some(false),
            ..DualWriteConfig::default()
        };
        assert!(
            !explicit_off.is_enabled(false),
            "explicit `enabled = false` must opt out even when submitting directly to Datadog"
        );
    }

    // `dual_write.enabled` must still parse as a plain TOML boolean -- the `Option<bool>`
    // representation is an internal resolution detail, not a schema change users need to know
    // about.
    #[test]
    fn dual_write_enabled_parses_as_a_plain_bool() {
        let config = toml::from_str::<DatadogMetricsConfig>(
            r#"
            default_api_key = "unused"
            [dual_write]
            enabled = true
            "#,
        )
        .expect("`dual_write.enabled = true` must parse");
        assert_eq!(config.dual_write.enabled, Some(true));

        let config = toml::from_str::<DatadogMetricsConfig>(
            r#"
            default_api_key = "unused"
            "#,
        )
        .expect("omitting `dual_write` entirely must still parse");
        assert_eq!(config.dual_write.enabled, None);
    }

    // `sketches_api_version` is independent of `series_api_version`: Datadog's intake gates V3
    // series and V3 sketches separately, so each must resolve to its own path regardless of what
    // the other is set to.
    #[test]
    fn sketches_path_is_independent_of_series_api_version() {
        assert_eq!(SketchesApiVersion::V2.get_path(), SKETCHES_PATH);
        assert_eq!(SketchesApiVersion::V3.get_path(), SKETCHES_V3_PATH);
    }

    // The V3 sketches intake routes don't exist (404 -> retriable ClientError -> endless
    // retry loop that never delivers), so `sketches_api_version: v3` must be rejected at
    // config-load time rather than accepted and failed at runtime. `SketchesApiVersion::V3`
    // itself stays fully implemented (see the previous test) -- only the config surface, via
    // `#[serde(skip)]` on the variant, is disabled.
    #[test]
    fn sketches_api_version_v3_is_not_configurable() {
        let err = toml::from_str::<DatadogMetricsConfig>(
            r#"
            default_api_key = "unused"
            sketches_api_version = "v3"
            "#,
        )
        .expect_err("sketches_api_version = \"v3\" must be rejected");

        assert!(
            err.to_string().contains("unknown variant"),
            "expected an unknown-variant error, got: {err}"
        );
    }

    // `v2` -- the only configurable value -- and the unset default must both still work.
    #[test]
    fn sketches_api_version_v2_and_default_are_configurable() {
        for toml in [
            r#"default_api_key = "unused""#,
            r#"default_api_key = "unused"
            sketches_api_version = "v2""#,
        ] {
            let config = toml::from_str::<DatadogMetricsConfig>(toml)
                .expect("v2 and the unset default must both parse");
            assert_eq!(config.sketches_api_version, SketchesApiVersion::V2);
        }
    }

    // `V3Beta` requests aren't paired/correlated with a legacy twin unless they go through the
    // dual-write path (which stamps `batch_id`/`X-Metrics-Request-*` itself), and the beta route
    // is validation-only -- it doesn't provide normal ingestion. So `series_api_version: v3_beta`
    // must be rejected at config-load time rather than accepted as a primary API version.
    // `SeriesApiVersion::V3Beta` itself stays fully implemented (see the next test) -- only the
    // primary config surface, via `#[serde(skip)]` on the variant, is disabled.
    #[test]
    fn series_api_version_v3_beta_is_not_configurable() {
        let err = toml::from_str::<DatadogMetricsConfig>(
            r#"
            default_api_key = "unused"
            series_api_version = "v3_beta"
            "#,
        )
        .expect_err("series_api_version = \"v3_beta\" must be rejected");

        assert!(
            err.to_string().contains("unknown variant"),
            "expected an unknown-variant error, got: {err}"
        );
    }

    // `v1`, `v2`, `v3` -- the configurable values -- and the unset default must all still work.
    // `v3_beta` is deliberately excluded here; it's covered by the rejection test above.
    #[test]
    fn series_api_version_v1_v2_v3_and_default_are_configurable() {
        for (toml, expected) in [
            (r#"default_api_key = "unused""#, SeriesApiVersion::V2),
            (
                r#"default_api_key = "unused"
            series_api_version = "v1""#,
                SeriesApiVersion::V1,
            ),
            (
                r#"default_api_key = "unused"
            series_api_version = "v2""#,
                SeriesApiVersion::V2,
            ),
            (
                r#"default_api_key = "unused"
            series_api_version = "v3""#,
                SeriesApiVersion::V3,
            ),
        ] {
            let config = toml::from_str::<DatadogMetricsConfig>(toml)
                .expect("v1, v2, v3, and the unset default must all parse");
            assert_eq!(config.series_api_version, expected);
        }
    }

    // `SeriesApiVersion::V3Beta`'s own code must stay correct even though it can't be selected
    // as a primary `series_api_version` -- it's still constructed directly (not through serde)
    // by the dual-write shadow path in `build_sink`.
    #[test]
    fn series_api_version_v3_beta_own_code_still_works() {
        assert_eq!(SeriesApiVersion::V3Beta.get_path(), SERIES_V3_BETA_PATH);
        assert!(SeriesApiVersion::V3Beta.is_v3_format());
    }
}
