use std::fmt;

use proptest::{
    arbitrary::any,
    collection::{SizeRange, vec as arb_vec},
    prop_compose, prop_oneof,
    strategy::{Just, NewTree, Strategy, ValueTree},
    test_runner::TestRunner,
};
use tokio::time::Duration;

use super::record::Record;

/// Input action for the model/system under test.
///
/// These actions map directly to methods that can be called from the reader or writer.
///
/// One notable difference compared to the real types is that acknowledgements here are only
/// allowed to acknowledge one read at a time.
#[derive(Clone, Debug)]
pub enum Action {
    WriteRecord(Record),
    FlushWrites,
    ReadRecord,
    AcknowledgeRead,
    AdvanceTime(Duration),
    Writeback(Writeback),
    Crash,
}

/// A stream the operating system flushed to disk on its own, ahead of any explicit flush.
/// This allows us to model OS non-determinism in durability.
#[derive(Clone, Debug)]
pub enum Writeback {
    /// The ledger's memory-mapped pages reach disk, the same durable effect as an `msync`.
    LedgerContents,
    /// A data file's dirty tail reaches disk, with the given degree of completeness.
    DataContents { file: u16, tail: TailPersistence },
    /// A single file's directory entry, its creation or deletion, reaches disk.
    DirEntry(DirTarget),
}

/// The file whose directory entry reaches disk.
#[derive(Clone, Debug)]
pub enum DirTarget {
    Ledger,
    DataFile(u16),
}

/// How completely a data file's dirty tail reached disk, modelling append atomicity.
#[derive(Clone, Copy, Debug)]
pub enum TailPersistence {
    /// Every dirty unit landed intact.
    AllDirty,
    /// A trailing unit did not land; the file is truncated at a unit boundary.
    TornAtBoundary,
    /// The trailing unit's size landed but its contents are garbage.
    GarbageBoundary,
}

prop_compose! {
    fn arb_ack_amount(limit: usize)(amount in 1..limit) -> usize {
        amount
    }
}

fn arb_action() -> impl Strategy<Value = Option<Action>> {
    RemovableAction::new(arb_concrete_action())
}

fn arb_concrete_action() -> impl Strategy<Value = Action> {
    // Overall, we want reads and writes to be equal, with slightly fewer acks, and slightly fewer
    // still flushes of writes.
    prop_oneof![
        // Generate nonzero durations only so time advances shrink to 1ms. Zero advances are valid
        // no-ops, but they add noise to generated repros and are stripped if they appear.
        2 => (1u64..=20_000)
            .prop_map(|millis| Action::AdvanceTime(Duration::from_millis(millis))),
        3 => Just(Action::FlushWrites),
        5 => Just(Action::ReadRecord),
        4 => Just(Action::AcknowledgeRead),
        3 => arb_writeback().prop_map(Action::Writeback),
        1 => Just(Action::Crash),
        // The model is checking durability of successful writes; empty records are immediate
        // validation errors and make those failures shrink into unrelated error-path calls.
        5 => arb_write_record(1u32..=6),
    ]
}

fn arb_write_record<S>(event_count: S) -> impl Strategy<Value = Action>
where
    S: Strategy<Value = u32>,
{
    (any::<(u32, u16, u8)>(), event_count).prop_map(
        |((id, base_size, size_offset), event_count)| {
            let size = u32::from(base_size) + u32::from(size_offset);
            Action::WriteRecord(Record::new(id, size, event_count))
        },
    )
}

fn arb_tail_persistence() -> impl Strategy<Value = TailPersistence> {
    prop_oneof![
        Just(TailPersistence::AllDirty),
        Just(TailPersistence::TornAtBoundary),
        Just(TailPersistence::GarbageBoundary),
    ]
}

fn arb_dir_target() -> impl Strategy<Value = DirTarget> {
    prop_oneof![
        Just(DirTarget::Ledger),
        (0u16..5).prop_map(DirTarget::DataFile)
    ]
}

fn arb_writeback() -> impl Strategy<Value = Writeback> {
    prop_oneof![
        Just(Writeback::LedgerContents),
        (0u16..5, arb_tail_persistence())
            .prop_map(|(file, tail)| Writeback::DataContents { file, tail }),
        arb_dir_target().prop_map(Writeback::DirEntry),
    ]
}

pub fn arb_actions<R>(len_range: R) -> impl Strategy<Value = Vec<Action>>
where
    R: Into<SizeRange>,
{
    ActionList::new(arb_vec(arb_action(), len_range))
}

/// Sanitizes raw actions generated by proptest into a valid sequence.
///
/// While we obviously want proptest to generate randomized orderings of actions to exercise our
/// model and our system under test (SUT), there are certain combinations/orderings that are simply
/// not valid.  For example, an acknowledgement is only generated by the user of a buffer once
/// they've gotten a record from a `read` operation, so allowing an acknowledgement to exist in an
/// action sequence where there is no read is not valid and never will be.  There is no reason to
/// test such a sequence.
pub fn sanitize_raw_actions(actions: Vec<Action>) -> Vec<Action> {
    let mut unread_event_count: usize = 0;
    let mut unacked_events: usize = 0;

    actions
        .into_iter()
        .filter_map(|a| match a {
            Action::WriteRecord(record) => {
                unread_event_count += 1;
                Some(Action::WriteRecord(record))
            }
            Action::ReadRecord => {
                if unread_event_count > 0 {
                    unread_event_count -= 1;
                    unacked_events += 1;
                }
                Some(Action::ReadRecord)
            }
            Action::AcknowledgeRead => (unacked_events > 0).then(|| {
                unacked_events -= 1;
                Action::AcknowledgeRead
            }),
            Action::AdvanceTime(duration) => Some(Action::AdvanceTime(duration)),
            Action::FlushWrites => Some(Action::FlushWrites),
            // The OS flushing a stream is always a valid thing to happen.
            Action::Writeback(w) => Some(Action::Writeback(w)),
            // A crash can happen at any point and invalidates outstanding read/ack accounting,
            // since the reader restarts from its last durable position after reopen.
            Action::Crash => {
                unread_event_count += unacked_events;
                unacked_events = 0;
                Some(Action::Crash)
            }
        })
        .collect::<Vec<_>>()
}

#[derive(Clone)]
struct RemovableAction<S> {
    inner: S,
}

impl<S> RemovableAction<S> {
    const fn new(inner: S) -> Self {
        Self { inner }
    }
}

impl<S> fmt::Debug for RemovableAction<S>
where
    S: fmt::Debug,
{
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("RemovableAction")
            .field("inner", &self.inner)
            .finish()
    }
}

impl<S> Strategy for RemovableAction<S>
where
    S: Strategy<Value = Action>,
{
    type Tree = RemovableActionTree<S::Tree>;
    type Value = Option<Action>;

    fn new_tree(&self, runner: &mut TestRunner) -> NewTree<Self> {
        self.inner.new_tree(runner).map(RemovableActionTree::new)
    }
}

#[derive(Clone, Debug)]
struct RemovableActionTree<T> {
    inner: T,
    removed: bool,
    removal_rejected: bool,
}

impl<T> RemovableActionTree<T> {
    const fn new(inner: T) -> Self {
        Self {
            inner,
            removed: false,
            removal_rejected: false,
        }
    }
}

impl<T> ValueTree for RemovableActionTree<T>
where
    T: ValueTree<Value = Action>,
{
    type Value = Option<Action>;

    fn current(&self) -> Self::Value {
        (!self.removed).then(|| self.inner.current())
    }

    fn simplify(&mut self) -> bool {
        // The built-in Option shrinker only tries None after the inner value is done shrinking.
        // Retrying removal after each accepted inner shrink keeps no-op time advances out of repros.
        if !self.removed && !self.removal_rejected {
            self.removed = true;
            return true;
        }

        if !self.removed && self.inner.simplify() {
            self.removal_rejected = false;
            return true;
        }

        false
    }

    fn complicate(&mut self) -> bool {
        if self.removed {
            self.removed = false;
            self.removal_rejected = true;
            return true;
        }

        if self.inner.complicate() {
            self.removal_rejected = false;
            return true;
        }

        false
    }
}

#[derive(Clone)]
struct ActionList<S> {
    inner: S,
}

impl<S> ActionList<S> {
    const fn new(inner: S) -> Self {
        Self { inner }
    }
}

impl<S> fmt::Debug for ActionList<S>
where
    S: fmt::Debug,
{
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("ActionList")
            .field("inner", &self.inner)
            .finish()
    }
}

impl<S> Strategy for ActionList<S>
where
    S: Strategy<Value = Vec<Option<Action>>>,
{
    type Tree = ActionListTree<S::Tree>;
    type Value = Vec<Action>;

    fn new_tree(&self, runner: &mut TestRunner) -> NewTree<Self> {
        self.inner.new_tree(runner).map(ActionListTree::new)
    }
}

#[derive(Clone, Debug)]
struct ActionListTree<T> {
    inner: T,
    strip_zero_advances: bool,
    zero_strip_rejected: bool,
    last_simplification: Option<ActionListSimplification>,
}

impl<T> ActionListTree<T> {
    const fn new(inner: T) -> Self {
        Self {
            inner,
            strip_zero_advances: false,
            zero_strip_rejected: false,
            last_simplification: None,
        }
    }
}

#[derive(Clone, Copy, Debug)]
enum ActionListSimplification {
    StripZeroAdvances,
    Inner,
}

impl<T> ValueTree for ActionListTree<T>
where
    T: ValueTree<Value = Vec<Option<Action>>>,
{
    type Value = Vec<Action>;

    fn current(&self) -> Self::Value {
        raw_actions_to_actions(self.inner.current(), self.strip_zero_advances)
    }

    fn simplify(&mut self) -> bool {
        // If a zero-time advance appears during shrinking or future generator changes, remove it
        // as a no-op before the vector shrinker spends budget elsewhere.
        if !self.strip_zero_advances
            && !self.zero_strip_rejected
            && has_zero_advance(self.inner.current())
        {
            self.strip_zero_advances = true;
            self.last_simplification = Some(ActionListSimplification::StripZeroAdvances);
            return true;
        }

        if self.inner.simplify() {
            self.zero_strip_rejected = false;
            self.last_simplification = Some(ActionListSimplification::Inner);
            return true;
        }

        self.last_simplification = None;
        false
    }

    fn complicate(&mut self) -> bool {
        match self.last_simplification.take() {
            Some(ActionListSimplification::StripZeroAdvances) => {
                self.strip_zero_advances = false;
                self.zero_strip_rejected = true;
                true
            }
            Some(ActionListSimplification::Inner) if self.inner.complicate() => {
                self.zero_strip_rejected = false;
                true
            }
            Some(ActionListSimplification::Inner) | None => false,
        }
    }
}

fn raw_actions_to_actions(
    raw_actions: Vec<Option<Action>>,
    strip_zero_advances: bool,
) -> Vec<Action> {
    let actions = raw_actions.into_iter().flatten().filter(|action| {
        !(strip_zero_advances
            && matches!(action, Action::AdvanceTime(duration) if *duration == Duration::ZERO))
    });

    sanitize_raw_actions(actions.collect::<Vec<_>>())
}

fn has_zero_advance(raw_actions: Vec<Option<Action>>) -> bool {
    raw_actions
        .into_iter()
        .flatten()
        .any(|action| matches!(action, Action::AdvanceTime(duration) if duration == Duration::ZERO))
}
