#!/usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail

if [ $# -lt 1 ]
then
  echo "usage: $0 FEATURE [OPTIONS]"
  exit 1
fi

feature=$1
shift

target=$PWD/target-feature-$feature
log=$target/log

echo "Starting feature check for $feature"

mkdir -p target
cp --archive --link target $target
trap '
  cat $log
  rm --force --recursive $target
' EXIT
rm -f $target/debug/.cargo-lock

# Redirect all the output to a temporary log to avoid crossing the
# streams when this is run in parallel. The log gets dumped in the
# exit cleanup handler above.
(
  echo "===== Feature: $feature ====="
  cargo check --workspace --all-targets \
	  --no-default-features \
	  --features $feature \
	  --target-dir $target \
	  "$@"
) &> $log

# It would be nice to relink newer files back into `target` so
# subsequent runs can pick them up, but that ends up confusing `cargo`
# later in the process.
