ruby '~> 3.1.0'

# !!!
# Please try not to add more dependencies here.
# We are trying to remove Ruby entirely from this repo.
# !!!

source 'https://rubygems.org'
gem 'git', '~> 1.13.0' # for scripts/check-version.rb
gem 'paint', '~> 2.1' # for scripts/release-prepare.rb
gem 'semantic', '~> 1.6.1' # for scripts/check-version.rb
gem 'toml-rb', '~> 2.0' # for scripts/check-meta.rb
gem 'logging', '~> 2.3.1' # for scripts/generate-component-docs.rb
