ruby '~> 2.7.0'

# !!!
# Please try not to add more dependencies here.
# We are trying to remove Ruby entirely from this repo.
# !!!

source 'https://rubygems.org'
gem 'git', '~> 1.7.0' # for scripts/check-version.rb
gem 'mdl', '~> 0.9' # for scripts/check-markdown.sh
gem 'semantic', '~> 1.6.1' # for scripts/check-version.rb
gem 'toml-rb', '~> 2.0' # for scripts/check-meta.rb
