ruby '~> 3.1.0'

# !!!
# Please try not to add more dependencies here.
# We are trying to remove Ruby entirely from this repo.
# !!!

source 'https://rubygems.org'
gem 'paint', '~> 2.1' # for scripts/release-prepare.rb
gem 'logging', '~> 2.3.1' # for scripts/generate-component-docs.rb
