#!/bin/bash

# Credit: https://github.com/DataDog/datadog-agent/blob/7.32.4/Dockerfiles/manifests/generate.sh

set -euo pipefail

vdev_cmd=(${VDEV:-cargo vdev})

IFS=$'\n\t'

if sed --version 2>/dev/null | grep -q "GNU sed"; then
    SED="sed"
elif gsed --version 2>/dev/null | grep -q "GNU sed"; then
    SED="gsed"
fi

cd "$(dirname "${BASH_SOURCE[0]}")/.."

chart_version=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        --chart-version)
            chart_version="${2:?}"
            shift 2
            ;;
        *)
            echo "unknown argument: $1" >&2
            exit 1
            ;;
    esac
done

helm repo add vector https://helm.vector.dev
helm repo update

# Pin every template/show invocation to one chart version so the generated
# manifests and READMEs cannot diverge from it if the repo publishes a newer
# chart between runs of this script. Default to the latest published chart.
if [[ -z "$chart_version" ]]; then
    chart_version=$(helm search repo vector/vector -o json | yq -p json '.[0].version')
fi
readonly chart_version
echo "Generating manifests from chart version ${chart_version}"

# Refuse to regenerate from a chart older than the one the checked-in
# manifests were generated from; that would silently downgrade them. The README
# records the version it was generated with. Equal is allowed so retries and
# idempotent re-runs from the same chart pass.
current_version=$(sed -nE 's/^version ([0-9][^ ]*) with the following.*/\1/p' \
    distribution/kubernetes/vector-agent/README.md)
if [[ -n "$current_version" ]]; then
    "${vdev_cmd[@]}" version check-newer --allow-equal --what chart \
        --new "$chart_version" --current "$current_version"
fi

TMPDIR=$(mktemp -d)
trap 'rm -r $TMPDIR' EXIT

cat > "$TMPDIR/values-vector-agent.yaml" <<EOF
role: Agent
service:
  enabled: false
EOF

cat > "$TMPDIR/values-vector-aggregator.yaml" <<EOF
EOF

cat > "$TMPDIR/values-vector-stateless-aggregator.yaml" <<EOF
role: Stateless-Aggregator
EOF

CLEANUP_INSTRUCTIONS='del(.metadata.labels."helm.sh/chart") | del(.metadata.labels."app.kubernetes.io/managed-by") | del(.metadata.annotations.checksum/*) | del(.spec.template.metadata.annotations.checksum/*)'

for values in "$TMPDIR"/values-*.yaml; do
    type=${values##*values-}
    type=${type%.yaml}

    rm -rf "${type:?}"
    mkdir "${type:?}"
    helm template --namespace default vector vector/vector --version "$chart_version" --values "$values" --output-dir "$TMPDIR/generated_$type"
    for file in "$TMPDIR/generated_$type"/vector/templates/*.yaml; do
        # Skip files containing only comments
        if [[ "$(yq eval '. | length' "$file")" == 0 ]]; then
            rm "$file"
            continue
        fi
        # We want this to output without expansion
        # shellcheck disable=SC2016
        ${SED:-sed} -E -i 's/^# Source: (.*)/# This file has been generated by `helm template vector vector\/vector` from \1. Please re-run `make generate-kubernetes-manifests` rather than modifying this file manually./' "$file"
        yq eval "$CLEANUP_INSTRUCTIONS" "$file" > "distribution/kubernetes/$type/$(basename "$file")"
    done

    cat > "distribution/kubernetes/$type/README.md" <<EOF
The kubernetes manifests found in this directory have been automatically generated
from the [helm chart \`vector/vector\`](https://github.com/vectordotdev/helm-charts/tree/master/charts/vector)
version $(helm show chart vector/vector --version "$chart_version" | yq e '.version' -) with the following \`values.yaml\`:

\`\`\`yaml
$(<"$values")
\`\`\`
EOF
    rm -rf "${type:?}"
done
