#!/usr/bin/env bash
# Generates website/cue/reference/generated/internal_metric_descriptions.cue
# from website/data/docs.json.
#
# Run this after regenerating docs.json to keep metric descriptions in sync
# with the Rust source (CounterName / HistogramName / GaugeName doc comments).
set -euo pipefail

DOCS_JSON="${1:-website/data/docs.json}"
OUT="website/cue/reference/generated/internal_metric_descriptions.cue"

{
  echo 'package metadata'
  echo ''
  echo '// Auto-generated by scripts/generate-internal-metric-docs.sh'
  echo '// Do not edit manually — update the doc comment on the relevant'
  echo '// CounterName / HistogramName / GaugeName variant in'
  echo '// lib/vector-common/src/internal_event/metric_name.rs instead.'
  echo 'components: sources: internal_metrics: output: metrics: {'
  jq -r '
    .components.sources.internal_metrics.output.metrics
    | to_entries
    | sort_by(.key)
    | .[]
    | "\t\(.key): description: \(.value.description | @json)"
  ' "$DOCS_JSON"
  echo '}'
} > "$OUT"

echo "Written: $OUT ($(wc -l < "$OUT") lines)"
