#!/bin/bash

if [[ $# -gt 1 ]]; then
  echo "usage: $0 [tag]" >&2
  exit 1
fi

exec "$(dirname "$0")/vendor-released-tree.sh" \
  https://github.com/DataDog/datadog-agent \
  lib/datadog-proto/proto/datadog/trace \
  pkg/proto/datadog/trace \
  '^[0-9]+\.[0-9]+\.[0-9]+$' \
  'Datadog Agent trace protobufs' \
  update-datadog-trace-proto \
  "$@"
