{
 "title": "Vector",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } },
   { "name": "host", "label": "Host", "query": { "query": "label_values(host)" } },
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } },
   { "name": "component_id", "label": "Component id", "query": { "query": "label_values(component_id)" } },
   { "name": "component_type", "label": "Component type", "query": { "query": "label_values(component_type)" } },
   { "name": "component_kind", "label": "Component kind", "query": { "query": "label_values(component_kind)" } }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "timeseries",
     "description": "The total number of seconds the Vector instance has been up.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "{__name__=~\".*_uptime_seconds\", host =~ \"$host\", job =~ \"$job\", instance=~\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Started total",
     "type": "timeseries",
     "description": "The total number of times the Vector instance has been started.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "{ __name__ =~ \".*_started_total\", host =~ \"$host\", job =~ \"$job\", instance=~\"$instance\" }",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Kubernetes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Docker format parse failures",
     "type": "timeseries",
     "description": "The total number of failures to parse a message as a JSON object.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "{ __name__ =~ \".*_k8s_docker_format_parse_failures_total\", component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", job =~ \"$job\" }",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Messages queue",
     "type": "timeseries",
     "description": "Current number of messages in producer queues.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "{ __name__ =~ \".*_sqs_message_delete_failed_total\", component_id =~ \"$component_id\", component_kind =~ \"$component_kind\", component_type =~ \"$component_type\", host =~ \"$host\", job =~ \"$job\" }",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "SQS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Message delete failed total",
     "type": "timeseries",
     "description": "The total number of failures to delete SQS messages.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "{ __name__ =~ \".*_sqs_message_delete_failed_total\", component_id =~ \"$component_id\", component_kind =~ \"$component_kind\", component_type =~ \"$component_type\", host =~ \"$host\", job =~ \"$job\" }",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}