# STDIO Example
# ------------------------------------------------------------------------------
# A simple STDIN / STDOUT example. This script is used in the quickstart guide:
#
# https://vector.dev/docs/setup/quickstart

sources:
  in:
    type: "stdin"

sinks:
  out:
    inputs: ["in"]
    type: "console"
    encoding:
      codec: "text"
