#![allow(missing_docs)]
use std::path::{Path, PathBuf};

use rdkafka::{ClientConfig, ClientContext, Statistics, consumer::ConsumerContext};
use snafu::Snafu;
use tracing::Span;
use vector_lib::{configurable::configurable_component, sensitive_string::SensitiveString};

use crate::{
    internal_events::KafkaStatisticsReceived,
    tls::{PEM_START_MARKER, TlsEnableableConfig},
};

#[cfg(feature = "aws-core")]
mod msk_iam;

#[cfg(feature = "aws-core")]
use aws_credential_types::provider::SharedCredentialsProvider;
#[cfg(feature = "aws-core")]
use aws_types::region::Region;
#[cfg(feature = "aws-core")]
use rdkafka::client::OAuthToken;
#[cfg(feature = "aws-core")]
use tokio::runtime::Handle;
#[cfg(feature = "aws-core")]
use crate::{
    aws::{AwsAuthentication, RegionOrEndpoint},
    config::ProxyConfig,
};

#[derive(Debug, Snafu)]
enum KafkaError {
    #[snafu(display("invalid path: {:?}", path))]
    InvalidPath { path: PathBuf },
}

/// Supported compression types for Kafka.
#[configurable_component]
#[derive(Clone, Copy, Debug, Default)]
#[serde(rename_all = "lowercase")]
pub enum KafkaCompression {
    /// No compression.
    #[default]
    None,

    /// Gzip.
    Gzip,

    /// Snappy.
    Snappy,

    /// LZ4.
    Lz4,

    /// Zstandard.
    Zstd,
}

/// Kafka authentication configuration.
#[configurable_component]
#[derive(Clone, Debug, Default)]
pub struct KafkaAuthConfig {
    #[configurable(derived)]
    pub(crate) sasl: Option<KafkaSaslConfig>,

    #[configurable(derived)]
    #[configurable(metadata(docs::advanced))]
    pub(crate) tls: Option<TlsEnableableConfig>,
}

/// Configuration for SASL authentication when interacting with Kafka.
#[configurable_component]
#[derive(Clone, Debug, Default)]
pub struct KafkaSaslConfig {
    /// Enables SASL authentication.
    ///
    /// Only `PLAIN`- and `SCRAM`-based mechanisms are supported when configuring SASL authentication using `sasl.*`. For
    /// other mechanisms, `librdkafka_options.*` must be used directly to configure other `librdkafka`-specific values.
    /// If using `sasl.kerberos.*` as an example, where `*` is `service.name`, `principal`, `kinit.md`, etc., then
    /// `librdkafka_options.*` as a result becomes `librdkafka_options.sasl.kerberos.service.name`,
    /// `librdkafka_options.sasl.kerberos.principal`, etc.
    ///
    /// See the [librdkafka documentation](https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md) for details.
    ///
    /// SASL authentication is not supported on Windows.
    pub(crate) enabled: Option<bool>,

    /// The SASL username.
    #[configurable(metadata(docs::examples = "username"))]
    pub(crate) username: Option<String>,

    /// The SASL password.
    #[configurable(metadata(docs::examples = "password"))]
    pub(crate) password: Option<SensitiveString>,

    /// The SASL mechanism to use.
    #[configurable(metadata(docs::examples = "SCRAM-SHA-256"))]
    #[configurable(metadata(docs::examples = "SCRAM-SHA-512"))]
    pub(crate) mechanism: Option<String>,

    /// AWS MSK IAM authentication using SASL/OAUTHBEARER.
    ///
    /// When enabled, `mechanism` is forced to `OAUTHBEARER` and the token is generated by
    /// SigV4-presigning the `kafka-cluster:Connect` action against the configured region. Mutually
    /// exclusive with `username`/`password`. Requires TLS (MSK IAM listens on the SASL_SSL port,
    /// `9098`).
    #[cfg(feature = "aws-core")]
    #[configurable(derived)]
    pub(crate) aws_msk_iam: Option<AwsMskIamConfig>,
}

/// Configuration for AWS MSK IAM authentication (SASL/OAUTHBEARER).
#[cfg(feature = "aws-core")]
#[configurable_component]
#[derive(Clone, Debug, Default)]
pub struct AwsMskIamConfig {
    /// Enables MSK IAM authentication.
    pub(crate) enabled: bool,

    #[configurable(derived)]
    #[serde(flatten, default)]
    pub(crate) region: RegionOrEndpoint,

    #[configurable(derived)]
    #[serde(default)]
    pub(crate) auth: AwsAuthentication,
}

impl KafkaAuthConfig {
    pub(crate) fn apply(&self, client: &mut ClientConfig) -> crate::Result<()> {
        let sasl_enabled = self.sasl.as_ref().and_then(|s| s.enabled).unwrap_or(false);
        let tls_enabled = self.tls.as_ref().and_then(|s| s.enabled).unwrap_or(false);

        let protocol = match (sasl_enabled, tls_enabled) {
            (false, false) => "plaintext",
            (false, true) => "ssl",
            (true, false) => "sasl_plaintext",
            (true, true) => "sasl_ssl",
        };
        client.set("security.protocol", protocol);

        if sasl_enabled {
            let sasl = self.sasl.as_ref().unwrap();

            #[cfg(feature = "aws-core")]
            let msk_iam_enabled = sasl
                .aws_msk_iam
                .as_ref()
                .map(|c| c.enabled)
                .unwrap_or(false);
            #[cfg(not(feature = "aws-core"))]
            let msk_iam_enabled = false;

            if msk_iam_enabled {
                // OAUTHBEARER: the token itself is produced by
                // `KafkaStatisticsContext::generate_oauth_token`. No username/password.
                client.set("sasl.mechanism", "OAUTHBEARER");
            } else {
                if let Some(username) = &sasl.username {
                    client.set("sasl.username", username.as_str());
                }
                if let Some(password) = &sasl.password {
                    client.set("sasl.password", password.inner());
                }
                if let Some(mechanism) = &sasl.mechanism {
                    client.set("sasl.mechanism", mechanism);
                }
            }
        }

        if tls_enabled {
            let tls = self.tls.as_ref().unwrap();

            if let Some(verify_certificate) = &tls.options.verify_certificate {
                client.set(
                    "enable.ssl.certificate.verification",
                    verify_certificate.to_string(),
                );
            }

            if let Some(verify_hostname) = &tls.options.verify_hostname {
                client.set(
                    "ssl.endpoint.identification.algorithm",
                    if *verify_hostname { "https" } else { "none" },
                );
            }

            if let Some(path) = &tls.options.ca_file {
                let text = pathbuf_to_string(path)?;
                if text.contains(PEM_START_MARKER) {
                    client.set("ssl.ca.pem", text);
                } else {
                    client.set("ssl.ca.location", text);
                }
            }

            if let Some(path) = &tls.options.crt_file {
                let text = pathbuf_to_string(path)?;
                if text.contains(PEM_START_MARKER) {
                    client.set("ssl.certificate.pem", text);
                } else {
                    client.set("ssl.certificate.location", text);
                }
            }

            if let Some(path) = &tls.options.key_file {
                let text = pathbuf_to_string(path)?;
                if text.contains(PEM_START_MARKER) {
                    client.set("ssl.key.pem", text);
                } else {
                    client.set("ssl.key.location", text);
                }
            }

            if let Some(pass) = &tls.options.key_pass {
                client.set("ssl.key.password", pass);
            }
        }

        Ok(())
    }

    /// Resolve the AWS credential material needed by the OAUTHBEARER token callback, if (and only
    /// if) MSK IAM auth is enabled. Async because building the credentials provider (IMDS / STS /
    /// SSO) is async. Call once at build time and move the result into `KafkaStatisticsContext`.
    #[cfg(feature = "aws-core")]
    pub(crate) async fn msk_iam_credentials(
        &self,
        proxy: &ProxyConfig,
    ) -> crate::Result<Option<MskIamCredentials>> {
        let Some(cfg) = self.sasl.as_ref().and_then(|s| s.aws_msk_iam.as_ref()) else {
            return Ok(None);
        };
        if !cfg.enabled {
            return Ok(None);
        }
        let region = cfg.region.region().ok_or(
            "`sasl.aws_msk_iam` requires a region (set `sasl.aws_msk_iam.region`)",
        )?;
        let provider = cfg
            .auth
            .credentials_provider(region.clone(), proxy, None)
            .await?;
        Ok(Some(MskIamCredentials { region, provider }))
    }
}

/// AWS credential material captured at build time and moved into the rdkafka client context so the
/// (synchronous) OAUTHBEARER refresh callback can mint fresh tokens.
#[cfg(feature = "aws-core")]
#[derive(Clone)]
pub(crate) struct MskIamCredentials {
    pub(crate) region: Region,
    pub(crate) provider: SharedCredentialsProvider,
}

fn pathbuf_to_string(path: &Path) -> crate::Result<&str> {
    path.to_str()
        .ok_or_else(|| KafkaError::InvalidPath { path: path.into() }.into())
}

pub(crate) struct KafkaStatisticsContext {
    pub(crate) expose_lag_metrics: bool,
    pub span: Span,
    /// Present only when MSK IAM (SASL/OAUTHBEARER) auth is enabled.
    #[cfg(feature = "aws-core")]
    pub(crate) msk_iam: Option<MskIamCredentials>,
    /// Handle to the tokio runtime, captured at construction. The OAUTHBEARER callback runs on
    /// librdkafka's own (non-tokio) thread, so it bridges to async credential resolution via
    /// `Handle::block_on`. `Option` because construction may happen outside a runtime (e.g. tests).
    #[cfg(feature = "aws-core")]
    pub(crate) runtime: Option<Handle>,
}

impl KafkaStatisticsContext {
    #[cfg(feature = "aws-core")]
    pub(crate) fn new(
        expose_lag_metrics: bool,
        span: Span,
        msk_iam: Option<MskIamCredentials>,
    ) -> Self {
        Self {
            expose_lag_metrics,
            span,
            msk_iam,
            runtime: Handle::try_current().ok(),
        }
    }

    #[cfg(not(feature = "aws-core"))]
    pub(crate) fn new(expose_lag_metrics: bool, span: Span) -> Self {
        Self {
            expose_lag_metrics,
            span,
        }
    }
}

impl ClientContext for KafkaStatisticsContext {
    // Required for `generate_oauth_token` to be invoked by librdkafka. Harmless for non-OAUTHBEARER
    // mechanisms (SCRAM/PLAIN), where the callback is simply never called.
    #[cfg(feature = "aws-core")]
    const ENABLE_REFRESH_OAUTH_TOKEN: bool = true;

    fn stats(&self, statistics: Statistics) {
        // This callback get executed on a separate thread within the rdkafka library, so we need
        // to propagate the span here to attach the component tags to the emitted events.
        let _entered = self.span.enter();
        emit!(KafkaStatisticsReceived {
            statistics: &statistics,
            expose_lag_metrics: self.expose_lag_metrics,
        });
    }

    #[cfg(feature = "aws-core")]
    fn generate_oauth_token(
        &self,
        _oauthbearer_config: Option<&str>,
    ) -> Result<OAuthToken, Box<dyn std::error::Error>> {
        let creds = self
            .msk_iam
            .as_ref()
            .ok_or("generate_oauth_token called but MSK IAM is not configured")?;
        let runtime = self
            .runtime
            .as_ref()
            .ok_or("no tokio runtime handle available to mint the MSK IAM token")?;

        // The MSK signer signs a synthetic `kafka.{region}.amazonaws.com` host, so region +
        // credentials are all the callback needs. block_on is safe: this runs on librdkafka's own
        // (non-tokio) thread, so there is no runtime nesting.
        let token =
            runtime.block_on(msk_iam::generate_auth_token(&creds.region, &creds.provider))?;

        Ok(OAuthToken {
            token: token.token,
            // MSK ignores the principal name, but librdkafka requires it to be non-empty.
            principal_name: "vector".to_string(),
            lifetime_ms: token.lifetime_ms,
        })
    }
}

impl ConsumerContext for KafkaStatisticsContext {}

// Enables `KafkaStatisticsContext` to back a `BaseProducer` directly (used by the sink healthcheck),
// so the OAUTHBEARER token callback is available there too. The sink's `FutureProducer` wraps this
// context separately and is unaffected.
impl rdkafka::producer::ProducerContext for KafkaStatisticsContext {
    type DeliveryOpaque = ();

    fn delivery(
        &self,
        _delivery_result: &rdkafka::producer::DeliveryResult<'_>,
        _delivery_opaque: Self::DeliveryOpaque,
    ) {
    }
}
