#![allow(missing_docs)]
use std::path::{Path, PathBuf};

use rdkafka::{ClientConfig, ClientContext, Statistics, consumer::ConsumerContext};
use snafu::Snafu;
use tracing::Span;
use vector_lib::{configurable::configurable_component, sensitive_string::SensitiveString};

use crate::{
    internal_events::KafkaStatisticsReceived,
    tls::{PEM_START_MARKER, TlsEnableableConfig},
};

#[cfg(feature = "aws-core")]
mod msk_iam;

#[cfg(feature = "aws-core")]
use std::time::SystemTime;
#[cfg(feature = "aws-core")]
use aws_types::region::Region;
#[cfg(feature = "aws-core")]
use rdkafka::client::OAuthToken;
#[cfg(feature = "aws-core")]
use crate::{
    aws::{AwsAuthentication, RegionOrEndpoint},
    config::ProxyConfig,
};

#[derive(Debug, Snafu)]
enum KafkaError {
    #[snafu(display("invalid path: {:?}", path))]
    InvalidPath { path: PathBuf },
}

/// Supported compression types for Kafka.
#[configurable_component]
#[derive(Clone, Copy, Debug, Default)]
#[serde(rename_all = "lowercase")]
pub enum KafkaCompression {
    /// No compression.
    #[default]
    None,

    /// Gzip.
    Gzip,

    /// Snappy.
    Snappy,

    /// LZ4.
    Lz4,

    /// Zstandard.
    Zstd,
}

/// Kafka authentication configuration.
#[configurable_component]
#[derive(Clone, Debug, Default)]
pub struct KafkaAuthConfig {
    #[configurable(derived)]
    pub(crate) sasl: Option<KafkaSaslConfig>,

    #[configurable(derived)]
    #[configurable(metadata(docs::advanced))]
    pub(crate) tls: Option<TlsEnableableConfig>,
}

/// Configuration for SASL authentication when interacting with Kafka.
#[configurable_component]
#[derive(Clone, Debug, Default)]
pub struct KafkaSaslConfig {
    /// Enables SASL authentication.
    ///
    /// Only `PLAIN`- and `SCRAM`-based mechanisms are supported when configuring SASL authentication using `sasl.*`. For
    /// other mechanisms, `librdkafka_options.*` must be used directly to configure other `librdkafka`-specific values.
    /// If using `sasl.kerberos.*` as an example, where `*` is `service.name`, `principal`, `kinit.md`, etc., then
    /// `librdkafka_options.*` as a result becomes `librdkafka_options.sasl.kerberos.service.name`,
    /// `librdkafka_options.sasl.kerberos.principal`, etc.
    ///
    /// See the [librdkafka documentation](https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md) for details.
    ///
    /// SASL authentication is not supported on Windows.
    pub(crate) enabled: Option<bool>,

    /// The SASL username.
    #[configurable(metadata(docs::examples = "username"))]
    pub(crate) username: Option<String>,

    /// The SASL password.
    #[configurable(metadata(docs::examples = "password"))]
    pub(crate) password: Option<SensitiveString>,

    /// The SASL mechanism to use.
    #[configurable(metadata(docs::examples = "SCRAM-SHA-256"))]
    #[configurable(metadata(docs::examples = "SCRAM-SHA-512"))]
    pub(crate) mechanism: Option<String>,

    /// AWS MSK IAM authentication using SASL/OAUTHBEARER.
    ///
    /// When enabled, `mechanism` is forced to `OAUTHBEARER` and the token is generated by
    /// SigV4-presigning the `kafka-cluster:Connect` action against the configured region. Mutually
    /// exclusive with `username`/`password`. Requires TLS (MSK IAM listens on the SASL_SSL port,
    /// `9098`).
    #[cfg(feature = "aws-core")]
    #[configurable(derived)]
    pub(crate) aws_msk_iam: Option<AwsMskIamConfig>,
}

/// Configuration for AWS MSK IAM authentication (SASL/OAUTHBEARER).
#[cfg(feature = "aws-core")]
#[configurable_component]
#[derive(Clone, Debug, Default)]
pub struct AwsMskIamConfig {
    /// Enables MSK IAM authentication.
    pub(crate) enabled: bool,

    #[configurable(derived)]
    #[serde(flatten, default)]
    pub(crate) region: RegionOrEndpoint,

    #[configurable(derived)]
    #[serde(default)]
    pub(crate) auth: AwsAuthentication,
}

impl KafkaAuthConfig {
    pub(crate) fn apply(&self, client: &mut ClientConfig) -> crate::Result<()> {
        #[cfg(feature = "aws-core")]
        let msk_iam_enabled = self
            .sasl
            .as_ref()
            .and_then(|s| s.aws_msk_iam.as_ref())
            .map(|c| c.enabled)
            .unwrap_or(false);
        #[cfg(not(feature = "aws-core"))]
        let msk_iam_enabled = false;

        // MSK IAM (SASL/OAUTHBEARER) implies SASL even if the legacy `sasl.enabled` flag is unset.
        let sasl_enabled =
            self.sasl.as_ref().and_then(|s| s.enabled).unwrap_or(false) || msk_iam_enabled;
        let tls_enabled = self.tls.as_ref().and_then(|s| s.enabled).unwrap_or(false);

        // MSK IAM is only offered on the SASL_SSL (IAM) listener, so TLS is mandatory. Reject early
        // rather than silently negotiating `sasl_plaintext` and failing to connect.
        if msk_iam_enabled && !tls_enabled {
            return Err(
                "`sasl.aws_msk_iam` requires TLS; set `tls.enabled = true` (MSK IAM uses the \
                 SASL_SSL port, 9098)"
                    .into(),
            );
        }

        // rust-rdkafka gates the OAUTHBEARER refresh callback on a compile-time associated const, so
        // in `aws-core` builds it is enabled for the context whenever it exists. Vector only provides
        // a token for it via MSK IAM. Reject a bare `OAUTHBEARER` mechanism up front with guidance,
        // rather than letting the callback fire later with no token provider.
        #[cfg(feature = "aws-core")]
        if sasl_enabled
            && !msk_iam_enabled
            && self
                .sasl
                .as_ref()
                .and_then(|s| s.mechanism.as_deref())
                .is_some_and(|m| m.eq_ignore_ascii_case("OAUTHBEARER"))
        {
            return Err(
                "`sasl.mechanism = \"OAUTHBEARER\"` is only supported via `sasl.aws_msk_iam` \
                 (AWS MSK IAM)"
                    .into(),
            );
        }

        let protocol = match (sasl_enabled, tls_enabled) {
            (false, false) => "plaintext",
            (false, true) => "ssl",
            (true, false) => "sasl_plaintext",
            (true, true) => "sasl_ssl",
        };
        client.set("security.protocol", protocol);

        if sasl_enabled {
            let sasl = self.sasl.as_ref().unwrap();

            if msk_iam_enabled {
                // OAUTHBEARER: the token itself is produced by
                // `KafkaStatisticsContext::generate_oauth_token`. No username/password.
                client.set("sasl.mechanism", "OAUTHBEARER");
            } else {
                if let Some(username) = &sasl.username {
                    client.set("sasl.username", username.as_str());
                }
                if let Some(password) = &sasl.password {
                    client.set("sasl.password", password.inner());
                }
                if let Some(mechanism) = &sasl.mechanism {
                    client.set("sasl.mechanism", mechanism);
                }
            }
        }

        if tls_enabled {
            let tls = self.tls.as_ref().unwrap();

            if let Some(verify_certificate) = &tls.options.verify_certificate {
                client.set(
                    "enable.ssl.certificate.verification",
                    verify_certificate.to_string(),
                );
            }

            if let Some(verify_hostname) = &tls.options.verify_hostname {
                client.set(
                    "ssl.endpoint.identification.algorithm",
                    if *verify_hostname { "https" } else { "none" },
                );
            }

            if let Some(path) = &tls.options.ca_file {
                let text = pathbuf_to_string(path)?;
                if text.contains(PEM_START_MARKER) {
                    client.set("ssl.ca.pem", text);
                } else {
                    client.set("ssl.ca.location", text);
                }
            }

            if let Some(path) = &tls.options.crt_file {
                let text = pathbuf_to_string(path)?;
                if text.contains(PEM_START_MARKER) {
                    client.set("ssl.certificate.pem", text);
                } else {
                    client.set("ssl.certificate.location", text);
                }
            }

            if let Some(path) = &tls.options.key_file {
                let text = pathbuf_to_string(path)?;
                if text.contains(PEM_START_MARKER) {
                    client.set("ssl.key.pem", text);
                } else {
                    client.set("ssl.key.location", text);
                }
            }

            if let Some(pass) = &tls.options.key_pass {
                client.set("ssl.key.password", pass);
            }
        }

        Ok(())
    }

    /// Resolve the AWS credential material needed by the OAUTHBEARER token callback, if (and only
    /// if) MSK IAM auth is enabled. Async because building the credentials provider (IMDS / STS /
    /// SSO) is async. Call once at build time and move the result into `KafkaStatisticsContext`.
    #[cfg(feature = "aws-core")]
    pub(crate) async fn msk_iam_credentials(
        &self,
        proxy: &ProxyConfig,
    ) -> crate::Result<Option<MskIamCredentials>> {
        let Some(cfg) = self.sasl.as_ref().and_then(|s| s.aws_msk_iam.as_ref()) else {
            return Ok(None);
        };
        if !cfg.enabled {
            return Ok(None);
        }
        let region = cfg.region.region().ok_or(
            "`sasl.aws_msk_iam` requires a region (set `sasl.aws_msk_iam.region`)",
        )?;
        // The signer host honors an explicit endpoint and resolves the partition suffix (e.g. China
        // regions use `amazonaws.com.cn`).
        let host = msk_iam::signing_host(region.as_ref(), cfg.region.endpoint().as_deref());
        let provider = cfg
            .auth
            .credentials_provider(region.clone(), proxy, None)
            .await?;
        // Resolve now (fail fast on misconfig, honoring the configured load timeout) and keep them
        // refreshed in the background so the token callback stays synchronous.
        let credentials =
            msk_iam::spawn_credentials_cache(provider, cfg.auth.load_timeout()).await?;
        Ok(Some(MskIamCredentials {
            region,
            host,
            credentials,
        }))
    }

    /// Validate `librdkafka_options` against the MSK IAM / OAUTHBEARER constraints. Both the source
    /// and sink apply `librdkafka_options` *after* [`Self::apply`], so:
    ///
    /// * When MSK IAM is enabled, a leftover `security.protocol`/`sasl.*` override would silently
    ///   drop OAUTHBEARER/SASL_SSL — the component would load credentials but fail to authenticate.
    /// * When MSK IAM is not enabled, setting `sasl.mechanism = OAUTHBEARER` here would still reach
    ///   the always-on refresh callback (which has no token provider) — reject it with the same
    ///   guidance as the top-level `sasl.mechanism` guard.
    #[cfg(feature = "aws-core")]
    pub(crate) fn validate_librdkafka_overrides<'a>(
        &self,
        options: impl IntoIterator<Item = (&'a String, &'a String)>,
    ) -> crate::Result<()> {
        let msk_iam_enabled = self
            .sasl
            .as_ref()
            .and_then(|s| s.aws_msk_iam.as_ref())
            .map(|c| c.enabled)
            .unwrap_or(false);

        const RESERVED: [&str; 4] = [
            "security.protocol",
            "sasl.mechanism",
            "sasl.username",
            "sasl.password",
        ];
        for (key, value) in options {
            if msk_iam_enabled {
                if RESERVED.iter().any(|r| key.eq_ignore_ascii_case(r)) {
                    return Err(format!(
                        "`librdkafka_options.{key}` conflicts with `sasl.aws_msk_iam`; remove it \
                         (MSK IAM manages `security.protocol` and `sasl.*`)"
                    )
                    .into());
                }
            } else if key.eq_ignore_ascii_case("sasl.mechanism")
                && value.eq_ignore_ascii_case("OAUTHBEARER")
            {
                return Err(
                    "`librdkafka_options.sasl.mechanism = \"OAUTHBEARER\"` is only supported via \
                     `sasl.aws_msk_iam` (AWS MSK IAM)"
                        .into(),
                );
            }
        }
        Ok(())
    }
}

/// AWS credential material moved into the rdkafka client context so the (synchronous) OAUTHBEARER
/// refresh callback can mint fresh tokens without any async/`block_on`.
#[cfg(feature = "aws-core")]
#[derive(Clone)]
pub(crate) struct MskIamCredentials {
    pub(crate) region: Region,
    /// The SigV4 signing host (partition-aware, honoring an explicit endpoint).
    pub(crate) host: String,
    pub(crate) credentials: msk_iam::CredentialsCache,
}

fn pathbuf_to_string(path: &Path) -> crate::Result<&str> {
    path.to_str()
        .ok_or_else(|| KafkaError::InvalidPath { path: path.into() }.into())
}

pub(crate) struct KafkaStatisticsContext {
    pub(crate) expose_lag_metrics: bool,
    pub span: Span,
    /// Present only when MSK IAM (SASL/OAUTHBEARER) auth is enabled.
    #[cfg(feature = "aws-core")]
    pub(crate) msk_iam: Option<MskIamCredentials>,
}

impl KafkaStatisticsContext {
    #[cfg(feature = "aws-core")]
    pub(crate) fn new(
        expose_lag_metrics: bool,
        span: Span,
        msk_iam: Option<MskIamCredentials>,
    ) -> Self {
        Self {
            expose_lag_metrics,
            span,
            msk_iam,
        }
    }

    #[cfg(not(feature = "aws-core"))]
    pub(crate) fn new(expose_lag_metrics: bool, span: Span) -> Self {
        Self {
            expose_lag_metrics,
            span,
        }
    }
}

impl ClientContext for KafkaStatisticsContext {
    // Required for `generate_oauth_token` to be invoked by librdkafka. Harmless for non-OAUTHBEARER
    // mechanisms (SCRAM/PLAIN), where the callback is simply never called.
    #[cfg(feature = "aws-core")]
    const ENABLE_REFRESH_OAUTH_TOKEN: bool = true;

    fn stats(&self, statistics: Statistics) {
        // This callback get executed on a separate thread within the rdkafka library, so we need
        // to propagate the span here to attach the component tags to the emitted events.
        let _entered = self.span.enter();
        emit!(KafkaStatisticsReceived {
            statistics: &statistics,
            expose_lag_metrics: self.expose_lag_metrics,
        });
    }

    #[cfg(feature = "aws-core")]
    fn generate_oauth_token(
        &self,
        _oauthbearer_config: Option<&str>,
    ) -> Result<OAuthToken, Box<dyn std::error::Error>> {
        let creds = self
            .msk_iam
            .as_ref()
            .ok_or("generate_oauth_token called but MSK IAM is not configured")?;

        // Fully synchronous: read the background-refreshed credentials and sign. No async / block_on,
        // so this is safe even when invoked on the tokio runtime thread that polls the consumer.
        let credentials = creds
            .credentials
            .lock()
            .map_err(|_| "MSK IAM credential cache mutex poisoned")?
            .clone();
        let token =
            msk_iam::build_token(&creds.region, &creds.host, &credentials, SystemTime::now())?;

        Ok(OAuthToken {
            token: token.token,
            // MSK ignores the principal name, but librdkafka requires it to be non-empty.
            principal_name: "vector".to_string(),
            lifetime_ms: token.lifetime_ms,
        })
    }
}

impl ConsumerContext for KafkaStatisticsContext {}

#[cfg(test)]
mod auth_tests {
    //! Exercises `KafkaAuthConfig::apply` across the full Kafka authentication matrix, mapped to the
    //! AWS MSK connection options (docs: MSK "Port information"):
    //!   * PLAINTEXT              (:9092)          -> `security.protocol=plaintext`
    //!   * TLS encryption / mTLS  (:9094)          -> `security.protocol=ssl`
    //!   * SASL/SCRAM over TLS    (:9096)          -> `security.protocol=sasl_ssl`, mechanism SCRAM
    //!   * SASL/IAM over TLS      (:9098)          -> `security.protocol=sasl_ssl`, mechanism OAUTHBEARER
    //! plus the non-MSK-but-valid librdkafka combos (SASL over plaintext) and the TLS<->non-TLS axis.
    use super::*;
    use rdkafka::ClientConfig;

    fn applied(auth: &KafkaAuthConfig) -> ClientConfig {
        let mut cc = ClientConfig::new();
        auth.apply(&mut cc).expect("apply");
        cc
    }

    fn sasl(enabled: Option<bool>, mechanism: Option<&str>, user: Option<&str>) -> KafkaSaslConfig {
        KafkaSaslConfig {
            enabled,
            username: user.map(str::to_owned),
            password: user.map(|_| "pw".to_owned().into()),
            mechanism: mechanism.map(str::to_owned),
            ..Default::default()
        }
    }

    fn tls(enabled: bool) -> TlsEnableableConfig {
        TlsEnableableConfig {
            enabled: Some(enabled),
            ..Default::default()
        }
    }

    // ---- security.protocol matrix: (sasl_enabled x tls_enabled) ----

    #[test]
    fn protocol_plaintext_when_nothing_enabled() {
        let cc = applied(&KafkaAuthConfig::default());
        assert_eq!(cc.get("security.protocol"), Some("plaintext"));
        assert_eq!(cc.get("sasl.mechanism"), None);
    }

    #[test]
    fn protocol_ssl_when_only_tls() {
        // MSK TLS encryption / mTLS listener (:9094).
        let auth = KafkaAuthConfig {
            sasl: None,
            tls: Some(tls(true)),
        };
        let cc = applied(&auth);
        assert_eq!(cc.get("security.protocol"), Some("ssl"));
        assert_eq!(cc.get("sasl.mechanism"), None);
    }

    #[test]
    fn protocol_sasl_plaintext_when_sasl_without_tls() {
        // Not an MSK option, but a valid librdkafka combo for self-managed Kafka.
        let auth = KafkaAuthConfig {
            sasl: Some(sasl(Some(true), Some("SCRAM-SHA-512"), Some("u"))),
            tls: None,
        };
        assert_eq!(applied(&auth).get("security.protocol"), Some("sasl_plaintext"));
    }

    #[test]
    fn protocol_sasl_ssl_when_sasl_and_tls() {
        let auth = KafkaAuthConfig {
            sasl: Some(sasl(Some(true), Some("SCRAM-SHA-512"), Some("u"))),
            tls: Some(tls(true)),
        };
        assert_eq!(applied(&auth).get("security.protocol"), Some("sasl_ssl"));
    }

    // ---- SASL mechanism selection (non-MSK) ----

    #[test]
    fn scram_sets_mechanism_and_credentials() {
        // MSK SASL/SCRAM listener (:9096).
        let auth = KafkaAuthConfig {
            sasl: Some(sasl(Some(true), Some("SCRAM-SHA-512"), Some("alice"))),
            tls: Some(tls(true)),
        };
        let cc = applied(&auth);
        assert_eq!(cc.get("sasl.mechanism"), Some("SCRAM-SHA-512"));
        assert_eq!(cc.get("sasl.username"), Some("alice"));
        assert_eq!(cc.get("sasl.password"), Some("pw"));
    }

    #[test]
    fn plain_mechanism_is_passed_through() {
        let auth = KafkaAuthConfig {
            sasl: Some(sasl(Some(true), Some("PLAIN"), Some("alice"))),
            tls: Some(tls(true)),
        };
        assert_eq!(applied(&auth).get("sasl.mechanism"), Some("PLAIN"));
    }

    #[test]
    fn sasl_present_but_disabled_sets_no_mechanism() {
        let auth = KafkaAuthConfig {
            sasl: Some(sasl(Some(false), Some("SCRAM-SHA-512"), Some("u"))),
            tls: Some(tls(true)),
        };
        let cc = applied(&auth);
        assert_eq!(cc.get("security.protocol"), Some("ssl")); // sasl off -> just TLS
        assert_eq!(cc.get("sasl.mechanism"), None);
    }

    // ---- TLS option plumbing ----

    #[test]
    fn tls_verify_certificate_flag_is_plumbed() {
        let mut t = tls(true);
        t.options.verify_certificate = Some(false);
        let auth = KafkaAuthConfig {
            sasl: None,
            tls: Some(t),
        };
        assert_eq!(
            applied(&auth).get("enable.ssl.certificate.verification"),
            Some("false")
        );
    }

    // ---- MSK IAM (SASL/OAUTHBEARER) ----

    #[cfg(feature = "aws-core")]
    fn msk_sasl(sasl_enabled: Option<bool>, user: Option<&str>) -> KafkaSaslConfig {
        KafkaSaslConfig {
            enabled: sasl_enabled,
            username: user.map(str::to_owned),
            password: user.map(|_| "pw".to_owned().into()),
            mechanism: None,
            aws_msk_iam: Some(AwsMskIamConfig {
                enabled: true,
                ..Default::default()
            }),
        }
    }

    #[cfg(feature = "aws-core")]
    #[test]
    fn msk_iam_over_tls_uses_oauthbearer() {
        // MSK SASL/IAM listener (:9098): SASL_SSL + OAUTHBEARER, no username/password.
        let auth = KafkaAuthConfig {
            sasl: Some(msk_sasl(Some(true), None)),
            tls: Some(tls(true)),
        };
        let cc = applied(&auth);
        assert_eq!(cc.get("security.protocol"), Some("sasl_ssl"));
        assert_eq!(cc.get("sasl.mechanism"), Some("OAUTHBEARER"));
        assert_eq!(cc.get("sasl.username"), None);
        assert_eq!(cc.get("sasl.password"), None);
    }

    #[cfg(feature = "aws-core")]
    #[test]
    fn bare_oauthbearer_mechanism_is_rejected() {
        // OAUTHBEARER is only wired up for MSK IAM; a manual mechanism must fail fast with guidance.
        let auth = KafkaAuthConfig {
            sasl: Some(sasl(Some(true), Some("OAUTHBEARER"), None)),
            tls: Some(tls(true)),
        };
        let mut cc = ClientConfig::new();
        let err = auth.apply(&mut cc).expect_err("bare OAUTHBEARER must be rejected");
        assert!(err.to_string().contains("aws_msk_iam"), "got: {err}");
    }

    #[cfg(feature = "aws-core")]
    #[test]
    fn disabled_sasl_stanza_with_oauthbearer_is_ignored() {
        // An inactive SASL stanza (enabled=false) never sets a mechanism, so it must not be rejected
        // — supports keeping a stanza around for templating/rollbacks.
        let auth = KafkaAuthConfig {
            sasl: Some(sasl(Some(false), Some("OAUTHBEARER"), None)),
            tls: Some(tls(true)),
        };
        let cc = applied(&auth);
        assert_eq!(cc.get("security.protocol"), Some("ssl"));
        assert_eq!(cc.get("sasl.mechanism"), None);
    }

    #[cfg(feature = "aws-core")]
    #[test]
    fn librdkafka_overrides_conflicting_with_msk_iam_are_rejected() {
        use std::collections::HashMap;
        let auth = KafkaAuthConfig {
            sasl: Some(msk_sasl(Some(true), None)),
            tls: Some(tls(true)),
        };
        for key in [
            "security.protocol",
            "sasl.mechanism",
            "sasl.username",
            "sasl.password",
        ] {
            let opts = HashMap::from([(key.to_string(), "x".to_string())]);
            let err = auth
                .validate_librdkafka_overrides(opts.iter())
                .expect_err("conflicting override must be rejected");
            assert!(err.to_string().contains(key), "got: {err}");
        }
        // Benign options are fine.
        let ok = HashMap::from([("socket.timeout.ms".to_string(), "1000".to_string())]);
        assert!(auth.validate_librdkafka_overrides(ok.iter()).is_ok());
    }

    #[cfg(feature = "aws-core")]
    #[test]
    fn librdkafka_overrides_ignored_without_msk_iam() {
        // Without MSK IAM, non-OAUTHBEARER overrides are the user's own business.
        use std::collections::HashMap;
        let auth = KafkaAuthConfig {
            sasl: Some(sasl(Some(true), Some("SCRAM-SHA-512"), Some("u"))),
            tls: Some(tls(true)),
        };
        let opts = HashMap::from([("sasl.mechanism".to_string(), "PLAIN".to_string())]);
        assert!(auth.validate_librdkafka_overrides(opts.iter()).is_ok());
    }

    #[cfg(feature = "aws-core")]
    #[test]
    fn librdkafka_oauthbearer_without_msk_iam_is_rejected() {
        // Closes the gap where OAUTHBEARER set via librdkafka_options (not the mechanism field) would
        // still reach the always-on refresh callback with no token provider.
        use std::collections::HashMap;
        let auth = KafkaAuthConfig {
            sasl: Some(sasl(Some(true), None, None)),
            tls: Some(tls(true)),
        };
        let opts = HashMap::from([("sasl.mechanism".to_string(), "OAUTHBEARER".to_string())]);
        let err = auth
            .validate_librdkafka_overrides(opts.iter())
            .expect_err("librdkafka OAUTHBEARER without MSK IAM must be rejected");
        assert!(err.to_string().contains("aws_msk_iam"), "got: {err}");
    }

    #[cfg(feature = "aws-core")]
    #[test]
    fn msk_iam_without_tls_is_rejected() {
        // MSK IAM is SASL_SSL-only; applying without TLS must be a hard error, not sasl_plaintext.
        let auth = KafkaAuthConfig {
            sasl: Some(msk_sasl(Some(true), None)),
            tls: None,
        };
        let mut cc = ClientConfig::new();
        let err = auth.apply(&mut cc).expect_err("must reject MSK IAM without TLS");
        assert!(err.to_string().contains("requires TLS"), "got: {err}");
    }

    #[cfg(feature = "aws-core")]
    #[test]
    fn msk_iam_enables_sasl_without_legacy_flag() {
        // Regression: `aws_msk_iam.enabled` alone must turn SASL on (sasl.enabled left unset).
        let auth = KafkaAuthConfig {
            sasl: Some(msk_sasl(None, None)),
            tls: Some(tls(true)),
        };
        let cc = applied(&auth);
        assert_eq!(cc.get("security.protocol"), Some("sasl_ssl"));
        assert_eq!(cc.get("sasl.mechanism"), Some("OAUTHBEARER"));
    }

    #[cfg(feature = "aws-core")]
    #[test]
    fn msk_iam_ignores_username_password() {
        // If both MSK IAM and username/password are set, OAUTHBEARER wins and no creds are emitted.
        let auth = KafkaAuthConfig {
            sasl: Some(msk_sasl(Some(true), Some("alice"))),
            tls: Some(tls(true)),
        };
        let cc = applied(&auth);
        assert_eq!(cc.get("sasl.mechanism"), Some("OAUTHBEARER"));
        assert_eq!(cc.get("sasl.username"), None);
        assert_eq!(cc.get("sasl.password"), None);
    }

    #[cfg(feature = "aws-core")]
    #[test]
    fn msk_iam_disabled_flag_falls_back_to_plain_sasl() {
        // aws_msk_iam present but enabled=false -> behaves like ordinary SASL config.
        let auth = KafkaAuthConfig {
            sasl: Some(KafkaSaslConfig {
                enabled: Some(true),
                mechanism: Some("SCRAM-SHA-256".to_owned()),
                username: Some("u".to_owned()),
                password: Some("pw".to_owned().into()),
                aws_msk_iam: Some(AwsMskIamConfig {
                    enabled: false,
                    ..Default::default()
                }),
            }),
            tls: Some(tls(true)),
        };
        let cc = applied(&auth);
        assert_eq!(cc.get("sasl.mechanism"), Some("SCRAM-SHA-256"));
        assert_eq!(cc.get("sasl.username"), Some("u"));
    }
}
