#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 96
#define LARGE_STATE_COUNT 17
#define SYMBOL_COUNT 54
#define ALIAS_COUNT 0
#define TOKEN_COUNT 26
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 1

enum {
  sym__horizontal_ws = 1,
  aux_sym_newline_token1 = 2,
  anon_sym_SEMI = 3,
  sym_null = 4,
  aux_sym_string_token1 = 5,
  anon_sym_BSLASH = 6,
  aux_sym_string_token2 = 7,
  anon_sym_true = 8,
  anon_sym_false = 9,
  anon_sym_s = 10,
  anon_sym_r = 11,
  anon_sym_SQUOTE = 12,
  aux_sym_raw_token1 = 13,
  aux_sym_raw_token2 = 14,
  anon_sym_DASH = 15,
  aux_sym_whole_number_token1 = 16,
  anon_sym_DOT = 17,
  sym_local_variable = 18,
  sym__single_quote = 19,
  sym_quoted_field = 20,
  aux_sym_query_field_token1 = 21,
  anon_sym_LPAREN = 22,
  anon_sym_PIPE = 23,
  anon_sym_RPAREN = 24,
  anon_sym_PERCENT = 25,
  sym_program = 26,
  sym_exprs = 27,
  sym_expr = 28,
  sym_literal = 29,
  sym_string = 30,
  sym_boolean = 31,
  sym_raw_string = 32,
  sym_raw_regex = 33,
  sym_raw = 34,
  sym__integer = 35,
  sym_integer = 36,
  sym__whole_number = 37,
  sym_float = 38,
  sym_query = 39,
  sym_local_query = 40,
  sym_query_segments = 41,
  sym__query_segment = 42,
  sym_query_field = 43,
  sym_query_coalesce = 44,
  sym_target_query = 45,
  sym_target_query_prefix = 46,
  aux_sym_newline_repeat1 = 47,
  aux_sym_ws_repeat1 = 48,
  aux_sym_exprs_repeat1 = 49,
  aux_sym_string_repeat1 = 50,
  aux_sym_raw_repeat1 = 51,
  aux_sym_query_segments_repeat1 = 52,
  aux_sym_query_coalesce_repeat1 = 53,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__horizontal_ws] = "_horizontal_ws",
  [aux_sym_newline_token1] = "newline_token1",
  [anon_sym_SEMI] = ";",
  [sym_null] = "null",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_BSLASH] = "\\",
  [aux_sym_string_token2] = "string_token2",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_s] = "s",
  [anon_sym_r] = "r",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_raw_token1] = "raw_token1",
  [aux_sym_raw_token2] = "raw_token2",
  [anon_sym_DASH] = "-",
  [aux_sym_whole_number_token1] = "whole_number_token1",
  [anon_sym_DOT] = ".",
  [sym_local_variable] = "local_variable",
  [sym__single_quote] = "_single_quote",
  [sym_quoted_field] = "quoted_field",
  [aux_sym_query_field_token1] = "query_field_token1",
  [anon_sym_LPAREN] = "(",
  [anon_sym_PIPE] = "|",
  [anon_sym_RPAREN] = ")",
  [anon_sym_PERCENT] = "%",
  [sym_program] = "program",
  [sym_exprs] = "exprs",
  [sym_expr] = "expr",
  [sym_literal] = "literal",
  [sym_string] = "string",
  [sym_boolean] = "boolean",
  [sym_raw_string] = "raw_string",
  [sym_raw_regex] = "raw_regex",
  [sym_raw] = "raw",
  [sym__integer] = "_integer",
  [sym_integer] = "integer",
  [sym__whole_number] = "_whole_number",
  [sym_float] = "float",
  [sym_query] = "query",
  [sym_local_query] = "local_query",
  [sym_query_segments] = "query_segments",
  [sym__query_segment] = "_query_segment",
  [sym_query_field] = "query_field",
  [sym_query_coalesce] = "query_coalesce",
  [sym_target_query] = "target_query",
  [sym_target_query_prefix] = "target_query_prefix",
  [aux_sym_newline_repeat1] = "newline_repeat1",
  [aux_sym_ws_repeat1] = "ws_repeat1",
  [aux_sym_exprs_repeat1] = "exprs_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_raw_repeat1] = "raw_repeat1",
  [aux_sym_query_segments_repeat1] = "query_segments_repeat1",
  [aux_sym_query_coalesce_repeat1] = "query_coalesce_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__horizontal_ws] = sym__horizontal_ws,
  [aux_sym_newline_token1] = aux_sym_newline_token1,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym_null] = sym_null,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_s] = anon_sym_s,
  [anon_sym_r] = anon_sym_r,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_raw_token1] = aux_sym_raw_token1,
  [aux_sym_raw_token2] = aux_sym_raw_token2,
  [anon_sym_DASH] = anon_sym_DASH,
  [aux_sym_whole_number_token1] = aux_sym_whole_number_token1,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_local_variable] = sym_local_variable,
  [sym__single_quote] = sym__single_quote,
  [sym_quoted_field] = sym_quoted_field,
  [aux_sym_query_field_token1] = aux_sym_query_field_token1,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [sym_program] = sym_program,
  [sym_exprs] = sym_exprs,
  [sym_expr] = sym_expr,
  [sym_literal] = sym_literal,
  [sym_string] = sym_string,
  [sym_boolean] = sym_boolean,
  [sym_raw_string] = sym_raw_string,
  [sym_raw_regex] = sym_raw_regex,
  [sym_raw] = sym_raw,
  [sym__integer] = sym__integer,
  [sym_integer] = sym_integer,
  [sym__whole_number] = sym__whole_number,
  [sym_float] = sym_float,
  [sym_query] = sym_query,
  [sym_local_query] = sym_local_query,
  [sym_query_segments] = sym_query_segments,
  [sym__query_segment] = sym__query_segment,
  [sym_query_field] = sym_query_field,
  [sym_query_coalesce] = sym_query_coalesce,
  [sym_target_query] = sym_target_query,
  [sym_target_query_prefix] = sym_target_query_prefix,
  [aux_sym_newline_repeat1] = aux_sym_newline_repeat1,
  [aux_sym_ws_repeat1] = aux_sym_ws_repeat1,
  [aux_sym_exprs_repeat1] = aux_sym_exprs_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_raw_repeat1] = aux_sym_raw_repeat1,
  [aux_sym_query_segments_repeat1] = aux_sym_query_segments_repeat1,
  [aux_sym_query_coalesce_repeat1] = aux_sym_query_coalesce_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__horizontal_ws] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_newline_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_s] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_r] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_raw_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_raw_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_whole_number_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_local_variable] = {
    .visible = true,
    .named = true,
  },
  [sym__single_quote] = {
    .visible = false,
    .named = true,
  },
  [sym_quoted_field] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_query_field_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym_exprs] = {
    .visible = true,
    .named = true,
  },
  [sym_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_string] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_regex] = {
    .visible = true,
    .named = true,
  },
  [sym_raw] = {
    .visible = true,
    .named = true,
  },
  [sym__integer] = {
    .visible = false,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym__whole_number] = {
    .visible = false,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym_query] = {
    .visible = true,
    .named = true,
  },
  [sym_local_query] = {
    .visible = true,
    .named = true,
  },
  [sym_query_segments] = {
    .visible = true,
    .named = true,
  },
  [sym__query_segment] = {
    .visible = false,
    .named = true,
  },
  [sym_query_field] = {
    .visible = true,
    .named = true,
  },
  [sym_query_coalesce] = {
    .visible = true,
    .named = true,
  },
  [sym_target_query] = {
    .visible = true,
    .named = true,
  },
  [sym_target_query_prefix] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_newline_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_ws_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_exprs_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_raw_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_query_segments_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_query_coalesce_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(9);
      if (lookahead == '\n') ADVANCE(11);
      if (lookahead == '"') ADVANCE(41);
      if (lookahead == '%') ADVANCE(48);
      if (lookahead == '\'') ADVANCE(23);
      if (lookahead == '(') ADVANCE(45);
      if (lookahead == ')') ADVANCE(47);
      if (lookahead == '-') ADVANCE(26);
      if (lookahead == '.') ADVANCE(29);
      if (lookahead == ';') ADVANCE(12);
      if (lookahead == '\\') ADVANCE(15);
      if (lookahead == 'r') ADVANCE(21);
      if (lookahead == 's') ADVANCE(19);
      if (lookahead == '|') ADVANCE(46);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(10);
      if (lookahead == 'n' ||
          lookahead == 't' ||
          ('{' <= lookahead && lookahead <= '}')) ADVANCE(14);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(41);
      if (lookahead == '\\') ADVANCE(15);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 2:
      if (lookahead == '\'') ADVANCE(23);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead != 0) ADVANCE(25);
      END_STATE();
    case 3:
      if (lookahead == '\\') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(42);
      END_STATE();
    case 4:
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(16);
      END_STATE();
    case 5:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(5);
      if (('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 6:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(24);
      END_STATE();
    case 7:
      if (eof) ADVANCE(9);
      if (lookahead == '\n') ADVANCE(11);
      if (lookahead == '"') ADVANCE(41);
      if (lookahead == '%') ADVANCE(48);
      if (lookahead == '\'') ADVANCE(23);
      if (lookahead == ')') ADVANCE(47);
      if (lookahead == '-') ADVANCE(26);
      if (lookahead == '.') ADVANCE(29);
      if (lookahead == ';') ADVANCE(12);
      if (lookahead == '_') ADVANCE(28);
      if (lookahead == 'f') ADVANCE(30);
      if (lookahead == 'n') ADVANCE(39);
      if (lookahead == 'r') ADVANCE(22);
      if (lookahead == 's') ADVANCE(20);
      if (lookahead == 't') ADVANCE(36);
      if (lookahead == '|') ADVANCE(46);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 8:
      if (eof) ADVANCE(9);
      if (lookahead == '\n') ADVANCE(11);
      if (lookahead == '"') ADVANCE(41);
      if (lookahead == '(') ADVANCE(45);
      if (lookahead == ';') ADVANCE(12);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(5);
      if (('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym__horizontal_ws);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym_newline_token1);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_null);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_string_token1);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_string_token2);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_s);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_s);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_r);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_r);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_raw_token1);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_raw_token2);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_whole_number_token1);
      if (lookahead == '_') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_whole_number_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_local_variable);
      if (lookahead == 'a') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_local_variable);
      if (lookahead == 'e') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_local_variable);
      if (lookahead == 'e') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_local_variable);
      if (lookahead == 'l') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_local_variable);
      if (lookahead == 'l') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_local_variable);
      if (lookahead == 'l') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_local_variable);
      if (lookahead == 'r') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_local_variable);
      if (lookahead == 's') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_local_variable);
      if (lookahead == 'u') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_local_variable);
      if (lookahead == 'u') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_local_variable);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym__single_quote);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_quoted_field);
      if (lookahead == '\\') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_quoted_field);
      if (lookahead != 0 &&
          lookahead != '\\') ADVANCE(42);
      if (lookahead == '\\') ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_query_field_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 7},
  [2] = {.lex_state = 7},
  [3] = {.lex_state = 7},
  [4] = {.lex_state = 7},
  [5] = {.lex_state = 7},
  [6] = {.lex_state = 7},
  [7] = {.lex_state = 7},
  [8] = {.lex_state = 7},
  [9] = {.lex_state = 7},
  [10] = {.lex_state = 7},
  [11] = {.lex_state = 7},
  [12] = {.lex_state = 7},
  [13] = {.lex_state = 7},
  [14] = {.lex_state = 7},
  [15] = {.lex_state = 7},
  [16] = {.lex_state = 7},
  [17] = {.lex_state = 7},
  [18] = {.lex_state = 7},
  [19] = {.lex_state = 7},
  [20] = {.lex_state = 8},
  [21] = {.lex_state = 8},
  [22] = {.lex_state = 7},
  [23] = {.lex_state = 8},
  [24] = {.lex_state = 7},
  [25] = {.lex_state = 7},
  [26] = {.lex_state = 8},
  [27] = {.lex_state = 8},
  [28] = {.lex_state = 8},
  [29] = {.lex_state = 7},
  [30] = {.lex_state = 7},
  [31] = {.lex_state = 8},
  [32] = {.lex_state = 7},
  [33] = {.lex_state = 8},
  [34] = {.lex_state = 7},
  [35] = {.lex_state = 7},
  [36] = {.lex_state = 8},
  [37] = {.lex_state = 7},
  [38] = {.lex_state = 7},
  [39] = {.lex_state = 8},
  [40] = {.lex_state = 7},
  [41] = {.lex_state = 7},
  [42] = {.lex_state = 8},
  [43] = {.lex_state = 7},
  [44] = {.lex_state = 7},
  [45] = {.lex_state = 7},
  [46] = {.lex_state = 7},
  [47] = {.lex_state = 7},
  [48] = {.lex_state = 7},
  [49] = {.lex_state = 7},
  [50] = {.lex_state = 7},
  [51] = {.lex_state = 7},
  [52] = {.lex_state = 7},
  [53] = {.lex_state = 7},
  [54] = {.lex_state = 7},
  [55] = {.lex_state = 7},
  [56] = {.lex_state = 7},
  [57] = {.lex_state = 7},
  [58] = {.lex_state = 7},
  [59] = {.lex_state = 8},
  [60] = {.lex_state = 7},
  [61] = {.lex_state = 7},
  [62] = {.lex_state = 1},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 7},
  [65] = {.lex_state = 7},
  [66] = {.lex_state = 2},
  [67] = {.lex_state = 7},
  [68] = {.lex_state = 7},
  [69] = {.lex_state = 7},
  [70] = {.lex_state = 7},
  [71] = {.lex_state = 7},
  [72] = {.lex_state = 7},
  [73] = {.lex_state = 7},
  [74] = {.lex_state = 7},
  [75] = {.lex_state = 7},
  [76] = {.lex_state = 7},
  [77] = {.lex_state = 2},
  [78] = {.lex_state = 7},
  [79] = {.lex_state = 7},
  [80] = {.lex_state = 7},
  [81] = {.lex_state = 7},
  [82] = {.lex_state = 1},
  [83] = {.lex_state = 7},
  [84] = {.lex_state = 7},
  [85] = {.lex_state = 7},
  [86] = {.lex_state = 2},
  [87] = {.lex_state = 1},
  [88] = {.lex_state = 7},
  [89] = {.lex_state = 7},
  [90] = {.lex_state = 7},
  [91] = {.lex_state = 7},
  [92] = {.lex_state = 4},
  [93] = {.lex_state = 7},
  [94] = {.lex_state = 3},
  [95] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__horizontal_ws] = ACTIONS(1),
    [aux_sym_newline_token1] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [aux_sym_string_token1] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [aux_sym_string_token2] = ACTIONS(1),
    [anon_sym_s] = ACTIONS(1),
    [anon_sym_r] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [aux_sym_raw_token2] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym__single_quote] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
  },
  [1] = {
    [sym_program] = STATE(95),
    [sym_exprs] = STATE(53),
    [sym_expr] = STATE(22),
    [sym_literal] = STATE(75),
    [sym_string] = STATE(84),
    [sym_boolean] = STATE(84),
    [sym_raw_string] = STATE(84),
    [sym_raw_regex] = STATE(84),
    [sym__integer] = STATE(51),
    [sym_integer] = STATE(84),
    [sym__whole_number] = STATE(51),
    [sym_float] = STATE(84),
    [sym_query] = STATE(75),
    [sym_local_query] = STATE(76),
    [sym_target_query] = STATE(76),
    [sym_target_query_prefix] = STATE(20),
    [aux_sym_newline_repeat1] = STATE(11),
    [aux_sym_ws_repeat1] = STATE(11),
    [sym__horizontal_ws] = ACTIONS(3),
    [aux_sym_newline_token1] = ACTIONS(3),
    [sym_null] = ACTIONS(5),
    [anon_sym_true] = ACTIONS(7),
    [anon_sym_false] = ACTIONS(7),
    [anon_sym_s] = ACTIONS(9),
    [anon_sym_r] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(13),
    [aux_sym_whole_number_token1] = ACTIONS(15),
    [anon_sym_DOT] = ACTIONS(17),
    [sym_local_variable] = ACTIONS(19),
    [sym__single_quote] = ACTIONS(21),
    [anon_sym_PERCENT] = ACTIONS(17),
  },
  [2] = {
    [sym_expr] = STATE(85),
    [sym_literal] = STATE(75),
    [sym_string] = STATE(84),
    [sym_boolean] = STATE(84),
    [sym_raw_string] = STATE(84),
    [sym_raw_regex] = STATE(84),
    [sym__integer] = STATE(51),
    [sym_integer] = STATE(84),
    [sym__whole_number] = STATE(51),
    [sym_float] = STATE(84),
    [sym_query] = STATE(75),
    [sym_local_query] = STATE(76),
    [sym_target_query] = STATE(76),
    [sym_target_query_prefix] = STATE(20),
    [aux_sym_newline_repeat1] = STATE(19),
    [aux_sym_ws_repeat1] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(23),
    [sym__horizontal_ws] = ACTIONS(25),
    [aux_sym_newline_token1] = ACTIONS(29),
    [anon_sym_SEMI] = ACTIONS(33),
    [sym_null] = ACTIONS(5),
    [anon_sym_true] = ACTIONS(7),
    [anon_sym_false] = ACTIONS(7),
    [anon_sym_s] = ACTIONS(9),
    [anon_sym_r] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(13),
    [aux_sym_whole_number_token1] = ACTIONS(15),
    [anon_sym_DOT] = ACTIONS(17),
    [sym_local_variable] = ACTIONS(19),
    [sym__single_quote] = ACTIONS(21),
    [anon_sym_PERCENT] = ACTIONS(17),
  },
  [3] = {
    [sym_expr] = STATE(85),
    [sym_literal] = STATE(75),
    [sym_string] = STATE(84),
    [sym_boolean] = STATE(84),
    [sym_raw_string] = STATE(84),
    [sym_raw_regex] = STATE(84),
    [sym__integer] = STATE(51),
    [sym_integer] = STATE(84),
    [sym__whole_number] = STATE(51),
    [sym_float] = STATE(84),
    [sym_query] = STATE(75),
    [sym_local_query] = STATE(76),
    [sym_target_query] = STATE(76),
    [sym_target_query_prefix] = STATE(20),
    [aux_sym_newline_repeat1] = STATE(19),
    [aux_sym_ws_repeat1] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(35),
    [sym__horizontal_ws] = ACTIONS(37),
    [aux_sym_newline_token1] = ACTIONS(41),
    [anon_sym_SEMI] = ACTIONS(33),
    [sym_null] = ACTIONS(5),
    [anon_sym_true] = ACTIONS(7),
    [anon_sym_false] = ACTIONS(7),
    [anon_sym_s] = ACTIONS(9),
    [anon_sym_r] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(13),
    [aux_sym_whole_number_token1] = ACTIONS(15),
    [anon_sym_DOT] = ACTIONS(17),
    [sym_local_variable] = ACTIONS(19),
    [sym__single_quote] = ACTIONS(21),
    [anon_sym_PERCENT] = ACTIONS(17),
  },
  [4] = {
    [sym_expr] = STATE(64),
    [sym_literal] = STATE(75),
    [sym_string] = STATE(84),
    [sym_boolean] = STATE(84),
    [sym_raw_string] = STATE(84),
    [sym_raw_regex] = STATE(84),
    [sym__integer] = STATE(51),
    [sym_integer] = STATE(84),
    [sym__whole_number] = STATE(51),
    [sym_float] = STATE(84),
    [sym_query] = STATE(75),
    [sym_local_query] = STATE(76),
    [sym_target_query] = STATE(76),
    [sym_target_query_prefix] = STATE(20),
    [aux_sym_newline_repeat1] = STATE(19),
    [aux_sym_ws_repeat1] = STATE(14),
    [ts_builtin_sym_end] = ACTIONS(23),
    [sym__horizontal_ws] = ACTIONS(45),
    [aux_sym_newline_token1] = ACTIONS(29),
    [anon_sym_SEMI] = ACTIONS(33),
    [sym_null] = ACTIONS(5),
    [anon_sym_true] = ACTIONS(7),
    [anon_sym_false] = ACTIONS(7),
    [anon_sym_s] = ACTIONS(9),
    [anon_sym_r] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(13),
    [aux_sym_whole_number_token1] = ACTIONS(15),
    [anon_sym_DOT] = ACTIONS(17),
    [sym_local_variable] = ACTIONS(19),
    [sym__single_quote] = ACTIONS(21),
    [anon_sym_PERCENT] = ACTIONS(17),
  },
  [5] = {
    [sym_expr] = STATE(64),
    [sym_literal] = STATE(75),
    [sym_string] = STATE(84),
    [sym_boolean] = STATE(84),
    [sym_raw_string] = STATE(84),
    [sym_raw_regex] = STATE(84),
    [sym__integer] = STATE(51),
    [sym_integer] = STATE(84),
    [sym__whole_number] = STATE(51),
    [sym_float] = STATE(84),
    [sym_query] = STATE(75),
    [sym_local_query] = STATE(76),
    [sym_target_query] = STATE(76),
    [sym_target_query_prefix] = STATE(20),
    [aux_sym_newline_repeat1] = STATE(19),
    [aux_sym_ws_repeat1] = STATE(14),
    [ts_builtin_sym_end] = ACTIONS(49),
    [sym__horizontal_ws] = ACTIONS(51),
    [aux_sym_newline_token1] = ACTIONS(55),
    [anon_sym_SEMI] = ACTIONS(33),
    [sym_null] = ACTIONS(5),
    [anon_sym_true] = ACTIONS(7),
    [anon_sym_false] = ACTIONS(7),
    [anon_sym_s] = ACTIONS(9),
    [anon_sym_r] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(13),
    [aux_sym_whole_number_token1] = ACTIONS(15),
    [anon_sym_DOT] = ACTIONS(17),
    [sym_local_variable] = ACTIONS(19),
    [sym__single_quote] = ACTIONS(21),
    [anon_sym_PERCENT] = ACTIONS(17),
  },
  [6] = {
    [sym_expr] = STATE(85),
    [sym_literal] = STATE(75),
    [sym_string] = STATE(84),
    [sym_boolean] = STATE(84),
    [sym_raw_string] = STATE(84),
    [sym_raw_regex] = STATE(84),
    [sym__integer] = STATE(51),
    [sym_integer] = STATE(84),
    [sym__whole_number] = STATE(51),
    [sym_float] = STATE(84),
    [sym_query] = STATE(75),
    [sym_local_query] = STATE(76),
    [sym_target_query] = STATE(76),
    [sym_target_query_prefix] = STATE(20),
    [aux_sym_newline_repeat1] = STATE(19),
    [aux_sym_ws_repeat1] = STATE(15),
    [sym__horizontal_ws] = ACTIONS(33),
    [aux_sym_newline_token1] = ACTIONS(33),
    [anon_sym_SEMI] = ACTIONS(33),
    [sym_null] = ACTIONS(5),
    [anon_sym_true] = ACTIONS(7),
    [anon_sym_false] = ACTIONS(7),
    [anon_sym_s] = ACTIONS(9),
    [anon_sym_r] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(13),
    [aux_sym_whole_number_token1] = ACTIONS(15),
    [anon_sym_DOT] = ACTIONS(17),
    [sym_local_variable] = ACTIONS(19),
    [sym__single_quote] = ACTIONS(21),
    [anon_sym_PERCENT] = ACTIONS(17),
  },
  [7] = {
    [sym_expr] = STATE(64),
    [sym_literal] = STATE(75),
    [sym_string] = STATE(84),
    [sym_boolean] = STATE(84),
    [sym_raw_string] = STATE(84),
    [sym_raw_regex] = STATE(84),
    [sym__integer] = STATE(51),
    [sym_integer] = STATE(84),
    [sym__whole_number] = STATE(51),
    [sym_float] = STATE(84),
    [sym_query] = STATE(75),
    [sym_local_query] = STATE(76),
    [sym_target_query] = STATE(76),
    [sym_target_query_prefix] = STATE(20),
    [aux_sym_newline_repeat1] = STATE(14),
    [aux_sym_ws_repeat1] = STATE(14),
    [ts_builtin_sym_end] = ACTIONS(49),
    [sym__horizontal_ws] = ACTIONS(59),
    [aux_sym_newline_token1] = ACTIONS(59),
    [sym_null] = ACTIONS(5),
    [anon_sym_true] = ACTIONS(7),
    [anon_sym_false] = ACTIONS(7),
    [anon_sym_s] = ACTIONS(9),
    [anon_sym_r] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(13),
    [aux_sym_whole_number_token1] = ACTIONS(15),
    [anon_sym_DOT] = ACTIONS(17),
    [sym_local_variable] = ACTIONS(19),
    [sym__single_quote] = ACTIONS(21),
    [anon_sym_PERCENT] = ACTIONS(17),
  },
  [8] = {
    [sym_expr] = STATE(85),
    [sym_literal] = STATE(75),
    [sym_string] = STATE(84),
    [sym_boolean] = STATE(84),
    [sym_raw_string] = STATE(84),
    [sym_raw_regex] = STATE(84),
    [sym__integer] = STATE(51),
    [sym_integer] = STATE(84),
    [sym__whole_number] = STATE(51),
    [sym_float] = STATE(84),
    [sym_query] = STATE(75),
    [sym_local_query] = STATE(76),
    [sym_target_query] = STATE(76),
    [sym_target_query_prefix] = STATE(20),
    [aux_sym_newline_repeat1] = STATE(15),
    [aux_sym_ws_repeat1] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(23),
    [sym__horizontal_ws] = ACTIONS(62),
    [aux_sym_newline_token1] = ACTIONS(62),
    [sym_null] = ACTIONS(5),
    [anon_sym_true] = ACTIONS(7),
    [anon_sym_false] = ACTIONS(7),
    [anon_sym_s] = ACTIONS(9),
    [anon_sym_r] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(13),
    [aux_sym_whole_number_token1] = ACTIONS(15),
    [anon_sym_DOT] = ACTIONS(17),
    [sym_local_variable] = ACTIONS(19),
    [sym__single_quote] = ACTIONS(21),
    [anon_sym_PERCENT] = ACTIONS(17),
  },
  [9] = {
    [sym_expr] = STATE(64),
    [sym_literal] = STATE(75),
    [sym_string] = STATE(84),
    [sym_boolean] = STATE(84),
    [sym_raw_string] = STATE(84),
    [sym_raw_regex] = STATE(84),
    [sym__integer] = STATE(51),
    [sym_integer] = STATE(84),
    [sym__whole_number] = STATE(51),
    [sym_float] = STATE(84),
    [sym_query] = STATE(75),
    [sym_local_query] = STATE(76),
    [sym_target_query] = STATE(76),
    [sym_target_query_prefix] = STATE(20),
    [aux_sym_newline_repeat1] = STATE(19),
    [aux_sym_ws_repeat1] = STATE(14),
    [sym__horizontal_ws] = ACTIONS(33),
    [aux_sym_newline_token1] = ACTIONS(33),
    [anon_sym_SEMI] = ACTIONS(33),
    [sym_null] = ACTIONS(5),
    [anon_sym_true] = ACTIONS(7),
    [anon_sym_false] = ACTIONS(7),
    [anon_sym_s] = ACTIONS(9),
    [anon_sym_r] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(13),
    [aux_sym_whole_number_token1] = ACTIONS(15),
    [anon_sym_DOT] = ACTIONS(17),
    [sym_local_variable] = ACTIONS(19),
    [sym__single_quote] = ACTIONS(21),
    [anon_sym_PERCENT] = ACTIONS(17),
  },
  [10] = {
    [sym_expr] = STATE(64),
    [sym_literal] = STATE(75),
    [sym_string] = STATE(84),
    [sym_boolean] = STATE(84),
    [sym_raw_string] = STATE(84),
    [sym_raw_regex] = STATE(84),
    [sym__integer] = STATE(51),
    [sym_integer] = STATE(84),
    [sym__whole_number] = STATE(51),
    [sym_float] = STATE(84),
    [sym_query] = STATE(75),
    [sym_local_query] = STATE(76),
    [sym_target_query] = STATE(76),
    [sym_target_query_prefix] = STATE(20),
    [aux_sym_newline_repeat1] = STATE(14),
    [aux_sym_ws_repeat1] = STATE(14),
    [ts_builtin_sym_end] = ACTIONS(23),
    [sym__horizontal_ws] = ACTIONS(65),
    [aux_sym_newline_token1] = ACTIONS(65),
    [sym_null] = ACTIONS(5),
    [anon_sym_true] = ACTIONS(7),
    [anon_sym_false] = ACTIONS(7),
    [anon_sym_s] = ACTIONS(9),
    [anon_sym_r] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(13),
    [aux_sym_whole_number_token1] = ACTIONS(15),
    [anon_sym_DOT] = ACTIONS(17),
    [sym_local_variable] = ACTIONS(19),
    [sym__single_quote] = ACTIONS(21),
    [anon_sym_PERCENT] = ACTIONS(17),
  },
  [11] = {
    [sym_exprs] = STATE(60),
    [sym_expr] = STATE(22),
    [sym_literal] = STATE(75),
    [sym_string] = STATE(84),
    [sym_boolean] = STATE(84),
    [sym_raw_string] = STATE(84),
    [sym_raw_regex] = STATE(84),
    [sym__integer] = STATE(51),
    [sym_integer] = STATE(84),
    [sym__whole_number] = STATE(51),
    [sym_float] = STATE(84),
    [sym_query] = STATE(75),
    [sym_local_query] = STATE(76),
    [sym_target_query] = STATE(76),
    [sym_target_query_prefix] = STATE(20),
    [aux_sym_newline_repeat1] = STATE(17),
    [aux_sym_ws_repeat1] = STATE(17),
    [sym__horizontal_ws] = ACTIONS(68),
    [aux_sym_newline_token1] = ACTIONS(68),
    [sym_null] = ACTIONS(5),
    [anon_sym_true] = ACTIONS(7),
    [anon_sym_false] = ACTIONS(7),
    [anon_sym_s] = ACTIONS(9),
    [anon_sym_r] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(13),
    [aux_sym_whole_number_token1] = ACTIONS(15),
    [anon_sym_DOT] = ACTIONS(17),
    [sym_local_variable] = ACTIONS(19),
    [sym__single_quote] = ACTIONS(21),
    [anon_sym_PERCENT] = ACTIONS(17),
  },
  [12] = {
    [sym_expr] = STATE(85),
    [sym_literal] = STATE(75),
    [sym_string] = STATE(84),
    [sym_boolean] = STATE(84),
    [sym_raw_string] = STATE(84),
    [sym_raw_regex] = STATE(84),
    [sym__integer] = STATE(51),
    [sym_integer] = STATE(84),
    [sym__whole_number] = STATE(51),
    [sym_float] = STATE(84),
    [sym_query] = STATE(75),
    [sym_local_query] = STATE(76),
    [sym_target_query] = STATE(76),
    [sym_target_query_prefix] = STATE(20),
    [aux_sym_newline_repeat1] = STATE(15),
    [aux_sym_ws_repeat1] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(35),
    [sym__horizontal_ws] = ACTIONS(70),
    [aux_sym_newline_token1] = ACTIONS(70),
    [sym_null] = ACTIONS(5),
    [anon_sym_true] = ACTIONS(7),
    [anon_sym_false] = ACTIONS(7),
    [anon_sym_s] = ACTIONS(9),
    [anon_sym_r] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(13),
    [aux_sym_whole_number_token1] = ACTIONS(15),
    [anon_sym_DOT] = ACTIONS(17),
    [sym_local_variable] = ACTIONS(19),
    [sym__single_quote] = ACTIONS(21),
    [anon_sym_PERCENT] = ACTIONS(17),
  },
  [13] = {
    [sym_expr] = STATE(85),
    [sym_literal] = STATE(75),
    [sym_string] = STATE(84),
    [sym_boolean] = STATE(84),
    [sym_raw_string] = STATE(84),
    [sym_raw_regex] = STATE(84),
    [sym__integer] = STATE(51),
    [sym_integer] = STATE(84),
    [sym__whole_number] = STATE(51),
    [sym_float] = STATE(84),
    [sym_query] = STATE(75),
    [sym_local_query] = STATE(76),
    [sym_target_query] = STATE(76),
    [sym_target_query_prefix] = STATE(20),
    [aux_sym_newline_repeat1] = STATE(15),
    [aux_sym_ws_repeat1] = STATE(15),
    [sym__horizontal_ws] = ACTIONS(73),
    [aux_sym_newline_token1] = ACTIONS(73),
    [sym_null] = ACTIONS(5),
    [anon_sym_true] = ACTIONS(7),
    [anon_sym_false] = ACTIONS(7),
    [anon_sym_s] = ACTIONS(9),
    [anon_sym_r] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(13),
    [aux_sym_whole_number_token1] = ACTIONS(15),
    [anon_sym_DOT] = ACTIONS(17),
    [sym_local_variable] = ACTIONS(19),
    [sym__single_quote] = ACTIONS(21),
    [anon_sym_PERCENT] = ACTIONS(17),
  },
  [14] = {
    [sym_expr] = STATE(78),
    [sym_literal] = STATE(75),
    [sym_string] = STATE(84),
    [sym_boolean] = STATE(84),
    [sym_raw_string] = STATE(84),
    [sym_raw_regex] = STATE(84),
    [sym__integer] = STATE(51),
    [sym_integer] = STATE(84),
    [sym__whole_number] = STATE(51),
    [sym_float] = STATE(84),
    [sym_query] = STATE(75),
    [sym_local_query] = STATE(76),
    [sym_target_query] = STATE(76),
    [sym_target_query_prefix] = STATE(20),
    [aux_sym_newline_repeat1] = STATE(17),
    [aux_sym_ws_repeat1] = STATE(17),
    [sym__horizontal_ws] = ACTIONS(68),
    [aux_sym_newline_token1] = ACTIONS(68),
    [sym_null] = ACTIONS(5),
    [anon_sym_true] = ACTIONS(7),
    [anon_sym_false] = ACTIONS(7),
    [anon_sym_s] = ACTIONS(9),
    [anon_sym_r] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(13),
    [aux_sym_whole_number_token1] = ACTIONS(15),
    [anon_sym_DOT] = ACTIONS(17),
    [sym_local_variable] = ACTIONS(19),
    [sym__single_quote] = ACTIONS(21),
    [anon_sym_PERCENT] = ACTIONS(17),
  },
  [15] = {
    [sym_expr] = STATE(64),
    [sym_literal] = STATE(75),
    [sym_string] = STATE(84),
    [sym_boolean] = STATE(84),
    [sym_raw_string] = STATE(84),
    [sym_raw_regex] = STATE(84),
    [sym__integer] = STATE(51),
    [sym_integer] = STATE(84),
    [sym__whole_number] = STATE(51),
    [sym_float] = STATE(84),
    [sym_query] = STATE(75),
    [sym_local_query] = STATE(76),
    [sym_target_query] = STATE(76),
    [sym_target_query_prefix] = STATE(20),
    [aux_sym_newline_repeat1] = STATE(17),
    [aux_sym_ws_repeat1] = STATE(17),
    [sym__horizontal_ws] = ACTIONS(68),
    [aux_sym_newline_token1] = ACTIONS(68),
    [sym_null] = ACTIONS(5),
    [anon_sym_true] = ACTIONS(7),
    [anon_sym_false] = ACTIONS(7),
    [anon_sym_s] = ACTIONS(9),
    [anon_sym_r] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(13),
    [aux_sym_whole_number_token1] = ACTIONS(15),
    [anon_sym_DOT] = ACTIONS(17),
    [sym_local_variable] = ACTIONS(19),
    [sym__single_quote] = ACTIONS(21),
    [anon_sym_PERCENT] = ACTIONS(17),
  },
  [16] = {
    [sym_expr] = STATE(64),
    [sym_literal] = STATE(75),
    [sym_string] = STATE(84),
    [sym_boolean] = STATE(84),
    [sym_raw_string] = STATE(84),
    [sym_raw_regex] = STATE(84),
    [sym__integer] = STATE(51),
    [sym_integer] = STATE(84),
    [sym__whole_number] = STATE(51),
    [sym_float] = STATE(84),
    [sym_query] = STATE(75),
    [sym_local_query] = STATE(76),
    [sym_target_query] = STATE(76),
    [sym_target_query_prefix] = STATE(20),
    [aux_sym_newline_repeat1] = STATE(14),
    [aux_sym_ws_repeat1] = STATE(14),
    [sym__horizontal_ws] = ACTIONS(75),
    [aux_sym_newline_token1] = ACTIONS(75),
    [sym_null] = ACTIONS(5),
    [anon_sym_true] = ACTIONS(7),
    [anon_sym_false] = ACTIONS(7),
    [anon_sym_s] = ACTIONS(9),
    [anon_sym_r] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(13),
    [aux_sym_whole_number_token1] = ACTIONS(15),
    [anon_sym_DOT] = ACTIONS(17),
    [sym_local_variable] = ACTIONS(19),
    [sym__single_quote] = ACTIONS(21),
    [anon_sym_PERCENT] = ACTIONS(17),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(79), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(17), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
    ACTIONS(82), 7,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      anon_sym_s,
      anon_sym_r,
      aux_sym_whole_number_token1,
      sym_local_variable,
    ACTIONS(77), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_DOT,
      sym__single_quote,
      anon_sym_PIPE,
      anon_sym_RPAREN,
      anon_sym_PERCENT,
  [28] = 4,
    ACTIONS(86), 1,
      aux_sym_newline_token1,
    STATE(18), 1,
      aux_sym_newline_repeat1,
    ACTIONS(89), 7,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      anon_sym_s,
      anon_sym_r,
      aux_sym_whole_number_token1,
      sym_local_variable,
    ACTIONS(84), 9,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_DOT,
      sym__single_quote,
      anon_sym_PIPE,
      anon_sym_RPAREN,
      anon_sym_PERCENT,
  [55] = 5,
    ACTIONS(94), 1,
      aux_sym_newline_token1,
    STATE(18), 1,
      aux_sym_newline_repeat1,
    ACTIONS(84), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
    ACTIONS(91), 5,
      sym__horizontal_ws,
      anon_sym_DASH,
      anon_sym_DOT,
      sym__single_quote,
      anon_sym_PERCENT,
    ACTIONS(98), 7,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      anon_sym_s,
      anon_sym_r,
      aux_sym_whole_number_token1,
      sym_local_variable,
  [82] = 6,
    ACTIONS(103), 1,
      sym__single_quote,
    ACTIONS(105), 1,
      aux_sym_query_field_token1,
    ACTIONS(107), 1,
      anon_sym_LPAREN,
    STATE(67), 1,
      sym_query_segments,
    STATE(40), 3,
      sym__query_segment,
      sym_query_field,
      sym_query_coalesce,
    ACTIONS(101), 4,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
  [106] = 5,
    ACTIONS(103), 1,
      sym__single_quote,
    ACTIONS(105), 1,
      aux_sym_query_field_token1,
    STATE(81), 1,
      sym_query_field,
    ACTIONS(109), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(28), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [124] = 7,
    ACTIONS(111), 1,
      ts_builtin_sym_end,
    ACTIONS(113), 1,
      sym__horizontal_ws,
    ACTIONS(116), 1,
      aux_sym_newline_token1,
    ACTIONS(119), 1,
      anon_sym_SEMI,
    STATE(3), 1,
      aux_sym_newline_repeat1,
    STATE(32), 1,
      aux_sym_exprs_repeat1,
    STATE(56), 1,
      aux_sym_ws_repeat1,
  [146] = 5,
    ACTIONS(103), 1,
      sym__single_quote,
    ACTIONS(105), 1,
      aux_sym_query_field_token1,
    STATE(69), 1,
      sym_query_field,
    ACTIONS(121), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(39), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [164] = 5,
    ACTIONS(125), 1,
      anon_sym_PIPE,
    ACTIONS(127), 1,
      anon_sym_RPAREN,
    STATE(25), 1,
      aux_sym_query_coalesce_repeat1,
    ACTIONS(123), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(44), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [182] = 5,
    ACTIONS(132), 1,
      anon_sym_PIPE,
    ACTIONS(135), 1,
      anon_sym_RPAREN,
    STATE(25), 1,
      aux_sym_query_coalesce_repeat1,
    ACTIONS(129), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(55), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [200] = 5,
    ACTIONS(103), 1,
      sym__single_quote,
    ACTIONS(105), 1,
      aux_sym_query_field_token1,
    ACTIONS(107), 1,
      anon_sym_LPAREN,
    STATE(68), 1,
      sym_query_segments,
    STATE(40), 3,
      sym__query_segment,
      sym_query_field,
      sym_query_coalesce,
  [218] = 5,
    ACTIONS(103), 1,
      sym__single_quote,
    ACTIONS(105), 1,
      aux_sym_query_field_token1,
    STATE(79), 1,
      sym_query_field,
    ACTIONS(137), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(23), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [236] = 5,
    ACTIONS(103), 1,
      sym__single_quote,
    ACTIONS(105), 1,
      aux_sym_query_field_token1,
    STATE(79), 1,
      sym_query_field,
    ACTIONS(121), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(39), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [254] = 5,
    ACTIONS(125), 1,
      anon_sym_PIPE,
    ACTIONS(141), 1,
      anon_sym_RPAREN,
    STATE(25), 1,
      aux_sym_query_coalesce_repeat1,
    ACTIONS(139), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(45), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [272] = 1,
    ACTIONS(143), 7,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_PIPE,
      anon_sym_RPAREN,
  [282] = 1,
    ACTIONS(145), 7,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
      sym__single_quote,
      aux_sym_query_field_token1,
      anon_sym_LPAREN,
  [292] = 7,
    ACTIONS(35), 1,
      ts_builtin_sym_end,
    ACTIONS(147), 1,
      sym__horizontal_ws,
    ACTIONS(150), 1,
      aux_sym_newline_token1,
    ACTIONS(153), 1,
      anon_sym_SEMI,
    STATE(2), 1,
      aux_sym_newline_repeat1,
    STATE(34), 1,
      aux_sym_exprs_repeat1,
    STATE(54), 1,
      aux_sym_ws_repeat1,
  [314] = 5,
    ACTIONS(103), 1,
      sym__single_quote,
    ACTIONS(105), 1,
      aux_sym_query_field_token1,
    STATE(38), 1,
      sym_query_field,
    ACTIONS(121), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(39), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [332] = 7,
    ACTIONS(155), 1,
      ts_builtin_sym_end,
    ACTIONS(157), 1,
      sym__horizontal_ws,
    ACTIONS(160), 1,
      aux_sym_newline_token1,
    ACTIONS(163), 1,
      anon_sym_SEMI,
    STATE(6), 1,
      aux_sym_newline_repeat1,
    STATE(34), 1,
      aux_sym_exprs_repeat1,
    STATE(58), 1,
      aux_sym_ws_repeat1,
  [354] = 1,
    ACTIONS(166), 7,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_PIPE,
      anon_sym_RPAREN,
  [364] = 5,
    ACTIONS(103), 1,
      sym__single_quote,
    ACTIONS(105), 1,
      aux_sym_query_field_token1,
    STATE(43), 1,
      sym_query_field,
    ACTIONS(168), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(33), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [382] = 3,
    ACTIONS(172), 1,
      anon_sym_DOT,
    STATE(37), 1,
      aux_sym_query_segments_repeat1,
    ACTIONS(170), 4,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
  [395] = 4,
    ACTIONS(125), 1,
      anon_sym_PIPE,
    STATE(24), 1,
      aux_sym_query_coalesce_repeat1,
    ACTIONS(175), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(55), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [410] = 3,
    ACTIONS(77), 2,
      sym__single_quote,
      aux_sym_query_field_token1,
    ACTIONS(177), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(39), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [423] = 3,
    ACTIONS(182), 1,
      anon_sym_DOT,
    STATE(41), 1,
      aux_sym_query_segments_repeat1,
    ACTIONS(180), 4,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
  [436] = 3,
    ACTIONS(182), 1,
      anon_sym_DOT,
    STATE(37), 1,
      aux_sym_query_segments_repeat1,
    ACTIONS(184), 4,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
  [449] = 4,
    ACTIONS(103), 1,
      sym__single_quote,
    ACTIONS(105), 1,
      aux_sym_query_field_token1,
    ACTIONS(107), 1,
      anon_sym_LPAREN,
    STATE(49), 3,
      sym__query_segment,
      sym_query_field,
      sym_query_coalesce,
  [464] = 4,
    ACTIONS(125), 1,
      anon_sym_PIPE,
    STATE(29), 1,
      aux_sym_query_coalesce_repeat1,
    ACTIONS(175), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(55), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [479] = 4,
    ACTIONS(186), 1,
      anon_sym_PIPE,
    ACTIONS(188), 1,
      anon_sym_RPAREN,
    ACTIONS(68), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(17), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [494] = 4,
    ACTIONS(127), 1,
      anon_sym_RPAREN,
    ACTIONS(186), 1,
      anon_sym_PIPE,
    ACTIONS(68), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(17), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [509] = 1,
    ACTIONS(190), 5,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
      anon_sym_DOT,
  [517] = 1,
    ACTIONS(192), 5,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
      anon_sym_DOT,
  [525] = 1,
    ACTIONS(194), 5,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
      anon_sym_DOT,
  [533] = 1,
    ACTIONS(170), 5,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
      anon_sym_DOT,
  [541] = 2,
    ACTIONS(198), 1,
      anon_sym_DOT,
    ACTIONS(196), 4,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
  [551] = 2,
    ACTIONS(202), 1,
      anon_sym_DOT,
    ACTIONS(200), 4,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
  [561] = 3,
    ACTIONS(204), 1,
      ts_builtin_sym_end,
    ACTIONS(68), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(17), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [573] = 3,
    ACTIONS(206), 1,
      ts_builtin_sym_end,
    ACTIONS(208), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(52), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [585] = 5,
    ACTIONS(68), 1,
      sym__horizontal_ws,
    ACTIONS(210), 1,
      aux_sym_newline_token1,
    ACTIONS(212), 1,
      anon_sym_SEMI,
    STATE(5), 1,
      aux_sym_newline_repeat1,
    STATE(17), 1,
      aux_sym_ws_repeat1,
  [601] = 3,
    ACTIONS(186), 1,
      anon_sym_PIPE,
    ACTIONS(68), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(17), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [613] = 5,
    ACTIONS(68), 1,
      sym__horizontal_ws,
    ACTIONS(214), 1,
      aux_sym_newline_token1,
    ACTIONS(216), 1,
      anon_sym_SEMI,
    STATE(4), 1,
      aux_sym_newline_repeat1,
    STATE(17), 1,
      aux_sym_ws_repeat1,
  [629] = 1,
    ACTIONS(218), 5,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
      anon_sym_DOT,
  [637] = 5,
    ACTIONS(68), 1,
      sym__horizontal_ws,
    ACTIONS(220), 1,
      aux_sym_newline_token1,
    ACTIONS(222), 1,
      anon_sym_SEMI,
    STATE(9), 1,
      aux_sym_newline_repeat1,
    STATE(17), 1,
      aux_sym_ws_repeat1,
  [653] = 3,
    ACTIONS(224), 1,
      aux_sym_newline_token1,
    STATE(59), 1,
      aux_sym_newline_repeat1,
    ACTIONS(84), 3,
      sym__horizontal_ws,
      sym__single_quote,
      aux_sym_query_field_token1,
  [665] = 3,
    ACTIONS(204), 1,
      ts_builtin_sym_end,
    ACTIONS(227), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(61), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [677] = 3,
    ACTIONS(229), 1,
      ts_builtin_sym_end,
    ACTIONS(68), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(17), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [689] = 4,
    ACTIONS(231), 1,
      aux_sym_string_token1,
    ACTIONS(233), 1,
      anon_sym_BSLASH,
    ACTIONS(235), 1,
      sym__single_quote,
    STATE(82), 1,
      aux_sym_string_repeat1,
  [702] = 4,
    ACTIONS(237), 1,
      aux_sym_string_token1,
    ACTIONS(240), 1,
      anon_sym_BSLASH,
    ACTIONS(243), 1,
      sym__single_quote,
    STATE(63), 1,
      aux_sym_string_repeat1,
  [715] = 1,
    ACTIONS(245), 4,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
  [722] = 1,
    ACTIONS(247), 4,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
  [729] = 4,
    ACTIONS(249), 1,
      anon_sym_SQUOTE,
    ACTIONS(251), 1,
      aux_sym_raw_token1,
    ACTIONS(253), 1,
      aux_sym_raw_token2,
    STATE(86), 1,
      aux_sym_raw_repeat1,
  [742] = 1,
    ACTIONS(255), 4,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
  [749] = 1,
    ACTIONS(257), 4,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
  [756] = 1,
    ACTIONS(259), 4,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_PIPE,
      anon_sym_RPAREN,
  [763] = 1,
    ACTIONS(261), 4,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
  [770] = 1,
    ACTIONS(263), 4,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
  [777] = 1,
    ACTIONS(265), 4,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
  [784] = 1,
    ACTIONS(267), 4,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
  [791] = 1,
    ACTIONS(269), 4,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
  [798] = 1,
    ACTIONS(271), 4,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
  [805] = 1,
    ACTIONS(273), 4,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
  [812] = 4,
    ACTIONS(275), 1,
      anon_sym_SQUOTE,
    ACTIONS(277), 1,
      aux_sym_raw_token1,
    ACTIONS(279), 1,
      aux_sym_raw_token2,
    STATE(66), 1,
      aux_sym_raw_repeat1,
  [825] = 1,
    ACTIONS(281), 4,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
  [832] = 1,
    ACTIONS(283), 4,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_PIPE,
      anon_sym_RPAREN,
  [839] = 1,
    ACTIONS(285), 4,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
  [846] = 1,
    ACTIONS(135), 4,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_PIPE,
      anon_sym_RPAREN,
  [853] = 4,
    ACTIONS(233), 1,
      anon_sym_BSLASH,
    ACTIONS(287), 1,
      aux_sym_string_token1,
    ACTIONS(289), 1,
      sym__single_quote,
    STATE(63), 1,
      aux_sym_string_repeat1,
  [866] = 1,
    ACTIONS(291), 4,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
  [873] = 1,
    ACTIONS(293), 4,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
  [880] = 1,
    ACTIONS(155), 4,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
  [887] = 4,
    ACTIONS(295), 1,
      anon_sym_SQUOTE,
    ACTIONS(297), 1,
      aux_sym_raw_token1,
    ACTIONS(300), 1,
      aux_sym_raw_token2,
    STATE(86), 1,
      aux_sym_raw_repeat1,
  [900] = 1,
    ACTIONS(243), 3,
      aux_sym_string_token1,
      anon_sym_BSLASH,
      sym__single_quote,
  [906] = 2,
    ACTIONS(303), 1,
      anon_sym_SQUOTE,
    STATE(71), 1,
      sym_raw,
  [913] = 2,
    ACTIONS(303), 1,
      anon_sym_SQUOTE,
    STATE(73), 1,
      sym_raw,
  [920] = 2,
    ACTIONS(305), 1,
      aux_sym_whole_number_token1,
    STATE(46), 1,
      sym__whole_number,
  [927] = 2,
    ACTIONS(307), 1,
      aux_sym_whole_number_token1,
    STATE(74), 1,
      sym__whole_number,
  [934] = 1,
    ACTIONS(309), 1,
      aux_sym_string_token2,
  [938] = 1,
    ACTIONS(311), 1,
      sym__single_quote,
  [942] = 1,
    ACTIONS(313), 1,
      sym_quoted_field,
  [946] = 1,
    ACTIONS(315), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(17)] = 0,
  [SMALL_STATE(18)] = 28,
  [SMALL_STATE(19)] = 55,
  [SMALL_STATE(20)] = 82,
  [SMALL_STATE(21)] = 106,
  [SMALL_STATE(22)] = 124,
  [SMALL_STATE(23)] = 146,
  [SMALL_STATE(24)] = 164,
  [SMALL_STATE(25)] = 182,
  [SMALL_STATE(26)] = 200,
  [SMALL_STATE(27)] = 218,
  [SMALL_STATE(28)] = 236,
  [SMALL_STATE(29)] = 254,
  [SMALL_STATE(30)] = 272,
  [SMALL_STATE(31)] = 282,
  [SMALL_STATE(32)] = 292,
  [SMALL_STATE(33)] = 314,
  [SMALL_STATE(34)] = 332,
  [SMALL_STATE(35)] = 354,
  [SMALL_STATE(36)] = 364,
  [SMALL_STATE(37)] = 382,
  [SMALL_STATE(38)] = 395,
  [SMALL_STATE(39)] = 410,
  [SMALL_STATE(40)] = 423,
  [SMALL_STATE(41)] = 436,
  [SMALL_STATE(42)] = 449,
  [SMALL_STATE(43)] = 464,
  [SMALL_STATE(44)] = 479,
  [SMALL_STATE(45)] = 494,
  [SMALL_STATE(46)] = 509,
  [SMALL_STATE(47)] = 517,
  [SMALL_STATE(48)] = 525,
  [SMALL_STATE(49)] = 533,
  [SMALL_STATE(50)] = 541,
  [SMALL_STATE(51)] = 551,
  [SMALL_STATE(52)] = 561,
  [SMALL_STATE(53)] = 573,
  [SMALL_STATE(54)] = 585,
  [SMALL_STATE(55)] = 601,
  [SMALL_STATE(56)] = 613,
  [SMALL_STATE(57)] = 629,
  [SMALL_STATE(58)] = 637,
  [SMALL_STATE(59)] = 653,
  [SMALL_STATE(60)] = 665,
  [SMALL_STATE(61)] = 677,
  [SMALL_STATE(62)] = 689,
  [SMALL_STATE(63)] = 702,
  [SMALL_STATE(64)] = 715,
  [SMALL_STATE(65)] = 722,
  [SMALL_STATE(66)] = 729,
  [SMALL_STATE(67)] = 742,
  [SMALL_STATE(68)] = 749,
  [SMALL_STATE(69)] = 756,
  [SMALL_STATE(70)] = 763,
  [SMALL_STATE(71)] = 770,
  [SMALL_STATE(72)] = 777,
  [SMALL_STATE(73)] = 784,
  [SMALL_STATE(74)] = 791,
  [SMALL_STATE(75)] = 798,
  [SMALL_STATE(76)] = 805,
  [SMALL_STATE(77)] = 812,
  [SMALL_STATE(78)] = 825,
  [SMALL_STATE(79)] = 832,
  [SMALL_STATE(80)] = 839,
  [SMALL_STATE(81)] = 846,
  [SMALL_STATE(82)] = 853,
  [SMALL_STATE(83)] = 866,
  [SMALL_STATE(84)] = 873,
  [SMALL_STATE(85)] = 880,
  [SMALL_STATE(86)] = 887,
  [SMALL_STATE(87)] = 900,
  [SMALL_STATE(88)] = 906,
  [SMALL_STATE(89)] = 913,
  [SMALL_STATE(90)] = 920,
  [SMALL_STATE(91)] = 927,
  [SMALL_STATE(92)] = 934,
  [SMALL_STATE(93)] = 938,
  [SMALL_STATE(94)] = 942,
  [SMALL_STATE(95)] = 946,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exprs, 3),
  [25] = {.entry = {.count = 3, .reusable = true}}, REDUCE(aux_sym_ws_repeat1, 1), REDUCE(sym_exprs, 3), SHIFT(15),
  [29] = {.entry = {.count = 3, .reusable = true}}, REDUCE(aux_sym_ws_repeat1, 1), REDUCE(sym_exprs, 3), SHIFT(19),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_ws_repeat1, 1),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exprs, 2),
  [37] = {.entry = {.count = 3, .reusable = true}}, REDUCE(aux_sym_ws_repeat1, 1), REDUCE(sym_exprs, 2), SHIFT(15),
  [41] = {.entry = {.count = 3, .reusable = true}}, REDUCE(aux_sym_ws_repeat1, 1), REDUCE(sym_exprs, 2), SHIFT(19),
  [45] = {.entry = {.count = 3, .reusable = true}}, REDUCE(aux_sym_ws_repeat1, 1), REDUCE(sym_exprs, 3), SHIFT(14),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exprs, 4),
  [51] = {.entry = {.count = 3, .reusable = true}}, REDUCE(aux_sym_ws_repeat1, 1), REDUCE(sym_exprs, 4), SHIFT(14),
  [55] = {.entry = {.count = 3, .reusable = true}}, REDUCE(aux_sym_ws_repeat1, 1), REDUCE(sym_exprs, 4), SHIFT(19),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_exprs, 4), SHIFT(14),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_exprs, 3), SHIFT(15),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_exprs, 3), SHIFT(14),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_exprs, 2), SHIFT(15),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_ws_repeat1, 2),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_ws_repeat1, 2), SHIFT_REPEAT(17),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_ws_repeat1, 2),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_newline_repeat1, 2),
  [86] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_newline_repeat1, 2), SHIFT_REPEAT(18),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_newline_repeat1, 2),
  [91] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_ws_repeat1, 1), REDUCE(aux_sym_newline_repeat1, 2),
  [94] = {.entry = {.count = 3, .reusable = true}}, REDUCE(aux_sym_ws_repeat1, 1), REDUCE(aux_sym_newline_repeat1, 2), SHIFT(18),
  [98] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_ws_repeat1, 1), REDUCE(aux_sym_newline_repeat1, 2),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_target_query, 1),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exprs, 1),
  [113] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_exprs, 1), SHIFT(56),
  [116] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_exprs, 1), SHIFT(3),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [129] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_query_coalesce_repeat1, 2), SHIFT_REPEAT(55),
  [132] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_query_coalesce_repeat1, 2), SHIFT_REPEAT(21),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_query_coalesce_repeat1, 2),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_field, 3),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_target_query_prefix, 1),
  [147] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_exprs, 2), SHIFT(54),
  [150] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_exprs, 2), SHIFT(2),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_exprs_repeat1, 2),
  [157] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_exprs_repeat1, 2), SHIFT_REPEAT(58),
  [160] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_exprs_repeat1, 2), SHIFT_REPEAT(6),
  [163] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_exprs_repeat1, 2), SHIFT_REPEAT(13),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_field, 1),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_query_segments_repeat1, 2),
  [172] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_query_segments_repeat1, 2), SHIFT_REPEAT(42),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [177] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_ws_repeat1, 2), SHIFT_REPEAT(39),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_segments, 1),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_segments, 2),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__integer, 2),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_coalesce, 5),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_coalesce, 4),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_local_query, 1),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_integer, 1),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 2),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_coalesce, 6),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [224] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_newline_repeat1, 2), SHIFT_REPEAT(59),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 3),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [237] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(63),
  [240] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(92),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_exprs_repeat1, 3),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_raw, 2),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [253] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_target_query, 2),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_local_query, 3),
  [259] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_query_coalesce_repeat1, 4),
  [261] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_raw, 3),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_raw_string, 2),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_raw_regex, 2),
  [269] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 3),
  [271] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 1),
  [273] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query, 1),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [279] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [281] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_exprs_repeat1, 4),
  [283] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_query_coalesce_repeat1, 3),
  [285] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [291] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2),
  [293] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1),
  [295] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_raw_repeat1, 2),
  [297] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_raw_repeat1, 2), SHIFT_REPEAT(86),
  [300] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_raw_repeat1, 2), SHIFT_REPEAT(86),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [315] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_vrl(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
