#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 74
#define LARGE_STATE_COUNT 6
#define SYMBOL_COUNT 33
#define ALIAS_COUNT 0
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 1

enum {
  sym__horizontal_ws = 1,
  aux_sym_newline_token1 = 2,
  anon_sym_SEMI = 3,
  anon_sym_DASH = 4,
  aux_sym_whole_number_token1 = 5,
  anon_sym_DOT = 6,
  sym_local_variable = 7,
  sym__single_quote = 8,
  sym_quoted_field = 9,
  aux_sym_query_field_token1 = 10,
  anon_sym_LPAREN = 11,
  anon_sym_PIPE = 12,
  anon_sym_RPAREN = 13,
  sym_program = 14,
  sym_exprs = 15,
  sym_expr = 16,
  sym_literal = 17,
  sym__integer = 18,
  sym_integer = 19,
  sym__whole_number = 20,
  sym_float = 21,
  sym_query = 22,
  sym_local_query = 23,
  sym_query_segments = 24,
  sym__query_segment = 25,
  sym_query_field = 26,
  sym_query_coalesce = 27,
  aux_sym_newline_repeat1 = 28,
  aux_sym_ws_repeat1 = 29,
  aux_sym_exprs_repeat1 = 30,
  aux_sym_query_segments_repeat1 = 31,
  aux_sym_query_coalesce_repeat1 = 32,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__horizontal_ws] = "_horizontal_ws",
  [aux_sym_newline_token1] = "newline_token1",
  [anon_sym_SEMI] = ";",
  [anon_sym_DASH] = "-",
  [aux_sym_whole_number_token1] = "whole_number_token1",
  [anon_sym_DOT] = ".",
  [sym_local_variable] = "local_variable",
  [sym__single_quote] = "_single_quote",
  [sym_quoted_field] = "quoted_field",
  [aux_sym_query_field_token1] = "query_field_token1",
  [anon_sym_LPAREN] = "(",
  [anon_sym_PIPE] = "|",
  [anon_sym_RPAREN] = ")",
  [sym_program] = "program",
  [sym_exprs] = "exprs",
  [sym_expr] = "expr",
  [sym_literal] = "literal",
  [sym__integer] = "_integer",
  [sym_integer] = "integer",
  [sym__whole_number] = "_whole_number",
  [sym_float] = "float",
  [sym_query] = "query",
  [sym_local_query] = "local_query",
  [sym_query_segments] = "query_segments",
  [sym__query_segment] = "_query_segment",
  [sym_query_field] = "query_field",
  [sym_query_coalesce] = "query_coalesce",
  [aux_sym_newline_repeat1] = "newline_repeat1",
  [aux_sym_ws_repeat1] = "ws_repeat1",
  [aux_sym_exprs_repeat1] = "exprs_repeat1",
  [aux_sym_query_segments_repeat1] = "query_segments_repeat1",
  [aux_sym_query_coalesce_repeat1] = "query_coalesce_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__horizontal_ws] = sym__horizontal_ws,
  [aux_sym_newline_token1] = aux_sym_newline_token1,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_DASH] = anon_sym_DASH,
  [aux_sym_whole_number_token1] = aux_sym_whole_number_token1,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_local_variable] = sym_local_variable,
  [sym__single_quote] = sym__single_quote,
  [sym_quoted_field] = sym_quoted_field,
  [aux_sym_query_field_token1] = aux_sym_query_field_token1,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_program] = sym_program,
  [sym_exprs] = sym_exprs,
  [sym_expr] = sym_expr,
  [sym_literal] = sym_literal,
  [sym__integer] = sym__integer,
  [sym_integer] = sym_integer,
  [sym__whole_number] = sym__whole_number,
  [sym_float] = sym_float,
  [sym_query] = sym_query,
  [sym_local_query] = sym_local_query,
  [sym_query_segments] = sym_query_segments,
  [sym__query_segment] = sym__query_segment,
  [sym_query_field] = sym_query_field,
  [sym_query_coalesce] = sym_query_coalesce,
  [aux_sym_newline_repeat1] = aux_sym_newline_repeat1,
  [aux_sym_ws_repeat1] = aux_sym_ws_repeat1,
  [aux_sym_exprs_repeat1] = aux_sym_exprs_repeat1,
  [aux_sym_query_segments_repeat1] = aux_sym_query_segments_repeat1,
  [aux_sym_query_coalesce_repeat1] = aux_sym_query_coalesce_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__horizontal_ws] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_newline_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_whole_number_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_local_variable] = {
    .visible = true,
    .named = true,
  },
  [sym__single_quote] = {
    .visible = false,
    .named = true,
  },
  [sym_quoted_field] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_query_field_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym_exprs] = {
    .visible = true,
    .named = true,
  },
  [sym_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym__integer] = {
    .visible = false,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym__whole_number] = {
    .visible = false,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym_query] = {
    .visible = true,
    .named = true,
  },
  [sym_local_query] = {
    .visible = true,
    .named = true,
  },
  [sym_query_segments] = {
    .visible = true,
    .named = true,
  },
  [sym__query_segment] = {
    .visible = false,
    .named = true,
  },
  [sym_query_field] = {
    .visible = true,
    .named = true,
  },
  [sym_query_coalesce] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_newline_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_ws_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_exprs_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_query_segments_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_query_coalesce_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(5);
      if (lookahead == '\n') ADVANCE(7);
      if (lookahead == '"') ADVANCE(17);
      if (lookahead == '(') ADVANCE(21);
      if (lookahead == ')') ADVANCE(23);
      if (lookahead == '-') ADVANCE(9);
      if (lookahead == '.') ADVANCE(14);
      if (lookahead == ';') ADVANCE(8);
      if (lookahead == '@') ADVANCE(20);
      if (lookahead == '_') ADVANCE(11);
      if (lookahead == '|') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(7);
      if (lookahead == '"') ADVANCE(17);
      if (lookahead == '(') ADVANCE(21);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(3);
      if (('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 2:
      if (lookahead == '\\') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(18);
      END_STATE();
    case 3:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(3);
      if (('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 4:
      if (eof) ADVANCE(5);
      if (lookahead == '\n') ADVANCE(7);
      if (lookahead == ')') ADVANCE(23);
      if (lookahead == '-') ADVANCE(9);
      if (lookahead == ';') ADVANCE(8);
      if (lookahead == '_') ADVANCE(13);
      if (lookahead == '|') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym__horizontal_ws);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(6);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(aux_sym_newline_token1);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(aux_sym_whole_number_token1);
      if (lookahead == '@') ADVANCE(20);
      if (lookahead == '_') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym_whole_number_token1);
      if (lookahead == '@') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(11);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_whole_number_token1);
      if (lookahead == '_') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_whole_number_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(13);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_local_variable);
      if (lookahead == '@') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_local_variable);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym__single_quote);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_quoted_field);
      if (lookahead == '\\') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_quoted_field);
      if (lookahead != 0 &&
          lookahead != '\\') ADVANCE(18);
      if (lookahead == '\\') ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_query_field_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 4},
  [2] = {.lex_state = 4},
  [3] = {.lex_state = 4},
  [4] = {.lex_state = 4},
  [5] = {.lex_state = 4},
  [6] = {.lex_state = 4},
  [7] = {.lex_state = 4},
  [8] = {.lex_state = 4},
  [9] = {.lex_state = 4},
  [10] = {.lex_state = 4},
  [11] = {.lex_state = 4},
  [12] = {.lex_state = 4},
  [13] = {.lex_state = 4},
  [14] = {.lex_state = 4},
  [15] = {.lex_state = 4},
  [16] = {.lex_state = 4},
  [17] = {.lex_state = 4},
  [18] = {.lex_state = 4},
  [19] = {.lex_state = 4},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 4},
  [70] = {.lex_state = 4},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 2},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__horizontal_ws] = ACTIONS(1),
    [aux_sym_newline_token1] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [aux_sym_whole_number_token1] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_local_variable] = ACTIONS(1),
    [sym__single_quote] = ACTIONS(1),
    [aux_sym_query_field_token1] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
  },
  [1] = {
    [sym_program] = STATE(72),
    [sym_exprs] = STATE(44),
    [sym_expr] = STATE(21),
    [sym_literal] = STATE(66),
    [sym__integer] = STATE(52),
    [sym_integer] = STATE(64),
    [sym__whole_number] = STATE(52),
    [sym_float] = STATE(64),
    [sym_query] = STATE(66),
    [sym_local_query] = STATE(63),
    [aux_sym_newline_repeat1] = STATE(8),
    [aux_sym_ws_repeat1] = STATE(8),
    [sym__horizontal_ws] = ACTIONS(3),
    [aux_sym_newline_token1] = ACTIONS(3),
    [anon_sym_DASH] = ACTIONS(5),
    [aux_sym_whole_number_token1] = ACTIONS(7),
    [sym_local_variable] = ACTIONS(9),
  },
  [2] = {
    [sym_expr] = STATE(68),
    [sym_literal] = STATE(66),
    [sym__integer] = STATE(52),
    [sym_integer] = STATE(64),
    [sym__whole_number] = STATE(52),
    [sym_float] = STATE(64),
    [sym_query] = STATE(66),
    [sym_local_query] = STATE(63),
    [aux_sym_newline_repeat1] = STATE(19),
    [aux_sym_ws_repeat1] = STATE(13),
    [ts_builtin_sym_end] = ACTIONS(11),
    [sym__horizontal_ws] = ACTIONS(13),
    [aux_sym_newline_token1] = ACTIONS(17),
    [anon_sym_SEMI] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(5),
    [aux_sym_whole_number_token1] = ACTIONS(7),
    [sym_local_variable] = ACTIONS(9),
  },
  [3] = {
    [sym_expr] = STATE(60),
    [sym_literal] = STATE(66),
    [sym__integer] = STATE(52),
    [sym_integer] = STATE(64),
    [sym__whole_number] = STATE(52),
    [sym_float] = STATE(64),
    [sym_query] = STATE(66),
    [sym_local_query] = STATE(63),
    [aux_sym_newline_repeat1] = STATE(19),
    [aux_sym_ws_repeat1] = STATE(14),
    [ts_builtin_sym_end] = ACTIONS(23),
    [sym__horizontal_ws] = ACTIONS(25),
    [aux_sym_newline_token1] = ACTIONS(29),
    [anon_sym_SEMI] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(5),
    [aux_sym_whole_number_token1] = ACTIONS(7),
    [sym_local_variable] = ACTIONS(9),
  },
  [4] = {
    [sym_expr] = STATE(68),
    [sym_literal] = STATE(66),
    [sym__integer] = STATE(52),
    [sym_integer] = STATE(64),
    [sym__whole_number] = STATE(52),
    [sym_float] = STATE(64),
    [sym_query] = STATE(66),
    [sym_local_query] = STATE(63),
    [aux_sym_newline_repeat1] = STATE(19),
    [aux_sym_ws_repeat1] = STATE(13),
    [ts_builtin_sym_end] = ACTIONS(33),
    [sym__horizontal_ws] = ACTIONS(35),
    [aux_sym_newline_token1] = ACTIONS(39),
    [anon_sym_SEMI] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(5),
    [aux_sym_whole_number_token1] = ACTIONS(7),
    [sym_local_variable] = ACTIONS(9),
  },
  [5] = {
    [sym_expr] = STATE(60),
    [sym_literal] = STATE(66),
    [sym__integer] = STATE(52),
    [sym_integer] = STATE(64),
    [sym__whole_number] = STATE(52),
    [sym_float] = STATE(64),
    [sym_query] = STATE(66),
    [sym_local_query] = STATE(63),
    [aux_sym_newline_repeat1] = STATE(19),
    [aux_sym_ws_repeat1] = STATE(14),
    [ts_builtin_sym_end] = ACTIONS(33),
    [sym__horizontal_ws] = ACTIONS(43),
    [aux_sym_newline_token1] = ACTIONS(39),
    [anon_sym_SEMI] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(5),
    [aux_sym_whole_number_token1] = ACTIONS(7),
    [sym_local_variable] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(5), 1,
      anon_sym_DASH,
    ACTIONS(7), 1,
      aux_sym_whole_number_token1,
    ACTIONS(9), 1,
      sym_local_variable,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    STATE(63), 1,
      sym_local_query,
    STATE(68), 1,
      sym_expr,
    ACTIONS(47), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(13), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
    STATE(52), 2,
      sym__integer,
      sym__whole_number,
    STATE(64), 2,
      sym_integer,
      sym_float,
    STATE(66), 2,
      sym_literal,
      sym_query,
  [39] = 11,
    ACTIONS(5), 1,
      anon_sym_DASH,
    ACTIONS(7), 1,
      aux_sym_whole_number_token1,
    ACTIONS(9), 1,
      sym_local_variable,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    STATE(60), 1,
      sym_expr,
    STATE(63), 1,
      sym_local_query,
    ACTIONS(50), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(14), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
    STATE(52), 2,
      sym__integer,
      sym__whole_number,
    STATE(64), 2,
      sym_integer,
      sym_float,
    STATE(66), 2,
      sym_literal,
      sym_query,
  [78] = 11,
    ACTIONS(5), 1,
      anon_sym_DASH,
    ACTIONS(7), 1,
      aux_sym_whole_number_token1,
    ACTIONS(9), 1,
      sym_local_variable,
    STATE(21), 1,
      sym_expr,
    STATE(51), 1,
      sym_exprs,
    STATE(63), 1,
      sym_local_query,
    ACTIONS(53), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(17), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
    STATE(52), 2,
      sym__integer,
      sym__whole_number,
    STATE(64), 2,
      sym_integer,
      sym_float,
    STATE(66), 2,
      sym_literal,
      sym_query,
  [117] = 11,
    ACTIONS(5), 1,
      anon_sym_DASH,
    ACTIONS(7), 1,
      aux_sym_whole_number_token1,
    ACTIONS(9), 1,
      sym_local_variable,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    STATE(60), 1,
      sym_expr,
    STATE(63), 1,
      sym_local_query,
    ACTIONS(55), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(14), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
    STATE(52), 2,
      sym__integer,
      sym__whole_number,
    STATE(64), 2,
      sym_integer,
      sym_float,
    STATE(66), 2,
      sym_literal,
      sym_query,
  [156] = 11,
    ACTIONS(5), 1,
      anon_sym_DASH,
    ACTIONS(7), 1,
      aux_sym_whole_number_token1,
    ACTIONS(9), 1,
      sym_local_variable,
    STATE(14), 1,
      aux_sym_ws_repeat1,
    STATE(19), 1,
      aux_sym_newline_repeat1,
    STATE(60), 1,
      sym_expr,
    STATE(63), 1,
      sym_local_query,
    STATE(52), 2,
      sym__integer,
      sym__whole_number,
    STATE(64), 2,
      sym_integer,
      sym_float,
    STATE(66), 2,
      sym_literal,
      sym_query,
    ACTIONS(21), 3,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
  [195] = 11,
    ACTIONS(5), 1,
      anon_sym_DASH,
    ACTIONS(7), 1,
      aux_sym_whole_number_token1,
    ACTIONS(9), 1,
      sym_local_variable,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    STATE(63), 1,
      sym_local_query,
    STATE(68), 1,
      sym_expr,
    ACTIONS(58), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(13), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
    STATE(52), 2,
      sym__integer,
      sym__whole_number,
    STATE(64), 2,
      sym_integer,
      sym_float,
    STATE(66), 2,
      sym_literal,
      sym_query,
  [234] = 11,
    ACTIONS(5), 1,
      anon_sym_DASH,
    ACTIONS(7), 1,
      aux_sym_whole_number_token1,
    ACTIONS(9), 1,
      sym_local_variable,
    STATE(13), 1,
      aux_sym_ws_repeat1,
    STATE(19), 1,
      aux_sym_newline_repeat1,
    STATE(63), 1,
      sym_local_query,
    STATE(68), 1,
      sym_expr,
    STATE(52), 2,
      sym__integer,
      sym__whole_number,
    STATE(64), 2,
      sym_integer,
      sym_float,
    STATE(66), 2,
      sym_literal,
      sym_query,
    ACTIONS(21), 3,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
  [273] = 10,
    ACTIONS(5), 1,
      anon_sym_DASH,
    ACTIONS(7), 1,
      aux_sym_whole_number_token1,
    ACTIONS(9), 1,
      sym_local_variable,
    STATE(60), 1,
      sym_expr,
    STATE(63), 1,
      sym_local_query,
    ACTIONS(53), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(17), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
    STATE(52), 2,
      sym__integer,
      sym__whole_number,
    STATE(64), 2,
      sym_integer,
      sym_float,
    STATE(66), 2,
      sym_literal,
      sym_query,
  [309] = 10,
    ACTIONS(5), 1,
      anon_sym_DASH,
    ACTIONS(7), 1,
      aux_sym_whole_number_token1,
    ACTIONS(9), 1,
      sym_local_variable,
    STATE(61), 1,
      sym_expr,
    STATE(63), 1,
      sym_local_query,
    ACTIONS(53), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(17), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
    STATE(52), 2,
      sym__integer,
      sym__whole_number,
    STATE(64), 2,
      sym_integer,
      sym_float,
    STATE(66), 2,
      sym_literal,
      sym_query,
  [345] = 10,
    ACTIONS(5), 1,
      anon_sym_DASH,
    ACTIONS(7), 1,
      aux_sym_whole_number_token1,
    ACTIONS(9), 1,
      sym_local_variable,
    STATE(60), 1,
      sym_expr,
    STATE(63), 1,
      sym_local_query,
    ACTIONS(61), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(14), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
    STATE(52), 2,
      sym__integer,
      sym__whole_number,
    STATE(64), 2,
      sym_integer,
      sym_float,
    STATE(66), 2,
      sym_literal,
      sym_query,
  [381] = 10,
    ACTIONS(5), 1,
      anon_sym_DASH,
    ACTIONS(7), 1,
      aux_sym_whole_number_token1,
    ACTIONS(9), 1,
      sym_local_variable,
    STATE(63), 1,
      sym_local_query,
    STATE(68), 1,
      sym_expr,
    ACTIONS(63), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(13), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
    STATE(52), 2,
      sym__integer,
      sym__whole_number,
    STATE(64), 2,
      sym_integer,
      sym_float,
    STATE(66), 2,
      sym_literal,
      sym_query,
  [417] = 4,
    ACTIONS(67), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    ACTIONS(70), 2,
      aux_sym_whole_number_token1,
      sym_local_variable,
    STATE(17), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
    ACTIONS(65), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_PIPE,
      anon_sym_RPAREN,
  [437] = 4,
    ACTIONS(74), 1,
      aux_sym_newline_token1,
    STATE(18), 1,
      aux_sym_newline_repeat1,
    ACTIONS(77), 2,
      aux_sym_whole_number_token1,
      sym_local_variable,
    ACTIONS(72), 6,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_PIPE,
      anon_sym_RPAREN,
  [456] = 5,
    ACTIONS(82), 1,
      aux_sym_newline_token1,
    STATE(18), 1,
      aux_sym_newline_repeat1,
    ACTIONS(72), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
    ACTIONS(79), 2,
      sym__horizontal_ws,
      anon_sym_DASH,
    ACTIONS(86), 2,
      aux_sym_whole_number_token1,
      sym_local_variable,
  [475] = 1,
    ACTIONS(89), 7,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_PIPE,
      anon_sym_RPAREN,
  [485] = 7,
    ACTIONS(91), 1,
      ts_builtin_sym_end,
    ACTIONS(93), 1,
      sym__horizontal_ws,
    ACTIONS(96), 1,
      aux_sym_newline_token1,
    ACTIONS(99), 1,
      anon_sym_SEMI,
    STATE(2), 1,
      aux_sym_newline_repeat1,
    STATE(23), 1,
      aux_sym_exprs_repeat1,
    STATE(45), 1,
      aux_sym_ws_repeat1,
  [507] = 5,
    ACTIONS(103), 1,
      sym__single_quote,
    ACTIONS(105), 1,
      aux_sym_query_field_token1,
    STATE(67), 1,
      sym_query_field,
    ACTIONS(101), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(37), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [525] = 7,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    ACTIONS(107), 1,
      sym__horizontal_ws,
    ACTIONS(110), 1,
      aux_sym_newline_token1,
    ACTIONS(113), 1,
      anon_sym_SEMI,
    STATE(4), 1,
      aux_sym_newline_repeat1,
    STATE(24), 1,
      aux_sym_exprs_repeat1,
    STATE(57), 1,
      aux_sym_ws_repeat1,
  [547] = 7,
    ACTIONS(115), 1,
      ts_builtin_sym_end,
    ACTIONS(117), 1,
      sym__horizontal_ws,
    ACTIONS(120), 1,
      aux_sym_newline_token1,
    ACTIONS(123), 1,
      anon_sym_SEMI,
    STATE(12), 1,
      aux_sym_newline_repeat1,
    STATE(24), 1,
      aux_sym_exprs_repeat1,
    STATE(50), 1,
      aux_sym_ws_repeat1,
  [569] = 5,
    ACTIONS(103), 1,
      sym__single_quote,
    ACTIONS(105), 1,
      aux_sym_query_field_token1,
    STATE(59), 1,
      sym_query_field,
    ACTIONS(126), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(30), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [587] = 1,
    ACTIONS(128), 7,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_PIPE,
      anon_sym_RPAREN,
  [597] = 5,
    ACTIONS(103), 1,
      sym__single_quote,
    ACTIONS(105), 1,
      aux_sym_query_field_token1,
    STATE(42), 1,
      sym_query_field,
    ACTIONS(130), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(34), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [615] = 4,
    ACTIONS(134), 1,
      anon_sym_DOT,
    STATE(41), 1,
      aux_sym_query_segments_repeat1,
    STATE(58), 1,
      sym_query_segments,
    ACTIONS(132), 4,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
  [631] = 5,
    ACTIONS(138), 1,
      anon_sym_PIPE,
    ACTIONS(140), 1,
      anon_sym_RPAREN,
    STATE(32), 1,
      aux_sym_query_coalesce_repeat1,
    ACTIONS(136), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(39), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [649] = 5,
    ACTIONS(103), 1,
      sym__single_quote,
    ACTIONS(105), 1,
      aux_sym_query_field_token1,
    STATE(65), 1,
      sym_query_field,
    ACTIONS(101), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(37), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [667] = 5,
    ACTIONS(103), 1,
      sym__single_quote,
    ACTIONS(105), 1,
      aux_sym_query_field_token1,
    STATE(65), 1,
      sym_query_field,
    ACTIONS(142), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(22), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [685] = 5,
    ACTIONS(147), 1,
      anon_sym_PIPE,
    ACTIONS(150), 1,
      anon_sym_RPAREN,
    STATE(32), 1,
      aux_sym_query_coalesce_repeat1,
    ACTIONS(144), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(53), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [703] = 5,
    ACTIONS(138), 1,
      anon_sym_PIPE,
    ACTIONS(154), 1,
      anon_sym_RPAREN,
    STATE(32), 1,
      aux_sym_query_coalesce_repeat1,
    ACTIONS(152), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(38), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [721] = 5,
    ACTIONS(103), 1,
      sym__single_quote,
    ACTIONS(105), 1,
      aux_sym_query_field_token1,
    STATE(35), 1,
      sym_query_field,
    ACTIONS(101), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(37), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [739] = 4,
    ACTIONS(138), 1,
      anon_sym_PIPE,
    STATE(33), 1,
      aux_sym_query_coalesce_repeat1,
    ACTIONS(156), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(53), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [754] = 3,
    ACTIONS(160), 1,
      anon_sym_DOT,
    STATE(36), 1,
      aux_sym_query_segments_repeat1,
    ACTIONS(158), 4,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
  [767] = 3,
    ACTIONS(65), 2,
      sym__single_quote,
      aux_sym_query_field_token1,
    ACTIONS(163), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(37), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [780] = 4,
    ACTIONS(166), 1,
      anon_sym_PIPE,
    ACTIONS(168), 1,
      anon_sym_RPAREN,
    ACTIONS(53), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(17), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [795] = 4,
    ACTIONS(154), 1,
      anon_sym_RPAREN,
    ACTIONS(166), 1,
      anon_sym_PIPE,
    ACTIONS(53), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(17), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [810] = 4,
    ACTIONS(103), 1,
      sym__single_quote,
    ACTIONS(105), 1,
      aux_sym_query_field_token1,
    ACTIONS(170), 1,
      anon_sym_LPAREN,
    STATE(48), 3,
      sym__query_segment,
      sym_query_field,
      sym_query_coalesce,
  [825] = 3,
    ACTIONS(134), 1,
      anon_sym_DOT,
    STATE(36), 1,
      aux_sym_query_segments_repeat1,
    ACTIONS(172), 4,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
  [838] = 4,
    ACTIONS(138), 1,
      anon_sym_PIPE,
    STATE(29), 1,
      aux_sym_query_coalesce_repeat1,
    ACTIONS(156), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(53), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [853] = 3,
    ACTIONS(174), 1,
      ts_builtin_sym_end,
    ACTIONS(53), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(17), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [865] = 3,
    ACTIONS(176), 1,
      ts_builtin_sym_end,
    ACTIONS(178), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(43), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [877] = 5,
    ACTIONS(53), 1,
      sym__horizontal_ws,
    ACTIONS(180), 1,
      aux_sym_newline_token1,
    ACTIONS(182), 1,
      anon_sym_SEMI,
    STATE(5), 1,
      aux_sym_newline_repeat1,
    STATE(17), 1,
      aux_sym_ws_repeat1,
  [893] = 3,
    ACTIONS(184), 1,
      aux_sym_newline_token1,
    STATE(46), 1,
      aux_sym_newline_repeat1,
    ACTIONS(72), 3,
      sym__horizontal_ws,
      sym__single_quote,
      aux_sym_query_field_token1,
  [905] = 1,
    ACTIONS(187), 5,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
      anon_sym_DOT,
  [913] = 1,
    ACTIONS(158), 5,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
      anon_sym_DOT,
  [921] = 1,
    ACTIONS(189), 5,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
      anon_sym_DOT,
  [929] = 5,
    ACTIONS(53), 1,
      sym__horizontal_ws,
    ACTIONS(191), 1,
      aux_sym_newline_token1,
    ACTIONS(193), 1,
      anon_sym_SEMI,
    STATE(10), 1,
      aux_sym_newline_repeat1,
    STATE(17), 1,
      aux_sym_ws_repeat1,
  [945] = 3,
    ACTIONS(174), 1,
      ts_builtin_sym_end,
    ACTIONS(195), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(55), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [957] = 2,
    ACTIONS(199), 1,
      anon_sym_DOT,
    ACTIONS(197), 4,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
  [967] = 3,
    ACTIONS(166), 1,
      anon_sym_PIPE,
    ACTIONS(53), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(17), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [979] = 1,
    ACTIONS(201), 5,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
      anon_sym_DOT,
  [987] = 3,
    ACTIONS(203), 1,
      ts_builtin_sym_end,
    ACTIONS(53), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(17), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [999] = 1,
    ACTIONS(205), 5,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
      anon_sym_DOT,
  [1007] = 5,
    ACTIONS(53), 1,
      sym__horizontal_ws,
    ACTIONS(207), 1,
      aux_sym_newline_token1,
    ACTIONS(209), 1,
      anon_sym_SEMI,
    STATE(3), 1,
      aux_sym_newline_repeat1,
    STATE(17), 1,
      aux_sym_ws_repeat1,
  [1023] = 1,
    ACTIONS(211), 4,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
  [1030] = 1,
    ACTIONS(150), 4,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_PIPE,
      anon_sym_RPAREN,
  [1037] = 1,
    ACTIONS(213), 4,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
  [1044] = 1,
    ACTIONS(215), 4,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
  [1051] = 1,
    ACTIONS(217), 4,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
  [1058] = 1,
    ACTIONS(219), 4,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
  [1065] = 1,
    ACTIONS(221), 4,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
  [1072] = 1,
    ACTIONS(223), 4,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_PIPE,
      anon_sym_RPAREN,
  [1079] = 1,
    ACTIONS(225), 4,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
  [1086] = 1,
    ACTIONS(227), 4,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_PIPE,
      anon_sym_RPAREN,
  [1093] = 1,
    ACTIONS(115), 4,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
  [1100] = 2,
    ACTIONS(229), 1,
      aux_sym_whole_number_token1,
    STATE(62), 1,
      sym__whole_number,
  [1107] = 2,
    ACTIONS(231), 1,
      aux_sym_whole_number_token1,
    STATE(56), 1,
      sym__whole_number,
  [1114] = 1,
    ACTIONS(233), 1,
      sym__single_quote,
  [1118] = 1,
    ACTIONS(235), 1,
      ts_builtin_sym_end,
  [1122] = 1,
    ACTIONS(237), 1,
      sym_quoted_field,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(6)] = 0,
  [SMALL_STATE(7)] = 39,
  [SMALL_STATE(8)] = 78,
  [SMALL_STATE(9)] = 117,
  [SMALL_STATE(10)] = 156,
  [SMALL_STATE(11)] = 195,
  [SMALL_STATE(12)] = 234,
  [SMALL_STATE(13)] = 273,
  [SMALL_STATE(14)] = 309,
  [SMALL_STATE(15)] = 345,
  [SMALL_STATE(16)] = 381,
  [SMALL_STATE(17)] = 417,
  [SMALL_STATE(18)] = 437,
  [SMALL_STATE(19)] = 456,
  [SMALL_STATE(20)] = 475,
  [SMALL_STATE(21)] = 485,
  [SMALL_STATE(22)] = 507,
  [SMALL_STATE(23)] = 525,
  [SMALL_STATE(24)] = 547,
  [SMALL_STATE(25)] = 569,
  [SMALL_STATE(26)] = 587,
  [SMALL_STATE(27)] = 597,
  [SMALL_STATE(28)] = 615,
  [SMALL_STATE(29)] = 631,
  [SMALL_STATE(30)] = 649,
  [SMALL_STATE(31)] = 667,
  [SMALL_STATE(32)] = 685,
  [SMALL_STATE(33)] = 703,
  [SMALL_STATE(34)] = 721,
  [SMALL_STATE(35)] = 739,
  [SMALL_STATE(36)] = 754,
  [SMALL_STATE(37)] = 767,
  [SMALL_STATE(38)] = 780,
  [SMALL_STATE(39)] = 795,
  [SMALL_STATE(40)] = 810,
  [SMALL_STATE(41)] = 825,
  [SMALL_STATE(42)] = 838,
  [SMALL_STATE(43)] = 853,
  [SMALL_STATE(44)] = 865,
  [SMALL_STATE(45)] = 877,
  [SMALL_STATE(46)] = 893,
  [SMALL_STATE(47)] = 905,
  [SMALL_STATE(48)] = 913,
  [SMALL_STATE(49)] = 921,
  [SMALL_STATE(50)] = 929,
  [SMALL_STATE(51)] = 945,
  [SMALL_STATE(52)] = 957,
  [SMALL_STATE(53)] = 967,
  [SMALL_STATE(54)] = 979,
  [SMALL_STATE(55)] = 987,
  [SMALL_STATE(56)] = 999,
  [SMALL_STATE(57)] = 1007,
  [SMALL_STATE(58)] = 1023,
  [SMALL_STATE(59)] = 1030,
  [SMALL_STATE(60)] = 1037,
  [SMALL_STATE(61)] = 1044,
  [SMALL_STATE(62)] = 1051,
  [SMALL_STATE(63)] = 1058,
  [SMALL_STATE(64)] = 1065,
  [SMALL_STATE(65)] = 1072,
  [SMALL_STATE(66)] = 1079,
  [SMALL_STATE(67)] = 1086,
  [SMALL_STATE(68)] = 1093,
  [SMALL_STATE(69)] = 1100,
  [SMALL_STATE(70)] = 1107,
  [SMALL_STATE(71)] = 1114,
  [SMALL_STATE(72)] = 1118,
  [SMALL_STATE(73)] = 1122,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exprs, 2),
  [13] = {.entry = {.count = 3, .reusable = true}}, REDUCE(aux_sym_ws_repeat1, 1), REDUCE(sym_exprs, 2), SHIFT(13),
  [17] = {.entry = {.count = 3, .reusable = true}}, REDUCE(aux_sym_ws_repeat1, 1), REDUCE(sym_exprs, 2), SHIFT(19),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_ws_repeat1, 1),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exprs, 4),
  [25] = {.entry = {.count = 3, .reusable = true}}, REDUCE(aux_sym_ws_repeat1, 1), REDUCE(sym_exprs, 4), SHIFT(14),
  [29] = {.entry = {.count = 3, .reusable = true}}, REDUCE(aux_sym_ws_repeat1, 1), REDUCE(sym_exprs, 4), SHIFT(19),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exprs, 3),
  [35] = {.entry = {.count = 3, .reusable = true}}, REDUCE(aux_sym_ws_repeat1, 1), REDUCE(sym_exprs, 3), SHIFT(13),
  [39] = {.entry = {.count = 3, .reusable = true}}, REDUCE(aux_sym_ws_repeat1, 1), REDUCE(sym_exprs, 3), SHIFT(19),
  [43] = {.entry = {.count = 3, .reusable = true}}, REDUCE(aux_sym_ws_repeat1, 1), REDUCE(sym_exprs, 3), SHIFT(14),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_exprs, 3), SHIFT(13),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_exprs, 3), SHIFT(14),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_exprs, 4), SHIFT(14),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_exprs, 2), SHIFT(13),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_ws_repeat1, 2),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_ws_repeat1, 2), SHIFT_REPEAT(17),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_ws_repeat1, 2),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_newline_repeat1, 2),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_newline_repeat1, 2), SHIFT_REPEAT(18),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_newline_repeat1, 2),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_ws_repeat1, 1), REDUCE(aux_sym_newline_repeat1, 2),
  [82] = {.entry = {.count = 3, .reusable = true}}, REDUCE(aux_sym_ws_repeat1, 1), REDUCE(aux_sym_newline_repeat1, 2), SHIFT(18),
  [86] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_ws_repeat1, 1), REDUCE(aux_sym_newline_repeat1, 2),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_field, 3),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exprs, 1),
  [93] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_exprs, 1), SHIFT(45),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_exprs, 1), SHIFT(2),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_exprs, 2), SHIFT(57),
  [110] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_exprs, 2), SHIFT(4),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_exprs_repeat1, 2),
  [117] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_exprs_repeat1, 2), SHIFT_REPEAT(50),
  [120] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_exprs_repeat1, 2), SHIFT_REPEAT(12),
  [123] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_exprs_repeat1, 2), SHIFT_REPEAT(16),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_field, 1),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_local_query, 1),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [144] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_query_coalesce_repeat1, 2), SHIFT_REPEAT(53),
  [147] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_query_coalesce_repeat1, 2), SHIFT_REPEAT(25),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_query_coalesce_repeat1, 2),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_query_segments_repeat1, 2),
  [160] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_query_segments_repeat1, 2), SHIFT_REPEAT(40),
  [163] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_ws_repeat1, 2), SHIFT_REPEAT(37),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_segments, 1),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 2),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [184] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_newline_repeat1, 2), SHIFT_REPEAT(46),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_coalesce, 6),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_coalesce, 5),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_integer, 1),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_coalesce, 4),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 3),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__integer, 2),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_local_query, 2),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_exprs_repeat1, 3),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_exprs_repeat1, 4),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 3),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query, 1),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_query_coalesce_repeat1, 3),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 1),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_query_coalesce_repeat1, 4),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [235] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_vrl(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
