#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 117
#define LARGE_STATE_COUNT 21
#define SYMBOL_COUNT 61
#define ALIAS_COUNT 0
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 1

enum {
  sym__horizontal_ws = 1,
  aux_sym_newline_token1 = 2,
  anon_sym_SEMI = 3,
  anon_sym_LPAREN = 4,
  anon_sym_RPAREN = 5,
  anon_sym_LBRACE = 6,
  anon_sym_RBRACE = 7,
  sym_null = 8,
  aux_sym_string_token1 = 9,
  anon_sym_BSLASH = 10,
  aux_sym_string_token2 = 11,
  anon_sym_true = 12,
  anon_sym_false = 13,
  anon_sym_s = 14,
  anon_sym_r = 15,
  anon_sym_t = 16,
  anon_sym_SQUOTE = 17,
  aux_sym_raw_token1 = 18,
  aux_sym_raw_token2 = 19,
  anon_sym_DASH = 20,
  aux_sym_whole_number_token1 = 21,
  anon_sym_DOT = 22,
  sym_local_variable = 23,
  sym__single_quote = 24,
  sym_quoted_field = 25,
  aux_sym_query_field_token1 = 26,
  anon_sym_PIPE = 27,
  anon_sym_PERCENT = 28,
  sym_program = 29,
  sym_exprs = 30,
  sym_expr = 31,
  sym_literal = 32,
  sym_container = 33,
  sym_group = 34,
  sym_block = 35,
  sym_string = 36,
  sym_boolean = 37,
  sym_raw_string = 38,
  sym_regex = 39,
  sym_timestamp = 40,
  sym_raw = 41,
  sym__integer = 42,
  sym_integer = 43,
  sym__whole_number = 44,
  sym_float = 45,
  sym_query = 46,
  sym_local_query = 47,
  sym_query_segments = 48,
  sym__query_segment = 49,
  sym_query_field = 50,
  sym_query_coalesce = 51,
  sym_target_query = 52,
  sym_target_query_prefix = 53,
  aux_sym_newline_repeat1 = 54,
  aux_sym_ws_repeat1 = 55,
  aux_sym_exprs_repeat1 = 56,
  aux_sym_string_repeat1 = 57,
  aux_sym_raw_repeat1 = 58,
  aux_sym_query_segments_repeat1 = 59,
  aux_sym_query_coalesce_repeat1 = 60,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__horizontal_ws] = "_horizontal_ws",
  [aux_sym_newline_token1] = "newline_token1",
  [anon_sym_SEMI] = ";",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_null] = "null",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_BSLASH] = "\\",
  [aux_sym_string_token2] = "string_token2",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_s] = "s",
  [anon_sym_r] = "r",
  [anon_sym_t] = "t",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_raw_token1] = "raw_token1",
  [aux_sym_raw_token2] = "raw_token2",
  [anon_sym_DASH] = "-",
  [aux_sym_whole_number_token1] = "whole_number_token1",
  [anon_sym_DOT] = ".",
  [sym_local_variable] = "local_variable",
  [sym__single_quote] = "_single_quote",
  [sym_quoted_field] = "quoted_field",
  [aux_sym_query_field_token1] = "query_field_token1",
  [anon_sym_PIPE] = "|",
  [anon_sym_PERCENT] = "%",
  [sym_program] = "program",
  [sym_exprs] = "exprs",
  [sym_expr] = "expr",
  [sym_literal] = "literal",
  [sym_container] = "container",
  [sym_group] = "group",
  [sym_block] = "block",
  [sym_string] = "string",
  [sym_boolean] = "boolean",
  [sym_raw_string] = "raw_string",
  [sym_regex] = "regex",
  [sym_timestamp] = "timestamp",
  [sym_raw] = "raw",
  [sym__integer] = "_integer",
  [sym_integer] = "integer",
  [sym__whole_number] = "_whole_number",
  [sym_float] = "float",
  [sym_query] = "query",
  [sym_local_query] = "local_query",
  [sym_query_segments] = "query_segments",
  [sym__query_segment] = "_query_segment",
  [sym_query_field] = "query_field",
  [sym_query_coalesce] = "query_coalesce",
  [sym_target_query] = "target_query",
  [sym_target_query_prefix] = "target_query_prefix",
  [aux_sym_newline_repeat1] = "newline_repeat1",
  [aux_sym_ws_repeat1] = "ws_repeat1",
  [aux_sym_exprs_repeat1] = "exprs_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_raw_repeat1] = "raw_repeat1",
  [aux_sym_query_segments_repeat1] = "query_segments_repeat1",
  [aux_sym_query_coalesce_repeat1] = "query_coalesce_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__horizontal_ws] = sym__horizontal_ws,
  [aux_sym_newline_token1] = aux_sym_newline_token1,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_null] = sym_null,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_s] = anon_sym_s,
  [anon_sym_r] = anon_sym_r,
  [anon_sym_t] = anon_sym_t,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_raw_token1] = aux_sym_raw_token1,
  [aux_sym_raw_token2] = aux_sym_raw_token2,
  [anon_sym_DASH] = anon_sym_DASH,
  [aux_sym_whole_number_token1] = aux_sym_whole_number_token1,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_local_variable] = sym_local_variable,
  [sym__single_quote] = sym__single_quote,
  [sym_quoted_field] = sym_quoted_field,
  [aux_sym_query_field_token1] = aux_sym_query_field_token1,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [sym_program] = sym_program,
  [sym_exprs] = sym_exprs,
  [sym_expr] = sym_expr,
  [sym_literal] = sym_literal,
  [sym_container] = sym_container,
  [sym_group] = sym_group,
  [sym_block] = sym_block,
  [sym_string] = sym_string,
  [sym_boolean] = sym_boolean,
  [sym_raw_string] = sym_raw_string,
  [sym_regex] = sym_regex,
  [sym_timestamp] = sym_timestamp,
  [sym_raw] = sym_raw,
  [sym__integer] = sym__integer,
  [sym_integer] = sym_integer,
  [sym__whole_number] = sym__whole_number,
  [sym_float] = sym_float,
  [sym_query] = sym_query,
  [sym_local_query] = sym_local_query,
  [sym_query_segments] = sym_query_segments,
  [sym__query_segment] = sym__query_segment,
  [sym_query_field] = sym_query_field,
  [sym_query_coalesce] = sym_query_coalesce,
  [sym_target_query] = sym_target_query,
  [sym_target_query_prefix] = sym_target_query_prefix,
  [aux_sym_newline_repeat1] = aux_sym_newline_repeat1,
  [aux_sym_ws_repeat1] = aux_sym_ws_repeat1,
  [aux_sym_exprs_repeat1] = aux_sym_exprs_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_raw_repeat1] = aux_sym_raw_repeat1,
  [aux_sym_query_segments_repeat1] = aux_sym_query_segments_repeat1,
  [aux_sym_query_coalesce_repeat1] = aux_sym_query_coalesce_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__horizontal_ws] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_newline_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_s] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_r] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_t] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_raw_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_raw_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_whole_number_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_local_variable] = {
    .visible = true,
    .named = true,
  },
  [sym__single_quote] = {
    .visible = false,
    .named = true,
  },
  [sym_quoted_field] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_query_field_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym_exprs] = {
    .visible = true,
    .named = true,
  },
  [sym_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_container] = {
    .visible = true,
    .named = true,
  },
  [sym_group] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_string] = {
    .visible = true,
    .named = true,
  },
  [sym_regex] = {
    .visible = true,
    .named = true,
  },
  [sym_timestamp] = {
    .visible = true,
    .named = true,
  },
  [sym_raw] = {
    .visible = true,
    .named = true,
  },
  [sym__integer] = {
    .visible = false,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym__whole_number] = {
    .visible = false,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym_query] = {
    .visible = true,
    .named = true,
  },
  [sym_local_query] = {
    .visible = true,
    .named = true,
  },
  [sym_query_segments] = {
    .visible = true,
    .named = true,
  },
  [sym__query_segment] = {
    .visible = false,
    .named = true,
  },
  [sym_query_field] = {
    .visible = true,
    .named = true,
  },
  [sym_query_coalesce] = {
    .visible = true,
    .named = true,
  },
  [sym_target_query] = {
    .visible = true,
    .named = true,
  },
  [sym_target_query_prefix] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_newline_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_ws_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_exprs_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_raw_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_query_segments_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_query_coalesce_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(9);
      if (lookahead == '\n') ADVANCE(11);
      if (lookahead == '"') ADVANCE(46);
      if (lookahead == '%') ADVANCE(51);
      if (lookahead == '\'') ADVANCE(29);
      if (lookahead == '(') ADVANCE(13);
      if (lookahead == ')') ADVANCE(14);
      if (lookahead == '-') ADVANCE(32);
      if (lookahead == '.') ADVANCE(35);
      if (lookahead == ';') ADVANCE(12);
      if (lookahead == '\\') ADVANCE(19);
      if (lookahead == 'n') ADVANCE(18);
      if (lookahead == 'r') ADVANCE(25);
      if (lookahead == 's') ADVANCE(23);
      if (lookahead == 't') ADVANCE(27);
      if (lookahead == '{') ADVANCE(15);
      if (lookahead == '|') ADVANCE(50);
      if (lookahead == '}') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(10);
      if (lookahead != 0) ADVANCE(18);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(46);
      if (lookahead == '\\') ADVANCE(19);
      if (lookahead != 0) ADVANCE(18);
      END_STATE();
    case 2:
      if (lookahead == '\'') ADVANCE(29);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead != 0) ADVANCE(31);
      END_STATE();
    case 3:
      if (lookahead == '\\') ADVANCE(48);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(47);
      END_STATE();
    case 4:
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(20);
      END_STATE();
    case 5:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(5);
      if (('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 6:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(30);
      END_STATE();
    case 7:
      if (eof) ADVANCE(9);
      if (lookahead == '\n') ADVANCE(11);
      if (lookahead == '"') ADVANCE(46);
      if (lookahead == '%') ADVANCE(51);
      if (lookahead == '\'') ADVANCE(29);
      if (lookahead == '(') ADVANCE(13);
      if (lookahead == ')') ADVANCE(14);
      if (lookahead == '-') ADVANCE(32);
      if (lookahead == '.') ADVANCE(35);
      if (lookahead == ';') ADVANCE(12);
      if (lookahead == '_') ADVANCE(34);
      if (lookahead == 'f') ADVANCE(36);
      if (lookahead == 'n') ADVANCE(44);
      if (lookahead == 'r') ADVANCE(26);
      if (lookahead == 's') ADVANCE(24);
      if (lookahead == 't') ADVANCE(28);
      if (lookahead == '{') ADVANCE(15);
      if (lookahead == '|') ADVANCE(50);
      if (lookahead == '}') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 8:
      if (eof) ADVANCE(9);
      if (lookahead == '\n') ADVANCE(11);
      if (lookahead == '"') ADVANCE(46);
      if (lookahead == '(') ADVANCE(13);
      if (lookahead == ')') ADVANCE(14);
      if (lookahead == ';') ADVANCE(12);
      if (lookahead == '}') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(5);
      if (('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym__horizontal_ws);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym_newline_token1);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_null);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_string_token1);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_string_token2);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_s);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_s);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_r);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_r);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_t);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_t);
      if (lookahead == 'r') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_raw_token1);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_raw_token2);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_whole_number_token1);
      if (lookahead == '_') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_whole_number_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(34);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_local_variable);
      if (lookahead == 'a') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_local_variable);
      if (lookahead == 'e') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_local_variable);
      if (lookahead == 'e') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_local_variable);
      if (lookahead == 'l') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_local_variable);
      if (lookahead == 'l') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_local_variable);
      if (lookahead == 'l') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_local_variable);
      if (lookahead == 's') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_local_variable);
      if (lookahead == 'u') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_local_variable);
      if (lookahead == 'u') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_local_variable);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym__single_quote);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_quoted_field);
      if (lookahead == '\\') ADVANCE(48);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_quoted_field);
      if (lookahead != 0 &&
          lookahead != '\\') ADVANCE(47);
      if (lookahead == '\\') ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_query_field_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 7},
  [2] = {.lex_state = 7},
  [3] = {.lex_state = 7},
  [4] = {.lex_state = 7},
  [5] = {.lex_state = 7},
  [6] = {.lex_state = 7},
  [7] = {.lex_state = 7},
  [8] = {.lex_state = 7},
  [9] = {.lex_state = 7},
  [10] = {.lex_state = 7},
  [11] = {.lex_state = 7},
  [12] = {.lex_state = 7},
  [13] = {.lex_state = 7},
  [14] = {.lex_state = 7},
  [15] = {.lex_state = 7},
  [16] = {.lex_state = 7},
  [17] = {.lex_state = 7},
  [18] = {.lex_state = 7},
  [19] = {.lex_state = 7},
  [20] = {.lex_state = 7},
  [21] = {.lex_state = 7},
  [22] = {.lex_state = 7},
  [23] = {.lex_state = 7},
  [24] = {.lex_state = 8},
  [25] = {.lex_state = 8},
  [26] = {.lex_state = 7},
  [27] = {.lex_state = 7},
  [28] = {.lex_state = 7},
  [29] = {.lex_state = 7},
  [30] = {.lex_state = 7},
  [31] = {.lex_state = 7},
  [32] = {.lex_state = 7},
  [33] = {.lex_state = 7},
  [34] = {.lex_state = 7},
  [35] = {.lex_state = 8},
  [36] = {.lex_state = 7},
  [37] = {.lex_state = 7},
  [38] = {.lex_state = 8},
  [39] = {.lex_state = 7},
  [40] = {.lex_state = 8},
  [41] = {.lex_state = 8},
  [42] = {.lex_state = 7},
  [43] = {.lex_state = 8},
  [44] = {.lex_state = 8},
  [45] = {.lex_state = 8},
  [46] = {.lex_state = 7},
  [47] = {.lex_state = 7},
  [48] = {.lex_state = 7},
  [49] = {.lex_state = 7},
  [50] = {.lex_state = 7},
  [51] = {.lex_state = 7},
  [52] = {.lex_state = 7},
  [53] = {.lex_state = 8},
  [54] = {.lex_state = 7},
  [55] = {.lex_state = 7},
  [56] = {.lex_state = 7},
  [57] = {.lex_state = 7},
  [58] = {.lex_state = 7},
  [59] = {.lex_state = 7},
  [60] = {.lex_state = 7},
  [61] = {.lex_state = 7},
  [62] = {.lex_state = 7},
  [63] = {.lex_state = 7},
  [64] = {.lex_state = 7},
  [65] = {.lex_state = 7},
  [66] = {.lex_state = 7},
  [67] = {.lex_state = 7},
  [68] = {.lex_state = 7},
  [69] = {.lex_state = 7},
  [70] = {.lex_state = 7},
  [71] = {.lex_state = 7},
  [72] = {.lex_state = 7},
  [73] = {.lex_state = 7},
  [74] = {.lex_state = 8},
  [75] = {.lex_state = 7},
  [76] = {.lex_state = 7},
  [77] = {.lex_state = 7},
  [78] = {.lex_state = 7},
  [79] = {.lex_state = 7},
  [80] = {.lex_state = 7},
  [81] = {.lex_state = 7},
  [82] = {.lex_state = 7},
  [83] = {.lex_state = 7},
  [84] = {.lex_state = 7},
  [85] = {.lex_state = 8},
  [86] = {.lex_state = 7},
  [87] = {.lex_state = 7},
  [88] = {.lex_state = 7},
  [89] = {.lex_state = 7},
  [90] = {.lex_state = 7},
  [91] = {.lex_state = 7},
  [92] = {.lex_state = 7},
  [93] = {.lex_state = 7},
  [94] = {.lex_state = 7},
  [95] = {.lex_state = 7},
  [96] = {.lex_state = 7},
  [97] = {.lex_state = 7},
  [98] = {.lex_state = 2},
  [99] = {.lex_state = 7},
  [100] = {.lex_state = 1},
  [101] = {.lex_state = 1},
  [102] = {.lex_state = 7},
  [103] = {.lex_state = 7},
  [104] = {.lex_state = 2},
  [105] = {.lex_state = 1},
  [106] = {.lex_state = 2},
  [107] = {.lex_state = 1},
  [108] = {.lex_state = 7},
  [109] = {.lex_state = 7},
  [110] = {.lex_state = 7},
  [111] = {.lex_state = 7},
  [112] = {.lex_state = 7},
  [113] = {.lex_state = 3},
  [114] = {.lex_state = 7},
  [115] = {.lex_state = 4},
  [116] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__horizontal_ws] = ACTIONS(1),
    [aux_sym_newline_token1] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [aux_sym_string_token1] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [aux_sym_string_token2] = ACTIONS(1),
    [anon_sym_s] = ACTIONS(1),
    [anon_sym_r] = ACTIONS(1),
    [anon_sym_t] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [aux_sym_raw_token2] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym__single_quote] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
  },
  [1] = {
    [sym_program] = STATE(116),
    [sym_exprs] = STATE(87),
    [sym_expr] = STATE(33),
    [sym_literal] = STATE(60),
    [sym_container] = STATE(60),
    [sym_group] = STATE(61),
    [sym_block] = STATE(61),
    [sym_string] = STATE(62),
    [sym_boolean] = STATE(62),
    [sym_raw_string] = STATE(62),
    [sym_regex] = STATE(62),
    [sym_timestamp] = STATE(62),
    [sym__integer] = STATE(48),
    [sym_integer] = STATE(62),
    [sym__whole_number] = STATE(48),
    [sym_float] = STATE(62),
    [sym_query] = STATE(60),
    [sym_local_query] = STATE(66),
    [sym_target_query] = STATE(66),
    [sym_target_query_prefix] = STATE(24),
    [aux_sym_newline_repeat1] = STATE(10),
    [aux_sym_ws_repeat1] = STATE(10),
    [sym__horizontal_ws] = ACTIONS(3),
    [aux_sym_newline_token1] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [sym_null] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_s] = ACTIONS(13),
    [anon_sym_r] = ACTIONS(15),
    [anon_sym_t] = ACTIONS(17),
    [anon_sym_DASH] = ACTIONS(19),
    [aux_sym_whole_number_token1] = ACTIONS(21),
    [anon_sym_DOT] = ACTIONS(23),
    [sym_local_variable] = ACTIONS(25),
    [sym__single_quote] = ACTIONS(27),
    [anon_sym_PERCENT] = ACTIONS(23),
  },
  [2] = {
    [sym_expr] = STATE(83),
    [sym_literal] = STATE(60),
    [sym_container] = STATE(60),
    [sym_group] = STATE(61),
    [sym_block] = STATE(61),
    [sym_string] = STATE(62),
    [sym_boolean] = STATE(62),
    [sym_raw_string] = STATE(62),
    [sym_regex] = STATE(62),
    [sym_timestamp] = STATE(62),
    [sym__integer] = STATE(48),
    [sym_integer] = STATE(62),
    [sym__whole_number] = STATE(48),
    [sym_float] = STATE(62),
    [sym_query] = STATE(60),
    [sym_local_query] = STATE(66),
    [sym_target_query] = STATE(66),
    [sym_target_query_prefix] = STATE(24),
    [aux_sym_newline_repeat1] = STATE(23),
    [aux_sym_ws_repeat1] = STATE(18),
    [ts_builtin_sym_end] = ACTIONS(29),
    [sym__horizontal_ws] = ACTIONS(31),
    [aux_sym_newline_token1] = ACTIONS(35),
    [anon_sym_SEMI] = ACTIONS(39),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(29),
    [sym_null] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_s] = ACTIONS(13),
    [anon_sym_r] = ACTIONS(15),
    [anon_sym_t] = ACTIONS(17),
    [anon_sym_DASH] = ACTIONS(19),
    [aux_sym_whole_number_token1] = ACTIONS(21),
    [anon_sym_DOT] = ACTIONS(23),
    [sym_local_variable] = ACTIONS(25),
    [sym__single_quote] = ACTIONS(27),
    [anon_sym_PERCENT] = ACTIONS(23),
  },
  [3] = {
    [sym_expr] = STATE(90),
    [sym_literal] = STATE(60),
    [sym_container] = STATE(60),
    [sym_group] = STATE(61),
    [sym_block] = STATE(61),
    [sym_string] = STATE(62),
    [sym_boolean] = STATE(62),
    [sym_raw_string] = STATE(62),
    [sym_regex] = STATE(62),
    [sym_timestamp] = STATE(62),
    [sym__integer] = STATE(48),
    [sym_integer] = STATE(62),
    [sym__whole_number] = STATE(48),
    [sym_float] = STATE(62),
    [sym_query] = STATE(60),
    [sym_local_query] = STATE(66),
    [sym_target_query] = STATE(66),
    [sym_target_query_prefix] = STATE(24),
    [aux_sym_newline_repeat1] = STATE(23),
    [aux_sym_ws_repeat1] = STATE(20),
    [ts_builtin_sym_end] = ACTIONS(29),
    [sym__horizontal_ws] = ACTIONS(41),
    [aux_sym_newline_token1] = ACTIONS(35),
    [anon_sym_SEMI] = ACTIONS(39),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(29),
    [sym_null] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_s] = ACTIONS(13),
    [anon_sym_r] = ACTIONS(15),
    [anon_sym_t] = ACTIONS(17),
    [anon_sym_DASH] = ACTIONS(19),
    [aux_sym_whole_number_token1] = ACTIONS(21),
    [anon_sym_DOT] = ACTIONS(23),
    [sym_local_variable] = ACTIONS(25),
    [sym__single_quote] = ACTIONS(27),
    [anon_sym_PERCENT] = ACTIONS(23),
  },
  [4] = {
    [sym_expr] = STATE(90),
    [sym_literal] = STATE(60),
    [sym_container] = STATE(60),
    [sym_group] = STATE(61),
    [sym_block] = STATE(61),
    [sym_string] = STATE(62),
    [sym_boolean] = STATE(62),
    [sym_raw_string] = STATE(62),
    [sym_regex] = STATE(62),
    [sym_timestamp] = STATE(62),
    [sym__integer] = STATE(48),
    [sym_integer] = STATE(62),
    [sym__whole_number] = STATE(48),
    [sym_float] = STATE(62),
    [sym_query] = STATE(60),
    [sym_local_query] = STATE(66),
    [sym_target_query] = STATE(66),
    [sym_target_query_prefix] = STATE(24),
    [aux_sym_newline_repeat1] = STATE(23),
    [aux_sym_ws_repeat1] = STATE(20),
    [ts_builtin_sym_end] = ACTIONS(45),
    [sym__horizontal_ws] = ACTIONS(47),
    [aux_sym_newline_token1] = ACTIONS(51),
    [anon_sym_SEMI] = ACTIONS(39),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(45),
    [sym_null] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_s] = ACTIONS(13),
    [anon_sym_r] = ACTIONS(15),
    [anon_sym_t] = ACTIONS(17),
    [anon_sym_DASH] = ACTIONS(19),
    [aux_sym_whole_number_token1] = ACTIONS(21),
    [anon_sym_DOT] = ACTIONS(23),
    [sym_local_variable] = ACTIONS(25),
    [sym__single_quote] = ACTIONS(27),
    [anon_sym_PERCENT] = ACTIONS(23),
  },
  [5] = {
    [sym_expr] = STATE(83),
    [sym_literal] = STATE(60),
    [sym_container] = STATE(60),
    [sym_group] = STATE(61),
    [sym_block] = STATE(61),
    [sym_string] = STATE(62),
    [sym_boolean] = STATE(62),
    [sym_raw_string] = STATE(62),
    [sym_regex] = STATE(62),
    [sym_timestamp] = STATE(62),
    [sym__integer] = STATE(48),
    [sym_integer] = STATE(62),
    [sym__whole_number] = STATE(48),
    [sym_float] = STATE(62),
    [sym_query] = STATE(60),
    [sym_local_query] = STATE(66),
    [sym_target_query] = STATE(66),
    [sym_target_query_prefix] = STATE(24),
    [aux_sym_newline_repeat1] = STATE(23),
    [aux_sym_ws_repeat1] = STATE(18),
    [ts_builtin_sym_end] = ACTIONS(55),
    [sym__horizontal_ws] = ACTIONS(57),
    [aux_sym_newline_token1] = ACTIONS(61),
    [anon_sym_SEMI] = ACTIONS(39),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(55),
    [sym_null] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_s] = ACTIONS(13),
    [anon_sym_r] = ACTIONS(15),
    [anon_sym_t] = ACTIONS(17),
    [anon_sym_DASH] = ACTIONS(19),
    [aux_sym_whole_number_token1] = ACTIONS(21),
    [anon_sym_DOT] = ACTIONS(23),
    [sym_local_variable] = ACTIONS(25),
    [sym__single_quote] = ACTIONS(27),
    [anon_sym_PERCENT] = ACTIONS(23),
  },
  [6] = {
    [sym_expr] = STATE(83),
    [sym_literal] = STATE(60),
    [sym_container] = STATE(60),
    [sym_group] = STATE(61),
    [sym_block] = STATE(61),
    [sym_string] = STATE(62),
    [sym_boolean] = STATE(62),
    [sym_raw_string] = STATE(62),
    [sym_regex] = STATE(62),
    [sym_timestamp] = STATE(62),
    [sym__integer] = STATE(48),
    [sym_integer] = STATE(62),
    [sym__whole_number] = STATE(48),
    [sym_float] = STATE(62),
    [sym_query] = STATE(60),
    [sym_local_query] = STATE(66),
    [sym_target_query] = STATE(66),
    [sym_target_query_prefix] = STATE(24),
    [aux_sym_newline_repeat1] = STATE(18),
    [aux_sym_ws_repeat1] = STATE(18),
    [ts_builtin_sym_end] = ACTIONS(29),
    [sym__horizontal_ws] = ACTIONS(65),
    [aux_sym_newline_token1] = ACTIONS(65),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(29),
    [sym_null] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_s] = ACTIONS(13),
    [anon_sym_r] = ACTIONS(15),
    [anon_sym_t] = ACTIONS(17),
    [anon_sym_DASH] = ACTIONS(19),
    [aux_sym_whole_number_token1] = ACTIONS(21),
    [anon_sym_DOT] = ACTIONS(23),
    [sym_local_variable] = ACTIONS(25),
    [sym__single_quote] = ACTIONS(27),
    [anon_sym_PERCENT] = ACTIONS(23),
  },
  [7] = {
    [sym_expr] = STATE(90),
    [sym_literal] = STATE(60),
    [sym_container] = STATE(60),
    [sym_group] = STATE(61),
    [sym_block] = STATE(61),
    [sym_string] = STATE(62),
    [sym_boolean] = STATE(62),
    [sym_raw_string] = STATE(62),
    [sym_regex] = STATE(62),
    [sym_timestamp] = STATE(62),
    [sym__integer] = STATE(48),
    [sym_integer] = STATE(62),
    [sym__whole_number] = STATE(48),
    [sym_float] = STATE(62),
    [sym_query] = STATE(60),
    [sym_local_query] = STATE(66),
    [sym_target_query] = STATE(66),
    [sym_target_query_prefix] = STATE(24),
    [aux_sym_newline_repeat1] = STATE(20),
    [aux_sym_ws_repeat1] = STATE(20),
    [ts_builtin_sym_end] = ACTIONS(29),
    [sym__horizontal_ws] = ACTIONS(68),
    [aux_sym_newline_token1] = ACTIONS(68),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(29),
    [sym_null] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_s] = ACTIONS(13),
    [anon_sym_r] = ACTIONS(15),
    [anon_sym_t] = ACTIONS(17),
    [anon_sym_DASH] = ACTIONS(19),
    [aux_sym_whole_number_token1] = ACTIONS(21),
    [anon_sym_DOT] = ACTIONS(23),
    [sym_local_variable] = ACTIONS(25),
    [sym__single_quote] = ACTIONS(27),
    [anon_sym_PERCENT] = ACTIONS(23),
  },
  [8] = {
    [sym_expr] = STATE(90),
    [sym_literal] = STATE(60),
    [sym_container] = STATE(60),
    [sym_group] = STATE(61),
    [sym_block] = STATE(61),
    [sym_string] = STATE(62),
    [sym_boolean] = STATE(62),
    [sym_raw_string] = STATE(62),
    [sym_regex] = STATE(62),
    [sym_timestamp] = STATE(62),
    [sym__integer] = STATE(48),
    [sym_integer] = STATE(62),
    [sym__whole_number] = STATE(48),
    [sym_float] = STATE(62),
    [sym_query] = STATE(60),
    [sym_local_query] = STATE(66),
    [sym_target_query] = STATE(66),
    [sym_target_query_prefix] = STATE(24),
    [aux_sym_newline_repeat1] = STATE(20),
    [aux_sym_ws_repeat1] = STATE(20),
    [ts_builtin_sym_end] = ACTIONS(45),
    [sym__horizontal_ws] = ACTIONS(71),
    [aux_sym_newline_token1] = ACTIONS(71),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(45),
    [sym_null] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_s] = ACTIONS(13),
    [anon_sym_r] = ACTIONS(15),
    [anon_sym_t] = ACTIONS(17),
    [anon_sym_DASH] = ACTIONS(19),
    [aux_sym_whole_number_token1] = ACTIONS(21),
    [anon_sym_DOT] = ACTIONS(23),
    [sym_local_variable] = ACTIONS(25),
    [sym__single_quote] = ACTIONS(27),
    [anon_sym_PERCENT] = ACTIONS(23),
  },
  [9] = {
    [sym_expr] = STATE(83),
    [sym_literal] = STATE(60),
    [sym_container] = STATE(60),
    [sym_group] = STATE(61),
    [sym_block] = STATE(61),
    [sym_string] = STATE(62),
    [sym_boolean] = STATE(62),
    [sym_raw_string] = STATE(62),
    [sym_regex] = STATE(62),
    [sym_timestamp] = STATE(62),
    [sym__integer] = STATE(48),
    [sym_integer] = STATE(62),
    [sym__whole_number] = STATE(48),
    [sym_float] = STATE(62),
    [sym_query] = STATE(60),
    [sym_local_query] = STATE(66),
    [sym_target_query] = STATE(66),
    [sym_target_query_prefix] = STATE(24),
    [aux_sym_newline_repeat1] = STATE(18),
    [aux_sym_ws_repeat1] = STATE(18),
    [ts_builtin_sym_end] = ACTIONS(55),
    [sym__horizontal_ws] = ACTIONS(74),
    [aux_sym_newline_token1] = ACTIONS(74),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(55),
    [sym_null] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_s] = ACTIONS(13),
    [anon_sym_r] = ACTIONS(15),
    [anon_sym_t] = ACTIONS(17),
    [anon_sym_DASH] = ACTIONS(19),
    [aux_sym_whole_number_token1] = ACTIONS(21),
    [anon_sym_DOT] = ACTIONS(23),
    [sym_local_variable] = ACTIONS(25),
    [sym__single_quote] = ACTIONS(27),
    [anon_sym_PERCENT] = ACTIONS(23),
  },
  [10] = {
    [sym_exprs] = STATE(79),
    [sym_expr] = STATE(33),
    [sym_literal] = STATE(60),
    [sym_container] = STATE(60),
    [sym_group] = STATE(61),
    [sym_block] = STATE(61),
    [sym_string] = STATE(62),
    [sym_boolean] = STATE(62),
    [sym_raw_string] = STATE(62),
    [sym_regex] = STATE(62),
    [sym_timestamp] = STATE(62),
    [sym__integer] = STATE(48),
    [sym_integer] = STATE(62),
    [sym__whole_number] = STATE(48),
    [sym_float] = STATE(62),
    [sym_query] = STATE(60),
    [sym_local_query] = STATE(66),
    [sym_target_query] = STATE(66),
    [sym_target_query_prefix] = STATE(24),
    [aux_sym_newline_repeat1] = STATE(21),
    [aux_sym_ws_repeat1] = STATE(21),
    [sym__horizontal_ws] = ACTIONS(77),
    [aux_sym_newline_token1] = ACTIONS(77),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [sym_null] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_s] = ACTIONS(13),
    [anon_sym_r] = ACTIONS(15),
    [anon_sym_t] = ACTIONS(17),
    [anon_sym_DASH] = ACTIONS(19),
    [aux_sym_whole_number_token1] = ACTIONS(21),
    [anon_sym_DOT] = ACTIONS(23),
    [sym_local_variable] = ACTIONS(25),
    [sym__single_quote] = ACTIONS(27),
    [anon_sym_PERCENT] = ACTIONS(23),
  },
  [11] = {
    [sym_exprs] = STATE(94),
    [sym_expr] = STATE(33),
    [sym_literal] = STATE(60),
    [sym_container] = STATE(60),
    [sym_group] = STATE(61),
    [sym_block] = STATE(61),
    [sym_string] = STATE(62),
    [sym_boolean] = STATE(62),
    [sym_raw_string] = STATE(62),
    [sym_regex] = STATE(62),
    [sym_timestamp] = STATE(62),
    [sym__integer] = STATE(48),
    [sym_integer] = STATE(62),
    [sym__whole_number] = STATE(48),
    [sym_float] = STATE(62),
    [sym_query] = STATE(60),
    [sym_local_query] = STATE(66),
    [sym_target_query] = STATE(66),
    [sym_target_query_prefix] = STATE(24),
    [aux_sym_newline_repeat1] = STATE(13),
    [aux_sym_ws_repeat1] = STATE(13),
    [sym__horizontal_ws] = ACTIONS(79),
    [aux_sym_newline_token1] = ACTIONS(79),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [sym_null] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_s] = ACTIONS(13),
    [anon_sym_r] = ACTIONS(15),
    [anon_sym_t] = ACTIONS(17),
    [anon_sym_DASH] = ACTIONS(19),
    [aux_sym_whole_number_token1] = ACTIONS(21),
    [anon_sym_DOT] = ACTIONS(23),
    [sym_local_variable] = ACTIONS(25),
    [sym__single_quote] = ACTIONS(27),
    [anon_sym_PERCENT] = ACTIONS(23),
  },
  [12] = {
    [sym_expr] = STATE(90),
    [sym_literal] = STATE(60),
    [sym_container] = STATE(60),
    [sym_group] = STATE(61),
    [sym_block] = STATE(61),
    [sym_string] = STATE(62),
    [sym_boolean] = STATE(62),
    [sym_raw_string] = STATE(62),
    [sym_regex] = STATE(62),
    [sym_timestamp] = STATE(62),
    [sym__integer] = STATE(48),
    [sym_integer] = STATE(62),
    [sym__whole_number] = STATE(48),
    [sym_float] = STATE(62),
    [sym_query] = STATE(60),
    [sym_local_query] = STATE(66),
    [sym_target_query] = STATE(66),
    [sym_target_query_prefix] = STATE(24),
    [aux_sym_newline_repeat1] = STATE(23),
    [aux_sym_ws_repeat1] = STATE(20),
    [sym__horizontal_ws] = ACTIONS(39),
    [aux_sym_newline_token1] = ACTIONS(39),
    [anon_sym_SEMI] = ACTIONS(39),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [sym_null] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_s] = ACTIONS(13),
    [anon_sym_r] = ACTIONS(15),
    [anon_sym_t] = ACTIONS(17),
    [anon_sym_DASH] = ACTIONS(19),
    [aux_sym_whole_number_token1] = ACTIONS(21),
    [anon_sym_DOT] = ACTIONS(23),
    [sym_local_variable] = ACTIONS(25),
    [sym__single_quote] = ACTIONS(27),
    [anon_sym_PERCENT] = ACTIONS(23),
  },
  [13] = {
    [sym_exprs] = STATE(82),
    [sym_expr] = STATE(33),
    [sym_literal] = STATE(60),
    [sym_container] = STATE(60),
    [sym_group] = STATE(61),
    [sym_block] = STATE(61),
    [sym_string] = STATE(62),
    [sym_boolean] = STATE(62),
    [sym_raw_string] = STATE(62),
    [sym_regex] = STATE(62),
    [sym_timestamp] = STATE(62),
    [sym__integer] = STATE(48),
    [sym_integer] = STATE(62),
    [sym__whole_number] = STATE(48),
    [sym_float] = STATE(62),
    [sym_query] = STATE(60),
    [sym_local_query] = STATE(66),
    [sym_target_query] = STATE(66),
    [sym_target_query_prefix] = STATE(24),
    [aux_sym_newline_repeat1] = STATE(21),
    [aux_sym_ws_repeat1] = STATE(21),
    [sym__horizontal_ws] = ACTIONS(77),
    [aux_sym_newline_token1] = ACTIONS(77),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [sym_null] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_s] = ACTIONS(13),
    [anon_sym_r] = ACTIONS(15),
    [anon_sym_t] = ACTIONS(17),
    [anon_sym_DASH] = ACTIONS(19),
    [aux_sym_whole_number_token1] = ACTIONS(21),
    [anon_sym_DOT] = ACTIONS(23),
    [sym_local_variable] = ACTIONS(25),
    [sym__single_quote] = ACTIONS(27),
    [anon_sym_PERCENT] = ACTIONS(23),
  },
  [14] = {
    [sym_expr] = STATE(83),
    [sym_literal] = STATE(60),
    [sym_container] = STATE(60),
    [sym_group] = STATE(61),
    [sym_block] = STATE(61),
    [sym_string] = STATE(62),
    [sym_boolean] = STATE(62),
    [sym_raw_string] = STATE(62),
    [sym_regex] = STATE(62),
    [sym_timestamp] = STATE(62),
    [sym__integer] = STATE(48),
    [sym_integer] = STATE(62),
    [sym__whole_number] = STATE(48),
    [sym_float] = STATE(62),
    [sym_query] = STATE(60),
    [sym_local_query] = STATE(66),
    [sym_target_query] = STATE(66),
    [sym_target_query_prefix] = STATE(24),
    [aux_sym_newline_repeat1] = STATE(23),
    [aux_sym_ws_repeat1] = STATE(18),
    [sym__horizontal_ws] = ACTIONS(39),
    [aux_sym_newline_token1] = ACTIONS(39),
    [anon_sym_SEMI] = ACTIONS(39),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [sym_null] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_s] = ACTIONS(13),
    [anon_sym_r] = ACTIONS(15),
    [anon_sym_t] = ACTIONS(17),
    [anon_sym_DASH] = ACTIONS(19),
    [aux_sym_whole_number_token1] = ACTIONS(21),
    [anon_sym_DOT] = ACTIONS(23),
    [sym_local_variable] = ACTIONS(25),
    [sym__single_quote] = ACTIONS(27),
    [anon_sym_PERCENT] = ACTIONS(23),
  },
  [15] = {
    [sym_expr] = STATE(92),
    [sym_literal] = STATE(60),
    [sym_container] = STATE(60),
    [sym_group] = STATE(61),
    [sym_block] = STATE(61),
    [sym_string] = STATE(62),
    [sym_boolean] = STATE(62),
    [sym_raw_string] = STATE(62),
    [sym_regex] = STATE(62),
    [sym_timestamp] = STATE(62),
    [sym__integer] = STATE(48),
    [sym_integer] = STATE(62),
    [sym__whole_number] = STATE(48),
    [sym_float] = STATE(62),
    [sym_query] = STATE(60),
    [sym_local_query] = STATE(66),
    [sym_target_query] = STATE(66),
    [sym_target_query_prefix] = STATE(24),
    [aux_sym_newline_repeat1] = STATE(21),
    [aux_sym_ws_repeat1] = STATE(21),
    [sym__horizontal_ws] = ACTIONS(77),
    [aux_sym_newline_token1] = ACTIONS(77),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [sym_null] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_s] = ACTIONS(13),
    [anon_sym_r] = ACTIONS(15),
    [anon_sym_t] = ACTIONS(17),
    [anon_sym_DASH] = ACTIONS(19),
    [aux_sym_whole_number_token1] = ACTIONS(21),
    [anon_sym_DOT] = ACTIONS(23),
    [sym_local_variable] = ACTIONS(25),
    [sym__single_quote] = ACTIONS(27),
    [anon_sym_PERCENT] = ACTIONS(23),
  },
  [16] = {
    [sym_expr] = STATE(90),
    [sym_literal] = STATE(60),
    [sym_container] = STATE(60),
    [sym_group] = STATE(61),
    [sym_block] = STATE(61),
    [sym_string] = STATE(62),
    [sym_boolean] = STATE(62),
    [sym_raw_string] = STATE(62),
    [sym_regex] = STATE(62),
    [sym_timestamp] = STATE(62),
    [sym__integer] = STATE(48),
    [sym_integer] = STATE(62),
    [sym__whole_number] = STATE(48),
    [sym_float] = STATE(62),
    [sym_query] = STATE(60),
    [sym_local_query] = STATE(66),
    [sym_target_query] = STATE(66),
    [sym_target_query_prefix] = STATE(24),
    [aux_sym_newline_repeat1] = STATE(20),
    [aux_sym_ws_repeat1] = STATE(20),
    [sym__horizontal_ws] = ACTIONS(81),
    [aux_sym_newline_token1] = ACTIONS(81),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [sym_null] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_s] = ACTIONS(13),
    [anon_sym_r] = ACTIONS(15),
    [anon_sym_t] = ACTIONS(17),
    [anon_sym_DASH] = ACTIONS(19),
    [aux_sym_whole_number_token1] = ACTIONS(21),
    [anon_sym_DOT] = ACTIONS(23),
    [sym_local_variable] = ACTIONS(25),
    [sym__single_quote] = ACTIONS(27),
    [anon_sym_PERCENT] = ACTIONS(23),
  },
  [17] = {
    [sym_expr] = STATE(83),
    [sym_literal] = STATE(60),
    [sym_container] = STATE(60),
    [sym_group] = STATE(61),
    [sym_block] = STATE(61),
    [sym_string] = STATE(62),
    [sym_boolean] = STATE(62),
    [sym_raw_string] = STATE(62),
    [sym_regex] = STATE(62),
    [sym_timestamp] = STATE(62),
    [sym__integer] = STATE(48),
    [sym_integer] = STATE(62),
    [sym__whole_number] = STATE(48),
    [sym_float] = STATE(62),
    [sym_query] = STATE(60),
    [sym_local_query] = STATE(66),
    [sym_target_query] = STATE(66),
    [sym_target_query_prefix] = STATE(24),
    [aux_sym_newline_repeat1] = STATE(18),
    [aux_sym_ws_repeat1] = STATE(18),
    [sym__horizontal_ws] = ACTIONS(83),
    [aux_sym_newline_token1] = ACTIONS(83),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [sym_null] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_s] = ACTIONS(13),
    [anon_sym_r] = ACTIONS(15),
    [anon_sym_t] = ACTIONS(17),
    [anon_sym_DASH] = ACTIONS(19),
    [aux_sym_whole_number_token1] = ACTIONS(21),
    [anon_sym_DOT] = ACTIONS(23),
    [sym_local_variable] = ACTIONS(25),
    [sym__single_quote] = ACTIONS(27),
    [anon_sym_PERCENT] = ACTIONS(23),
  },
  [18] = {
    [sym_expr] = STATE(93),
    [sym_literal] = STATE(60),
    [sym_container] = STATE(60),
    [sym_group] = STATE(61),
    [sym_block] = STATE(61),
    [sym_string] = STATE(62),
    [sym_boolean] = STATE(62),
    [sym_raw_string] = STATE(62),
    [sym_regex] = STATE(62),
    [sym_timestamp] = STATE(62),
    [sym__integer] = STATE(48),
    [sym_integer] = STATE(62),
    [sym__whole_number] = STATE(48),
    [sym_float] = STATE(62),
    [sym_query] = STATE(60),
    [sym_local_query] = STATE(66),
    [sym_target_query] = STATE(66),
    [sym_target_query_prefix] = STATE(24),
    [aux_sym_newline_repeat1] = STATE(21),
    [aux_sym_ws_repeat1] = STATE(21),
    [sym__horizontal_ws] = ACTIONS(77),
    [aux_sym_newline_token1] = ACTIONS(77),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [sym_null] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_s] = ACTIONS(13),
    [anon_sym_r] = ACTIONS(15),
    [anon_sym_t] = ACTIONS(17),
    [anon_sym_DASH] = ACTIONS(19),
    [aux_sym_whole_number_token1] = ACTIONS(21),
    [anon_sym_DOT] = ACTIONS(23),
    [sym_local_variable] = ACTIONS(25),
    [sym__single_quote] = ACTIONS(27),
    [anon_sym_PERCENT] = ACTIONS(23),
  },
  [19] = {
    [sym_expr] = STATE(95),
    [sym_literal] = STATE(60),
    [sym_container] = STATE(60),
    [sym_group] = STATE(61),
    [sym_block] = STATE(61),
    [sym_string] = STATE(62),
    [sym_boolean] = STATE(62),
    [sym_raw_string] = STATE(62),
    [sym_regex] = STATE(62),
    [sym_timestamp] = STATE(62),
    [sym__integer] = STATE(48),
    [sym_integer] = STATE(62),
    [sym__whole_number] = STATE(48),
    [sym_float] = STATE(62),
    [sym_query] = STATE(60),
    [sym_local_query] = STATE(66),
    [sym_target_query] = STATE(66),
    [sym_target_query_prefix] = STATE(24),
    [aux_sym_newline_repeat1] = STATE(15),
    [aux_sym_ws_repeat1] = STATE(15),
    [sym__horizontal_ws] = ACTIONS(85),
    [aux_sym_newline_token1] = ACTIONS(85),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [sym_null] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_s] = ACTIONS(13),
    [anon_sym_r] = ACTIONS(15),
    [anon_sym_t] = ACTIONS(17),
    [anon_sym_DASH] = ACTIONS(19),
    [aux_sym_whole_number_token1] = ACTIONS(21),
    [anon_sym_DOT] = ACTIONS(23),
    [sym_local_variable] = ACTIONS(25),
    [sym__single_quote] = ACTIONS(27),
    [anon_sym_PERCENT] = ACTIONS(23),
  },
  [20] = {
    [sym_expr] = STATE(83),
    [sym_literal] = STATE(60),
    [sym_container] = STATE(60),
    [sym_group] = STATE(61),
    [sym_block] = STATE(61),
    [sym_string] = STATE(62),
    [sym_boolean] = STATE(62),
    [sym_raw_string] = STATE(62),
    [sym_regex] = STATE(62),
    [sym_timestamp] = STATE(62),
    [sym__integer] = STATE(48),
    [sym_integer] = STATE(62),
    [sym__whole_number] = STATE(48),
    [sym_float] = STATE(62),
    [sym_query] = STATE(60),
    [sym_local_query] = STATE(66),
    [sym_target_query] = STATE(66),
    [sym_target_query_prefix] = STATE(24),
    [aux_sym_newline_repeat1] = STATE(21),
    [aux_sym_ws_repeat1] = STATE(21),
    [sym__horizontal_ws] = ACTIONS(77),
    [aux_sym_newline_token1] = ACTIONS(77),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [sym_null] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_s] = ACTIONS(13),
    [anon_sym_r] = ACTIONS(15),
    [anon_sym_t] = ACTIONS(17),
    [anon_sym_DASH] = ACTIONS(19),
    [aux_sym_whole_number_token1] = ACTIONS(21),
    [anon_sym_DOT] = ACTIONS(23),
    [sym_local_variable] = ACTIONS(25),
    [sym__single_quote] = ACTIONS(27),
    [anon_sym_PERCENT] = ACTIONS(23),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(89), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(21), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
    ACTIONS(92), 8,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      anon_sym_s,
      anon_sym_r,
      anon_sym_t,
      aux_sym_whole_number_token1,
      sym_local_variable,
    ACTIONS(87), 11,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_DOT,
      sym__single_quote,
      anon_sym_PIPE,
      anon_sym_PERCENT,
  [32] = 4,
    ACTIONS(96), 1,
      aux_sym_newline_token1,
    STATE(22), 1,
      aux_sym_newline_repeat1,
    ACTIONS(99), 8,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      anon_sym_s,
      anon_sym_r,
      anon_sym_t,
      aux_sym_whole_number_token1,
      sym_local_variable,
    ACTIONS(94), 12,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_DOT,
      sym__single_quote,
      anon_sym_PIPE,
      anon_sym_PERCENT,
  [63] = 5,
    ACTIONS(104), 1,
      aux_sym_newline_token1,
    STATE(22), 1,
      aux_sym_newline_repeat1,
    ACTIONS(94), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    ACTIONS(101), 7,
      sym__horizontal_ws,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_DOT,
      sym__single_quote,
      anon_sym_PERCENT,
    ACTIONS(108), 8,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      anon_sym_s,
      anon_sym_r,
      anon_sym_t,
      aux_sym_whole_number_token1,
      sym_local_variable,
  [94] = 6,
    ACTIONS(113), 1,
      anon_sym_LPAREN,
    ACTIONS(115), 1,
      sym__single_quote,
    ACTIONS(117), 1,
      aux_sym_query_field_token1,
    STATE(67), 1,
      sym_query_segments,
    STATE(27), 3,
      sym__query_segment,
      sym_query_field,
      sym_query_coalesce,
    ACTIONS(111), 6,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [120] = 1,
    ACTIONS(119), 9,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      sym__single_quote,
      aux_sym_query_field_token1,
  [132] = 7,
    ACTIONS(123), 1,
      sym__horizontal_ws,
    ACTIONS(126), 1,
      aux_sym_newline_token1,
    ACTIONS(129), 1,
      anon_sym_SEMI,
    STATE(12), 1,
      aux_sym_newline_repeat1,
    STATE(26), 1,
      aux_sym_exprs_repeat1,
    STATE(89), 1,
      aux_sym_ws_repeat1,
    ACTIONS(121), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [155] = 3,
    ACTIONS(134), 1,
      anon_sym_DOT,
    STATE(32), 1,
      aux_sym_query_segments_repeat1,
    ACTIONS(132), 6,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [170] = 3,
    ACTIONS(138), 1,
      anon_sym_DOT,
    STATE(28), 1,
      aux_sym_query_segments_repeat1,
    ACTIONS(136), 6,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [185] = 1,
    ACTIONS(141), 8,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_DOT,
      anon_sym_PIPE,
  [196] = 1,
    ACTIONS(143), 8,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_DOT,
      anon_sym_PIPE,
  [207] = 7,
    ACTIONS(145), 1,
      sym__horizontal_ws,
    ACTIONS(148), 1,
      aux_sym_newline_token1,
    ACTIONS(151), 1,
      anon_sym_SEMI,
    STATE(3), 1,
      aux_sym_newline_repeat1,
    STATE(26), 1,
      aux_sym_exprs_repeat1,
    STATE(78), 1,
      aux_sym_ws_repeat1,
    ACTIONS(45), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [230] = 3,
    ACTIONS(134), 1,
      anon_sym_DOT,
    STATE(28), 1,
      aux_sym_query_segments_repeat1,
    ACTIONS(153), 6,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [245] = 7,
    ACTIONS(157), 1,
      sym__horizontal_ws,
    ACTIONS(160), 1,
      aux_sym_newline_token1,
    ACTIONS(163), 1,
      anon_sym_SEMI,
    STATE(4), 1,
      aux_sym_newline_repeat1,
    STATE(31), 1,
      aux_sym_exprs_repeat1,
    STATE(88), 1,
      aux_sym_ws_repeat1,
    ACTIONS(155), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [268] = 2,
    ACTIONS(167), 1,
      anon_sym_DOT,
    ACTIONS(165), 6,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [280] = 5,
    ACTIONS(113), 1,
      anon_sym_LPAREN,
    ACTIONS(115), 1,
      sym__single_quote,
    ACTIONS(117), 1,
      aux_sym_query_field_token1,
    STATE(57), 1,
      sym_query_segments,
    STATE(27), 3,
      sym__query_segment,
      sym_query_field,
      sym_query_coalesce,
  [298] = 1,
    ACTIONS(169), 7,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_DOT,
  [308] = 5,
    ACTIONS(174), 1,
      anon_sym_RPAREN,
    ACTIONS(176), 1,
      anon_sym_PIPE,
    STATE(37), 1,
      aux_sym_query_coalesce_repeat1,
    ACTIONS(171), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(91), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [326] = 5,
    ACTIONS(115), 1,
      sym__single_quote,
    ACTIONS(117), 1,
      aux_sym_query_field_token1,
    STATE(69), 1,
      sym_query_field,
    ACTIONS(179), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(53), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [344] = 1,
    ACTIONS(181), 7,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_DOT,
  [354] = 5,
    ACTIONS(115), 1,
      sym__single_quote,
    ACTIONS(117), 1,
      aux_sym_query_field_token1,
    STATE(102), 1,
      sym_query_field,
    ACTIONS(179), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(53), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [372] = 5,
    ACTIONS(115), 1,
      sym__single_quote,
    ACTIONS(117), 1,
      aux_sym_query_field_token1,
    STATE(71), 1,
      sym_query_field,
    ACTIONS(183), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(38), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [390] = 5,
    ACTIONS(187), 1,
      anon_sym_RPAREN,
    ACTIONS(189), 1,
      anon_sym_PIPE,
    STATE(37), 1,
      aux_sym_query_coalesce_repeat1,
    ACTIONS(185), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(56), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [408] = 5,
    ACTIONS(115), 1,
      sym__single_quote,
    ACTIONS(117), 1,
      aux_sym_query_field_token1,
    STATE(102), 1,
      sym_query_field,
    ACTIONS(191), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(44), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [426] = 5,
    ACTIONS(115), 1,
      sym__single_quote,
    ACTIONS(117), 1,
      aux_sym_query_field_token1,
    STATE(103), 1,
      sym_query_field,
    ACTIONS(179), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(53), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [444] = 5,
    ACTIONS(115), 1,
      sym__single_quote,
    ACTIONS(117), 1,
      aux_sym_query_field_token1,
    STATE(99), 1,
      sym_query_field,
    ACTIONS(193), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(40), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [462] = 1,
    ACTIONS(136), 7,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_DOT,
  [472] = 1,
    ACTIONS(195), 7,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_DOT,
  [482] = 2,
    ACTIONS(199), 1,
      anon_sym_DOT,
    ACTIONS(197), 6,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [494] = 1,
    ACTIONS(201), 7,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_DOT,
  [504] = 5,
    ACTIONS(189), 1,
      anon_sym_PIPE,
    ACTIONS(205), 1,
      anon_sym_RPAREN,
    STATE(37), 1,
      aux_sym_query_coalesce_repeat1,
    ACTIONS(203), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(58), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [522] = 1,
    ACTIONS(207), 6,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [531] = 1,
    ACTIONS(209), 6,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [540] = 3,
    ACTIONS(87), 2,
      sym__single_quote,
      aux_sym_query_field_token1,
    ACTIONS(211), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(53), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [553] = 1,
    ACTIONS(214), 6,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [562] = 1,
    ACTIONS(216), 6,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [571] = 4,
    ACTIONS(218), 1,
      anon_sym_RPAREN,
    ACTIONS(220), 1,
      anon_sym_PIPE,
    ACTIONS(77), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(21), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [586] = 1,
    ACTIONS(222), 6,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [595] = 4,
    ACTIONS(187), 1,
      anon_sym_RPAREN,
    ACTIONS(220), 1,
      anon_sym_PIPE,
    ACTIONS(77), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(21), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [610] = 1,
    ACTIONS(224), 6,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [619] = 1,
    ACTIONS(226), 6,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [628] = 1,
    ACTIONS(228), 6,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [637] = 1,
    ACTIONS(230), 6,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [646] = 1,
    ACTIONS(232), 6,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [655] = 1,
    ACTIONS(234), 6,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [664] = 1,
    ACTIONS(236), 6,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [673] = 1,
    ACTIONS(238), 6,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [682] = 1,
    ACTIONS(240), 6,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [691] = 1,
    ACTIONS(242), 6,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [700] = 4,
    ACTIONS(189), 1,
      anon_sym_PIPE,
    STATE(42), 1,
      aux_sym_query_coalesce_repeat1,
    ACTIONS(244), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(91), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [715] = 1,
    ACTIONS(246), 6,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [724] = 4,
    ACTIONS(189), 1,
      anon_sym_PIPE,
    STATE(50), 1,
      aux_sym_query_coalesce_repeat1,
    ACTIONS(244), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(91), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [739] = 1,
    ACTIONS(248), 6,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [748] = 1,
    ACTIONS(250), 6,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [757] = 4,
    ACTIONS(113), 1,
      anon_sym_LPAREN,
    ACTIONS(115), 1,
      sym__single_quote,
    ACTIONS(117), 1,
      aux_sym_query_field_token1,
    STATE(46), 3,
      sym__query_segment,
      sym_query_field,
      sym_query_coalesce,
  [772] = 1,
    ACTIONS(252), 6,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [781] = 1,
    ACTIONS(254), 6,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [790] = 1,
    ACTIONS(256), 6,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [799] = 5,
    ACTIONS(77), 1,
      sym__horizontal_ws,
    ACTIONS(258), 1,
      aux_sym_newline_token1,
    ACTIONS(260), 1,
      anon_sym_SEMI,
    STATE(5), 1,
      aux_sym_newline_repeat1,
    STATE(21), 1,
      aux_sym_ws_repeat1,
  [815] = 3,
    ACTIONS(262), 1,
      ts_builtin_sym_end,
    ACTIONS(264), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(97), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [827] = 3,
    ACTIONS(266), 1,
      anon_sym_RPAREN,
    ACTIONS(77), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(21), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [839] = 3,
    ACTIONS(268), 1,
      anon_sym_RBRACE,
    ACTIONS(77), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(21), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [851] = 3,
    ACTIONS(272), 1,
      anon_sym_RBRACE,
    ACTIONS(270), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(81), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [863] = 1,
    ACTIONS(274), 5,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [871] = 3,
    ACTIONS(262), 1,
      ts_builtin_sym_end,
    ACTIONS(77), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(21), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [883] = 3,
    ACTIONS(276), 1,
      aux_sym_newline_token1,
    STATE(85), 1,
      aux_sym_newline_repeat1,
    ACTIONS(94), 3,
      sym__horizontal_ws,
      sym__single_quote,
      aux_sym_query_field_token1,
  [895] = 3,
    ACTIONS(272), 1,
      anon_sym_RBRACE,
    ACTIONS(77), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(21), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [907] = 3,
    ACTIONS(279), 1,
      ts_builtin_sym_end,
    ACTIONS(281), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(84), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [919] = 5,
    ACTIONS(77), 1,
      sym__horizontal_ws,
    ACTIONS(283), 1,
      aux_sym_newline_token1,
    ACTIONS(285), 1,
      anon_sym_SEMI,
    STATE(2), 1,
      aux_sym_newline_repeat1,
    STATE(21), 1,
      aux_sym_ws_repeat1,
  [935] = 5,
    ACTIONS(77), 1,
      sym__horizontal_ws,
    ACTIONS(287), 1,
      aux_sym_newline_token1,
    ACTIONS(289), 1,
      anon_sym_SEMI,
    STATE(14), 1,
      aux_sym_newline_repeat1,
    STATE(21), 1,
      aux_sym_ws_repeat1,
  [951] = 1,
    ACTIONS(121), 5,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [959] = 3,
    ACTIONS(220), 1,
      anon_sym_PIPE,
    ACTIONS(77), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(21), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [971] = 3,
    ACTIONS(293), 1,
      anon_sym_RPAREN,
    ACTIONS(291), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(80), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [983] = 1,
    ACTIONS(295), 5,
      ts_builtin_sym_end,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [991] = 3,
    ACTIONS(299), 1,
      anon_sym_RBRACE,
    ACTIONS(297), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(86), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [1003] = 3,
    ACTIONS(303), 1,
      anon_sym_RPAREN,
    ACTIONS(301), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(96), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [1015] = 3,
    ACTIONS(293), 1,
      anon_sym_RPAREN,
    ACTIONS(77), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(21), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [1027] = 3,
    ACTIONS(305), 1,
      ts_builtin_sym_end,
    ACTIONS(77), 2,
      sym__horizontal_ws,
      aux_sym_newline_token1,
    STATE(21), 2,
      aux_sym_newline_repeat1,
      aux_sym_ws_repeat1,
  [1039] = 4,
    ACTIONS(307), 1,
      anon_sym_SQUOTE,
    ACTIONS(309), 1,
      aux_sym_raw_token1,
    ACTIONS(311), 1,
      aux_sym_raw_token2,
    STATE(104), 1,
      aux_sym_raw_repeat1,
  [1052] = 1,
    ACTIONS(174), 4,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_RPAREN,
      anon_sym_PIPE,
  [1059] = 4,
    ACTIONS(313), 1,
      aux_sym_string_token1,
    ACTIONS(315), 1,
      anon_sym_BSLASH,
    ACTIONS(317), 1,
      sym__single_quote,
    STATE(105), 1,
      aux_sym_string_repeat1,
  [1072] = 4,
    ACTIONS(319), 1,
      aux_sym_string_token1,
    ACTIONS(322), 1,
      anon_sym_BSLASH,
    ACTIONS(325), 1,
      sym__single_quote,
    STATE(101), 1,
      aux_sym_string_repeat1,
  [1085] = 1,
    ACTIONS(327), 4,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_RPAREN,
      anon_sym_PIPE,
  [1092] = 1,
    ACTIONS(329), 4,
      sym__horizontal_ws,
      aux_sym_newline_token1,
      anon_sym_RPAREN,
      anon_sym_PIPE,
  [1099] = 4,
    ACTIONS(331), 1,
      anon_sym_SQUOTE,
    ACTIONS(333), 1,
      aux_sym_raw_token1,
    ACTIONS(335), 1,
      aux_sym_raw_token2,
    STATE(106), 1,
      aux_sym_raw_repeat1,
  [1112] = 4,
    ACTIONS(315), 1,
      anon_sym_BSLASH,
    ACTIONS(337), 1,
      aux_sym_string_token1,
    ACTIONS(339), 1,
      sym__single_quote,
    STATE(101), 1,
      aux_sym_string_repeat1,
  [1125] = 4,
    ACTIONS(341), 1,
      anon_sym_SQUOTE,
    ACTIONS(343), 1,
      aux_sym_raw_token1,
    ACTIONS(346), 1,
      aux_sym_raw_token2,
    STATE(106), 1,
      aux_sym_raw_repeat1,
  [1138] = 1,
    ACTIONS(325), 3,
      aux_sym_string_token1,
      anon_sym_BSLASH,
      sym__single_quote,
  [1144] = 2,
    ACTIONS(349), 1,
      aux_sym_whole_number_token1,
    STATE(70), 1,
      sym__whole_number,
  [1151] = 2,
    ACTIONS(351), 1,
      aux_sym_whole_number_token1,
    STATE(39), 1,
      sym__whole_number,
  [1158] = 2,
    ACTIONS(353), 1,
      anon_sym_SQUOTE,
    STATE(73), 1,
      sym_raw,
  [1165] = 2,
    ACTIONS(353), 1,
      anon_sym_SQUOTE,
    STATE(51), 1,
      sym_raw,
  [1172] = 2,
    ACTIONS(353), 1,
      anon_sym_SQUOTE,
    STATE(72), 1,
      sym_raw,
  [1179] = 1,
    ACTIONS(355), 1,
      sym_quoted_field,
  [1183] = 1,
    ACTIONS(357), 1,
      sym__single_quote,
  [1187] = 1,
    ACTIONS(359), 1,
      aux_sym_string_token2,
  [1191] = 1,
    ACTIONS(361), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(21)] = 0,
  [SMALL_STATE(22)] = 32,
  [SMALL_STATE(23)] = 63,
  [SMALL_STATE(24)] = 94,
  [SMALL_STATE(25)] = 120,
  [SMALL_STATE(26)] = 132,
  [SMALL_STATE(27)] = 155,
  [SMALL_STATE(28)] = 170,
  [SMALL_STATE(29)] = 185,
  [SMALL_STATE(30)] = 196,
  [SMALL_STATE(31)] = 207,
  [SMALL_STATE(32)] = 230,
  [SMALL_STATE(33)] = 245,
  [SMALL_STATE(34)] = 268,
  [SMALL_STATE(35)] = 280,
  [SMALL_STATE(36)] = 298,
  [SMALL_STATE(37)] = 308,
  [SMALL_STATE(38)] = 326,
  [SMALL_STATE(39)] = 344,
  [SMALL_STATE(40)] = 354,
  [SMALL_STATE(41)] = 372,
  [SMALL_STATE(42)] = 390,
  [SMALL_STATE(43)] = 408,
  [SMALL_STATE(44)] = 426,
  [SMALL_STATE(45)] = 444,
  [SMALL_STATE(46)] = 462,
  [SMALL_STATE(47)] = 472,
  [SMALL_STATE(48)] = 482,
  [SMALL_STATE(49)] = 494,
  [SMALL_STATE(50)] = 504,
  [SMALL_STATE(51)] = 522,
  [SMALL_STATE(52)] = 531,
  [SMALL_STATE(53)] = 540,
  [SMALL_STATE(54)] = 553,
  [SMALL_STATE(55)] = 562,
  [SMALL_STATE(56)] = 571,
  [SMALL_STATE(57)] = 586,
  [SMALL_STATE(58)] = 595,
  [SMALL_STATE(59)] = 610,
  [SMALL_STATE(60)] = 619,
  [SMALL_STATE(61)] = 628,
  [SMALL_STATE(62)] = 637,
  [SMALL_STATE(63)] = 646,
  [SMALL_STATE(64)] = 655,
  [SMALL_STATE(65)] = 664,
  [SMALL_STATE(66)] = 673,
  [SMALL_STATE(67)] = 682,
  [SMALL_STATE(68)] = 691,
  [SMALL_STATE(69)] = 700,
  [SMALL_STATE(70)] = 715,
  [SMALL_STATE(71)] = 724,
  [SMALL_STATE(72)] = 739,
  [SMALL_STATE(73)] = 748,
  [SMALL_STATE(74)] = 757,
  [SMALL_STATE(75)] = 772,
  [SMALL_STATE(76)] = 781,
  [SMALL_STATE(77)] = 790,
  [SMALL_STATE(78)] = 799,
  [SMALL_STATE(79)] = 815,
  [SMALL_STATE(80)] = 827,
  [SMALL_STATE(81)] = 839,
  [SMALL_STATE(82)] = 851,
  [SMALL_STATE(83)] = 863,
  [SMALL_STATE(84)] = 871,
  [SMALL_STATE(85)] = 883,
  [SMALL_STATE(86)] = 895,
  [SMALL_STATE(87)] = 907,
  [SMALL_STATE(88)] = 919,
  [SMALL_STATE(89)] = 935,
  [SMALL_STATE(90)] = 951,
  [SMALL_STATE(91)] = 959,
  [SMALL_STATE(92)] = 971,
  [SMALL_STATE(93)] = 983,
  [SMALL_STATE(94)] = 991,
  [SMALL_STATE(95)] = 1003,
  [SMALL_STATE(96)] = 1015,
  [SMALL_STATE(97)] = 1027,
  [SMALL_STATE(98)] = 1039,
  [SMALL_STATE(99)] = 1052,
  [SMALL_STATE(100)] = 1059,
  [SMALL_STATE(101)] = 1072,
  [SMALL_STATE(102)] = 1085,
  [SMALL_STATE(103)] = 1092,
  [SMALL_STATE(104)] = 1099,
  [SMALL_STATE(105)] = 1112,
  [SMALL_STATE(106)] = 1125,
  [SMALL_STATE(107)] = 1138,
  [SMALL_STATE(108)] = 1144,
  [SMALL_STATE(109)] = 1151,
  [SMALL_STATE(110)] = 1158,
  [SMALL_STATE(111)] = 1165,
  [SMALL_STATE(112)] = 1172,
  [SMALL_STATE(113)] = 1179,
  [SMALL_STATE(114)] = 1183,
  [SMALL_STATE(115)] = 1187,
  [SMALL_STATE(116)] = 1191,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(112),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(111),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(110),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exprs, 3),
  [31] = {.entry = {.count = 3, .reusable = true}}, REDUCE(aux_sym_ws_repeat1, 1), REDUCE(sym_exprs, 3), SHIFT(18),
  [35] = {.entry = {.count = 3, .reusable = true}}, REDUCE(aux_sym_ws_repeat1, 1), REDUCE(sym_exprs, 3), SHIFT(23),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_ws_repeat1, 1),
  [41] = {.entry = {.count = 3, .reusable = true}}, REDUCE(aux_sym_ws_repeat1, 1), REDUCE(sym_exprs, 3), SHIFT(20),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exprs, 2),
  [47] = {.entry = {.count = 3, .reusable = true}}, REDUCE(aux_sym_ws_repeat1, 1), REDUCE(sym_exprs, 2), SHIFT(20),
  [51] = {.entry = {.count = 3, .reusable = true}}, REDUCE(aux_sym_ws_repeat1, 1), REDUCE(sym_exprs, 2), SHIFT(23),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exprs, 4),
  [57] = {.entry = {.count = 3, .reusable = true}}, REDUCE(aux_sym_ws_repeat1, 1), REDUCE(sym_exprs, 4), SHIFT(18),
  [61] = {.entry = {.count = 3, .reusable = true}}, REDUCE(aux_sym_ws_repeat1, 1), REDUCE(sym_exprs, 4), SHIFT(23),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_exprs, 3), SHIFT(18),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_exprs, 3), SHIFT(20),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_exprs, 2), SHIFT(20),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_exprs, 4), SHIFT(18),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_ws_repeat1, 2),
  [89] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_ws_repeat1, 2), SHIFT_REPEAT(21),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_ws_repeat1, 2),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_newline_repeat1, 2),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_newline_repeat1, 2), SHIFT_REPEAT(22),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_newline_repeat1, 2),
  [101] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_ws_repeat1, 1), REDUCE(aux_sym_newline_repeat1, 2),
  [104] = {.entry = {.count = 3, .reusable = true}}, REDUCE(aux_sym_ws_repeat1, 1), REDUCE(aux_sym_newline_repeat1, 2), SHIFT(22),
  [108] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_ws_repeat1, 1), REDUCE(aux_sym_newline_repeat1, 2),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_target_query, 1),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_target_query_prefix, 1),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_exprs_repeat1, 2),
  [123] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_exprs_repeat1, 2), SHIFT_REPEAT(89),
  [126] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_exprs_repeat1, 2), SHIFT_REPEAT(12),
  [129] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_exprs_repeat1, 2), SHIFT_REPEAT(16),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_segments, 1),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_query_segments_repeat1, 2),
  [138] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_query_segments_repeat1, 2), SHIFT_REPEAT(74),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_field, 3),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_field, 1),
  [145] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_exprs, 2), SHIFT(78),
  [148] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_exprs, 2), SHIFT(3),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_segments, 2),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exprs, 1),
  [157] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_exprs, 1), SHIFT(88),
  [160] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_exprs, 1), SHIFT(4),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_local_query, 1),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_coalesce, 4),
  [171] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_query_coalesce_repeat1, 2), SHIFT_REPEAT(91),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_query_coalesce_repeat1, 2),
  [176] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_query_coalesce_repeat1, 2), SHIFT_REPEAT(45),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__integer, 2),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_coalesce, 5),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_integer, 1),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_coalesce, 6),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_regex, 2),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_raw, 3),
  [211] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_ws_repeat1, 2), SHIFT_REPEAT(53),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_raw, 2),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_local_query, 3),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 1),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_container, 1),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 5),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 5),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 3),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query, 1),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_target_query, 2),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 3),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_raw_string, 2),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_timestamp, 2),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 4),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 4),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 2),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [274] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_exprs_repeat1, 3),
  [276] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_newline_repeat1, 2), SHIFT_REPEAT(85),
  [279] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [295] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_exprs_repeat1, 4),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [305] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 3),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [311] = {.entry = {.count = 1, .reusable = false}}, SHIFT(104),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [319] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(101),
  [322] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(115),
  [325] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2),
  [327] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_query_coalesce_repeat1, 3),
  [329] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_query_coalesce_repeat1, 4),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [335] = {.entry = {.count = 1, .reusable = false}}, SHIFT(106),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [341] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_raw_repeat1, 2),
  [343] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_raw_repeat1, 2), SHIFT_REPEAT(106),
  [346] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_raw_repeat1, 2), SHIFT_REPEAT(106),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [353] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [361] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_vrl(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
