name: Cross

on:
  workflow_call:
    inputs:
      ref:
        description: "Git ref to checkout"
        required: false
        type: string

permissions:
  contents: read

jobs:
  cross-linux:
    name: Cross - ${{ matrix.target }}
    runs-on: ubuntu-24.04
    timeout-minutes: 90
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
          - armv7-unknown-linux-gnueabihf
          - armv7-unknown-linux-musleabihf
          - arm-unknown-linux-gnueabi
          - arm-unknown-linux-musleabi
    steps:
      - name: Checkout branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ inputs.ref }}

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22

      - run: echo "::add-matcher::.github/matchers/rust.json"

      # Why is this build, not check? Because we need to make sure the linking phase works.
      # aarch64 and musl in particular are notoriously hard to link.
      # While it may be tempting to slot a `check` in here for quickness, please don't.
      - name: Build
        run: nix build .#vector-${{ matrix.target }} --print-build-logs

      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: "vector-${{ matrix.target }}"
          path: "./result/bin/vector"
