name: Integration - Windows

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      windows: ${{ steps.filter.outputs.windows }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4.0.3
        id: filter
        with:
          filters: |
            windows:
              - "src/sources/windows_event_log/**"
              - "src/internal_events/windows_event_log.rs"
              - "src/internal_events/windows.rs"
              - "src/vector_windows.rs"
              - "src/service.rs"
              - "tests/integration/windows-event-log/**"
              - ".github/workflows/integration_windows.yml"

  run-test-integration-windows:
    needs: changes
    if: needs.changes.outputs.windows == 'true'
    runs-on: windows-2025-8core
    timeout-minutes: 60
    steps:
      - name: Checkout branch
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.10"

      - run: .\scripts\environment\bootstrap-windows-2025.ps1

      - name: Run Windows Event Log integration tests
        run: make test-integration-windows-event-log

  test-integration-windows:
    if: always()
    runs-on: ubuntu-latest
    needs: run-test-integration-windows
    steps:
      - run: |
          if [[ "${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
            echo "One or more jobs failed or were cancelled"
            exit 1
          fi
