name: Nightly

permissions:
  contents: read # Restrictive default

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * 2-6" # Runs at 5:00 AM UTC, Tuesday through Saturday

jobs:
  Nightly:
    permissions:
      contents: write # Required to create/update releases and tags
      packages: write # Required to push container images to GHCR
    uses: ./.github/workflows/publish.yml
    with:
      git_ref: ${{ github.ref }}
      channel: nightly
    secrets: inherit
