name: Release Suite

permissions:
  contents: read # Restrictive default

on:
  push:
    tags:
      - v0.*
      - v1.*

jobs:
  Release:
    permissions:
      contents: write # Required to create/update releases and tags
      packages: write # Required to push container images to GHCR
    uses: ./.github/workflows/publish.yml
    with:
      git_ref: ${{ github.ref }}
      channel: release
    secrets: inherit
