name: Check Spelling

on:
  pull_request:
    branches:
      - "**"
    tags-ignore:
      - "**"
    types:
      - "opened"
      - "reopened"
      - "synchronize"

permissions:
  contents: read

jobs:
  spelling:
    name: Check Spelling
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    if: "contains(github.event_name, 'pull_request') || github.event_name == 'push'"
    concurrency:
      group: spelling-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4
      - uses: crate-ci/typos@d43b6c087ac471e2ea7b8af622ff15f05c0c365b # v1.50.1
