name: Check Spelling

on:
  pull_request:
    branches:
      - "**"
    tags-ignore:
      - "**"
    types:
      - "opened"
      - "reopened"
      - "synchronize"

permissions:
  contents: read

jobs:
  spelling:
    name: Check Spelling
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    if: "contains(github.event_name, 'pull_request') || github.event_name == 'push'"
    concurrency:
      group: spelling-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos-action@v1
