name: Unit - Windows

on:
  workflow_call:
    inputs:
      ref:
        description: "Git ref to checkout"
        required: false
        type: string

permissions:
  contents: read

jobs:
  test-windows:
    runs-on: windows-2025-8core
    timeout-minutes: 60
    steps:
      - name: Checkout branch
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ inputs.ref }}

      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.10"
      - run: .\scripts\environment\bootstrap-windows-2025.ps1
      - run: make test

      - name: Upload test results to Datadog
        if: always()
        run: scripts/upload-test-results.sh
        shell: bash
